// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: common/v1/common.proto

/* eslint-disable */

/** 状态设置请求参数 */
export interface SetStatusRequest {
  /** 主键id */
  id: number;
  /** 状态 */
  status: number;
}

/** 树形选项响应 */
export interface TreeOptionResponse {
  /** 选项列表 */
  list: TreeOptionResponse_Option[];
}

/** 树形选项 */
export interface TreeOptionResponse_Option {
  /** 选项名 */
  label: string;
  /** 选项值 */
  value: number;
  /** 是否禁用 */
  disabled: boolean;
  /** 是否存在子节点 */
  has_children: boolean;
  /** 子节点树 */
  children: TreeOptionResponse_Option[];
}

/** 下拉选项响应 */
export interface SelectOptionResponse {
  /** 选项列表 */
  list: SelectOptionResponse_Option[];
}

/** 下拉选项 */
export interface SelectOptionResponse_Option {
  /** 选项名 */
  label: string;
  /** 选项值 */
  value: number;
  /** 是否禁用 */
  disabled: boolean;
}

/** 应用树形选项响应 */
export interface AppTreeOptionResponse {
  /** 选项列表 */
  list: AppTreeOptionResponse_Option[];
}

/** 应用树形选项 */
export interface AppTreeOptionResponse_Option {
  /** 值。必填 */
  value: string;
  /** 显示文字。必填 */
  text: string;
  /** 是否默认选中。默认值false */
  selected: boolean;
  /** 是否禁用。默认值false */
  disable: boolean;
  /** 子节点树 */
  children: AppTreeOptionResponse_Option[];
}
