// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: common/v1/enum.proto

/* eslint-disable */

/** 状态 */
export enum Status {
  /** STATUS_UNSPECIFIED - 未知状态 */
  STATUS_UNSPECIFIED = 0,
  /** STATUS_ENABLE - 启用 */
  STATUS_ENABLE = 1,
  /** STATUS_DISABLE - 禁用 */
  STATUS_DISABLE = 2,
}

/** 定时任务日志状态 */
export enum BaseJobLogStatus {
  /** BASE_JOB_LOG_STATUS_UNSPECIFIED - 未指定定时任务日志状态 */
  BASE_JOB_LOG_STATUS_UNSPECIFIED = 0,
  /** BASE_JOB_LOG_STATUS_SUCCESS - 成功 */
  BASE_JOB_LOG_STATUS_SUCCESS = 1,
  /** BASE_JOB_LOG_STATUS_FAIL - 失败 */
  BASE_JOB_LOG_STATUS_FAIL = 2,
}
