// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/app/v1/auth.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseUserIDType } from "../../common/v1/common";

/** 获取用户资料请求参数 */
export interface GetUserProfileRequest {
}

/** 用户资料表单 */
export interface UserProfileForm {
  /** 用户账号 */
  user_name: string;
  /** 用户昵称 */
  nick_name: string;
  /** 性别 */
  gender: number;
  /** 手机号 */
  phone: string;
  /** 邮箱 */
  email: string;
  /** 证件类型：枚举【BaseUserIDType】 */
  id_type: BaseUserIDType;
  /** 证件号 */
  id_code: string;
  /** 头像 */
  avatar: string;
}

/** 更新用户资料请求参数 */
export interface UpdateUserProfileRequest {
  /** 用户资料 */
  user_profile: UserProfileForm | undefined;
}

/** 手机号授权请求参数 */
export interface BindUserPhoneRequest {
  /** 授权信息 */
  code: string;
}

/** 手机号授权响应 */
export interface BindUserPhoneResponse {
  /** 手机号 */
  phone: string;
}

/** App用户认证服务 */
export interface AuthService {
  /** 获取已经登录的用户的数据 */
  GetUserProfile(request: GetUserProfileRequest): Promise<UserProfileForm>;
  /** 修改个人中心用户信息 */
  UpdateUserProfile(request: UpdateUserProfileRequest): Promise<Empty>;
  /** 手机号授权 */
  BindUserPhone(request: BindUserPhoneRequest): Promise<BindUserPhoneResponse>;
}
