// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/app/v1/base_menu.proto

/* eslint-disable */

/** 移动端菜单查询条件 */
export interface ListBaseMenuRequest {
}

/** 移动端菜单响应 */
export interface ListBaseMenuResponse {
  /** 移动端扁平菜单 */
  items: BaseMenu[];
}

/** 移动端菜单 */
export interface BaseMenu {
  /** 菜单ID */
  id: number;
  /** 父级菜单ID */
  parent_id: number;
  /** 逻辑路由地址 */
  path: string;
  /** 逻辑路由名称 */
  name: string;
  /** 移动端菜单元信息 */
  meta: BaseMenuMeta | undefined;
}

/** 移动端菜单元信息 */
export interface BaseMenuMeta {
  /** 菜单标题 */
  title: string;
  /** 菜单图标 */
  icon?:
    | string
    | undefined;
  /** 移动端页面配置 */
  app: BaseMenuAppMeta | undefined;
}

/** 移动端页面配置 */
export interface BaseMenuAppMeta {
  /** 已注册的稳定视图键 */
  view_key: string;
  /** 页面访问模式 */
  access: string;
  /** 是否显示在自绘标签栏 */
  in_tab_bar: boolean;
  /** 标签栏选中图标 */
  selected_icon?: string | undefined;
}

/** App菜单服务 */
export interface BaseMenuService {
  /** 查询移动端菜单 */
  ListBaseMenu(request: ListBaseMenuRequest): Promise<ListBaseMenuResponse>;
}
