// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/app/v1/base_area.proto

/* eslint-disable */
import type { AppTreeOptionResponse_Option } from "../../../common/v1/common";

/** 行政区域树形查询条件 */
export interface TreeBaseAreaRequest {
}

/** 行政区域树形响应 */
export interface TreeBaseAreaResponse {
  /** 行政区域树形选项 */
  areas: AppTreeOptionResponse_Option[];
}

/** App行政区域服务 */
export interface BaseAreaService {
  /** 查询行政区域树形列表 */
  TreeBaseArea(request: TreeBaseAreaRequest): Promise<TreeBaseAreaResponse>;
}
