// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/app/v1/base_dict.proto

/* eslint-disable */

/** 查询字典请求参数 */
export interface GetBaseDictRequest {
  /** 字典编号 */
  code: string;
}

/** 字典表单 */
export interface BaseDictForm {
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 字典属性 */
  items: BaseDictForm_DictItem[];
}

/** 字典项 */
export interface BaseDictForm_DictItem {
  /** 字典值 */
  value: string;
  /** 字典项标签 */
  label: string;
}

/** App字典服务 */
export interface BaseDictService {
  /** 查询字典 */
  GetBaseDict(request: GetBaseDictRequest): Promise<BaseDictForm>;
}
