// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/ai_message.proto

/* eslint-disable */
import type { AiAttachment, AiMessage, AiSession } from "./ai_session";

/** AI 助手消息更新请求 */
export interface UpdateAiMessageRequest {
  /** 会话ID */
  session_id: string;
  /** 消息ID */
  message_id: string;
  /** 更新后的消息内容 */
  content: string;
}

/** AI 助手消息发送响应 */
export interface SendAiMessageResponse {
  /** 新增消息列表 */
  messages: AiMessage[];
  /** 最新会话信息 */
  session: AiSession | undefined;
}

/** AI 助手消息删除请求 */
export interface DeleteAiMessageRequest {
  /** 会话ID */
  session_id: string;
  /** 消息ID */
  message_id: string;
}

/** AI 助手消息删除响应 */
export interface DeleteAiMessageResponse {
}

/** AI 助手消息发送请求 */
export interface SendAiMessageRequest {
  /** 会话ID */
  session_id: string;
  /** 消息内容 */
  content: string;
  /** 附件列表 */
  attachments: AiAttachment[];
  /** 助手动作 */
  action: AiAction | undefined;
}

/** AI 助手失败消息重试请求 */
export interface RetryAiUserMessageRequest {
  /** 会话ID */
  session_id: string;
  /** 失败消息ID */
  message_id: string;
}

/** AI 助手输出重新生成请求 */
export interface RegenerateAiMessageRequest {
  /** 会话ID */
  session_id: string;
  /** 消息ID */
  message_id: string;
}

/** AI 助手动作 */
export interface AiAction {
  /** 流程标识 */
  flow: string;
  /** 流程步骤 */
  step: string;
  /** 动作类型 */
  type: string;
  /** 动作负载JSON */
  payload_json: string;
  /** 动作来源消息ID */
  source_message_id: string;
  /** 动作唯一ID */
  action_id: string;
  /** 流程状态版本 */
  flow_version: number;
}

/** Base AI 助手消息服务 */
export interface AiMessageService {
  /** 更新 AI 助手消息并重新生成输出 */
  UpdateAiMessage(request: UpdateAiMessageRequest): Promise<SendAiMessageResponse>;
  /** 删除 AI 助手消息 */
  DeleteAiMessage(request: DeleteAiMessageRequest): Promise<DeleteAiMessageResponse>;
  /** 发送 AI 助手消息 */
  SendAiMessage(request: SendAiMessageRequest): Promise<SendAiMessageResponse>;
  /** 重试失败的 AI 助手消息 */
  RetryAiUserMessage(request: RetryAiUserMessageRequest): Promise<SendAiMessageResponse>;
  /** 重新生成 AI 助手输出 */
  RegenerateAiMessage(request: RegenerateAiMessageRequest): Promise<SendAiMessageResponse>;
}
