// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/ai_session.proto

/* eslint-disable */
import type { Timestamp } from "../../google/protobuf/timestamp";
import type { AiToolCall, Terminal } from "./ai_tool";

/** AI 助手消息状态。 */
export enum AiMessageStatus {
  /** AI_MESSAGE_STATUS_UNSPECIFIED - 未指定 AI 助手消息状态。 */
  AI_MESSAGE_STATUS_UNSPECIFIED = 0,
  /** AI_MESSAGE_STATUS_GENERATING - 生成中。 */
  AI_MESSAGE_STATUS_GENERATING = 1,
  /** AI_MESSAGE_STATUS_SUCCESS - 成功。 */
  AI_MESSAGE_STATUS_SUCCESS = 2,
  /** AI_MESSAGE_STATUS_FAILED - 失败。 */
  AI_MESSAGE_STATUS_FAILED = 3,
}

/** AI 助手消息列表查询条件 */
export interface ListAiMessageRequest {
  /** 会话ID */
  session_id: string;
}

/** AI 助手消息列表响应 */
export interface ListAiMessageResponse {
  /** 消息列表 */
  messages: AiMessage[];
}

/** AI 助手会话列表查询条件 */
export interface ListAiSessionRequest {
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手会话列表响应 */
export interface ListAiSessionResponse {
  /** 会话列表 */
  sessions: AiSession[];
}

/** AI 助手会话创建请求 */
export interface CreateAiSessionRequest {
  /** 会话标题 */
  title: string;
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手会话创建响应 */
export interface CreateAiSessionResponse {
  /** 会话信息 */
  session: AiSession | undefined;
}

/** AI 助手分支会话创建请求 */
export interface CreateAiSessionBranchRequest {
  /** 来源会话ID */
  source_session_id: string;
  /** 分支锚点消息ID */
  anchor_message_id: string;
  /** 分支会话标题 */
  title: string;
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手分支会话创建响应 */
export interface CreateAiSessionBranchResponse {
  /** 新会话信息 */
  session:
    | AiSession
    | undefined;
  /** 新会话消息列表 */
  messages: AiMessage[];
}

/** AI 助手会话更新请求 */
export interface UpdateAiSessionRequest {
  /** 会话ID */
  id: string;
  /** 会话标题 */
  title: string;
}

/** AI 助手会话更新响应 */
export interface UpdateAiSessionResponse {
  /** 会话信息 */
  session: AiSession | undefined;
}

/** AI 助手会话删除请求 */
export interface DeleteAiSessionRequest {
  /** 会话ID */
  id: string;
}

/** AI 助手会话删除响应 */
export interface DeleteAiSessionResponse {
}

/** AI 助手会话 */
export interface AiSession {
  /** 会话ID */
  id: string;
  /** 会话标题 */
  title: string;
  /** 会话摘要 */
  summary: string;
  /** 更新时间 */
  updated_at:
    | Timestamp
    | undefined;
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手消息 */
export interface AiMessage {
  /** 消息ID */
  id: string;
  /** 输入内容 */
  input_content:
    | AiInputContent
    | undefined;
  /** 输出内容 */
  output_content:
    | AiOutputContent
    | undefined;
  /** 附件列表 */
  attachments: AiAttachment[];
  /** 创建时间 */
  created_at:
    | Timestamp
    | undefined;
  /** 消息生成状态：枚举【AiMessageStatus】 */
  status: AiMessageStatus;
  /** Token 统计 */
  token:
    | AiToken
    | undefined;
  /** 本次消息使用的工具调用记录 */
  tools: AiToolCall[];
  /** 首 Token 耗时毫秒 */
  first_token_ms: number;
  /** 总耗时毫秒 */
  duration_ms: number;
}

/** AI 助手输入内容 */
export interface AiInputContent {
  /** 内容类型 */
  kind: string;
  /** 内容正文 */
  content: string;
}

/** AI 助手输出内容 */
export interface AiOutputContent {
  /** 内容类型 */
  kind: string;
  /** 内容正文 */
  content: string;
  /** 回复来源：llm/fallback */
  reply_source: string;
  /** 回复使用的模型名称 */
  model: string;
  /** 是否为降级回复 */
  fallback: boolean;
  /** 降级原因 */
  fallback_reason: string;
  /** 流程标识 */
  flow: string;
  /** 流程步骤 */
  step: string;
  /** 移动端结构化内容JSON */
  blocks_json: string;
}

/** AI 助手 Token 统计 */
export interface AiToken {
  /** 输入 Token 数 */
  input: number;
  /** 输出 Token 数 */
  output: number;
  /** 缓存 Token 数 */
  cache: number;
  /** 总 Token 数 */
  total: number;
}

/** AI 助手附件 */
export interface AiAttachment {
  /** 附件ID */
  id: string;
  /** 附件名称 */
  name: string;
  /** 附件大小 */
  size: number;
  /** 附件地址 */
  url: string;
  /** 附件 MIME 类型 */
  mime_type: string;
}

/** Base AI 助手会话服务 */
export interface AiSessionService {
  /** 查询 AI 助手消息列表 */
  ListAiMessage(request: ListAiMessageRequest): Promise<ListAiMessageResponse>;
  /** 查询 AI 助手会话列表 */
  ListAiSession(request: ListAiSessionRequest): Promise<ListAiSessionResponse>;
  /** 创建 AI 助手会话 */
  CreateAiSession(request: CreateAiSessionRequest): Promise<CreateAiSessionResponse>;
  /** 从指定消息创建 AI 助手分支会话 */
  CreateAiSessionBranch(request: CreateAiSessionBranchRequest): Promise<CreateAiSessionBranchResponse>;
  /** 更新 AI 助手会话 */
  UpdateAiSession(request: UpdateAiSessionRequest): Promise<UpdateAiSessionResponse>;
  /** 删除 AI 助手会话 */
  DeleteAiSession(request: DeleteAiSessionRequest): Promise<DeleteAiSessionResponse>;
}
