// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/ai_tool.proto

/* eslint-disable */

/** 终端类型。 */
export enum Terminal {
  /** TERMINAL_UNSPECIFIED - 未指定终端类型。 */
  TERMINAL_UNSPECIFIED = 0,
  /** TERMINAL_APP - 移动端。 */
  TERMINAL_APP = 1,
  /** TERMINAL_ADMIN - 管理端。 */
  TERMINAL_ADMIN = 2,
}

/** AI 助手快捷入口列表查询条件 */
export interface ListAiShortcutRequest {
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手快捷入口列表响应 */
export interface ListAiShortcutResponse {
  /** 快捷入口列表 */
  shortcuts: AiShortcut[];
}

/** AI 助手快捷入口 */
export interface AiShortcut {
  /** 快捷入口标识 */
  key: string;
  /** 展示标题 */
  title: string;
  /** 发送给助手的提示词 */
  prompt: string;
  /** 快捷入口动作 */
  action:
    | AiShortcutAction
    | undefined;
  /** 依赖工具列表 */
  required_tools: string[];
  /** 排序值 */
  sort: number;
  /** 分组名称 */
  group: string;
}

/** AI 助手快捷入口动作 */
export interface AiShortcutAction {
  /** 流程标识 */
  flow: string;
  /** 流程步骤 */
  step: string;
  /** 动作类型 */
  type: string;
  /** 动作负载JSON */
  payload_json: string;
}

/** AI 助手工具调用记录 */
export interface AiToolCall {
  /** 工具类型：function/server */
  type: string;
  /** 工具名称 */
  name: string;
  /** 工具展示名称 */
  title: string;
  /** 工具调用状态 */
  status: string;
  /** 工具原始入参JSON */
  input: string;
  /** 工具原始出参JSON */
  output: string;
}

/** Base AI 助手工具服务 */
export interface AiToolService {
  /** 查询 AI 助手快捷入口列表 */
  ListAiShortcut(request: ListAiShortcutRequest): Promise<ListAiShortcutResponse>;
}
