// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/config.proto

/* eslint-disable */

/** 系统配置位置。 */
export enum BaseConfigSite {
  /** BASE_CONFIG_SITE_UNSPECIFIED - 未指定系统配置位置。 */
  BASE_CONFIG_SITE_UNSPECIFIED = 0,
  /** BASE_CONFIG_SITE_SYSTEM - 系统内使用。 */
  BASE_CONFIG_SITE_SYSTEM = 1,
  /** BASE_CONFIG_SITE_ADMIN - 管理端。 */
  BASE_CONFIG_SITE_ADMIN = 2,
  /** BASE_CONFIG_SITE_APP - 移动端。 */
  BASE_CONFIG_SITE_APP = 3,
}

/** 获取系统配置条件 */
export interface GetConfigRequest {
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
}

/** 系统配置项 */
export interface ConfigItem {
  /** 配置ID */
  id: number;
  /** 配置key */
  key: string;
  /** 配置value */
  value: string;
}

/** 系统配置查询结果 */
export interface GetConfigResponse {
  /** 系统配置列表 */
  configs: ConfigItem[];
}

/** Base系统配置公共服务 */
export interface ConfigService {
  /** 获取系统配置 */
  GetConfig(request: GetConfigRequest): Promise<GetConfigResponse>;
}
