// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/sse.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/** SSE订阅请求参数 */
export interface SubscribeSseRequest {
  /** SSE流标识 */
  stream: string;
  /** SSE通道ID */
  channel_id?: string | undefined;
}

/** Base SSE服务 */
export interface SseService {
  /** 订阅SSE事件流 */
  SubscribeSse(request: SubscribeSseRequest): Promise<Empty>;
}
