// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_language.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 语言选项查询条件 */
export interface OptionBaseLanguageRequest {
  /** 是否只返回启用语言 */
  enabled_only?: boolean | undefined;
}

/** 语言选项响应 */
export interface OptionBaseLanguageResponse {
  /** 语言选项 */
  base_languages: BaseLanguage[];
}

/** 语言分页查询条件 */
export interface PageBaseLanguageRequest {
  /** 语言名称 */
  language_name: string;
  /** 语言代码 */
  language_code: string;
  /** 启用状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 语言分页响应 */
export interface PageBaseLanguageResponse {
  /** 语言列表 */
  base_languages: BaseLanguage[];
  /** 总数 */
  total: number;
}

/** 语言详情查询条件 */
export interface GetBaseLanguageRequest {
  /** 语言ID */
  id: number;
}

/** 语言表单 */
export interface BaseLanguageForm {
  /** 语言ID */
  id: number;
  /** 标准语言代码 */
  language_code: string;
  /** 语言名称 */
  language_name: string;
  /** 本地语言名称 */
  native_name: string;
  /** 排序，值越小越靠前 */
  sort: number;
  /** 启用状态 */
  status: Status;
}

/** 语言 */
export interface BaseLanguage {
  /** 语言ID */
  id: number;
  /** 标准语言代码 */
  language_code: string;
  /** 语言名称 */
  language_name: string;
  /** 本地语言名称 */
  native_name: string;
  /** 排序 */
  sort: number;
  /** 是否主语言 */
  is_primary: boolean;
  /** 启用状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** 创建语言请求参数 */
export interface CreateBaseLanguageRequest {
  /** 语言表单 */
  base_language: BaseLanguageForm | undefined;
}

/** 更新语言请求参数 */
export interface UpdateBaseLanguageRequest {
  /** 语言表单 */
  base_language: BaseLanguageForm | undefined;
}

/** 删除语言请求参数 */
export interface DeleteBaseLanguageRequest {
  /** 语言ID列表 */
  id: string;
}

/** 设置语言状态请求参数 */
export interface SetBaseLanguageStatusRequest {
  /** 语言ID */
  id: number;
  /** 启用状态 */
  status: Status;
}

/** 设置主语言请求参数 */
export interface SetBaseLanguagePrimaryRequest {
  /** 语言ID */
  id: number;
}

/** Admin语言管理服务 */
export interface BaseLanguageService {
  /** 查询启用语言选项 */
  OptionBaseLanguage(request: OptionBaseLanguageRequest): Promise<OptionBaseLanguageResponse>;
  /** 查询语言分页列表 */
  PageBaseLanguage(request: PageBaseLanguageRequest): Promise<PageBaseLanguageResponse>;
  /** 查询语言详情 */
  GetBaseLanguage(request: GetBaseLanguageRequest): Promise<BaseLanguageForm>;
  /** 创建语言 */
  CreateBaseLanguage(request: CreateBaseLanguageRequest): Promise<Empty>;
  /** 更新语言 */
  UpdateBaseLanguage(request: UpdateBaseLanguageRequest): Promise<Empty>;
  /** 删除语言 */
  DeleteBaseLanguage(request: DeleteBaseLanguageRequest): Promise<Empty>;
  /** 设置语言状态 */
  SetBaseLanguageStatus(request: SetBaseLanguageStatusRequest): Promise<Empty>;
  /** 设置主语言 */
  SetBaseLanguagePrimary(request: SetBaseLanguagePrimaryRequest): Promise<Empty>;
}
