// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_redact_output_policy.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 出库脱敏策略处理模式。 */
export enum BaseRedactOutputPolicyMode {
  /** BASE_REDACT_OUTPUT_POLICY_MODE_UNSPECIFIED - 未指定模式。 */
  BASE_REDACT_OUTPUT_POLICY_MODE_UNSPECIFIED = 0,
  /** BASE_REDACT_OUTPUT_POLICY_MODE_RULE - 使用规则模板处理。 */
  BASE_REDACT_OUTPUT_POLICY_MODE_RULE = 1,
  /** BASE_REDACT_OUTPUT_POLICY_MODE_HIDE - 替换为字段零值。 */
  BASE_REDACT_OUTPUT_POLICY_MODE_HIDE = 2,
  /** BASE_REDACT_OUTPUT_POLICY_MODE_FULL - 保留字段原值。 */
  BASE_REDACT_OUTPUT_POLICY_MODE_FULL = 3,
}

/** 出库脱敏策略分页查询条件。 */
export interface PageBaseRedactOutputPolicyRequest {
  /** 接口操作 */
  operation: string;
  /** Proto消息完整名称 */
  message_ref: string;
  /** 返回字段路径 */
  field_path: string;
  /** 服务名 */
  service_name: string;
  /** 处理模式 */
  mode?:
    | BaseRedactOutputPolicyMode
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 出库脱敏策略分页响应。 */
export interface PageBaseRedactOutputPolicyResponse {
  /** 出库脱敏策略列表 */
  base_redact_output_policies: BaseRedactOutputPolicy[];
  /** 总数 */
  total: number;
}

/** 出库脱敏策略详情查询条件。 */
export interface GetBaseRedactOutputPolicyRequest {
  id: number;
}

/** 出库脱敏策略表单。 */
export interface BaseRedactOutputPolicyForm {
  /** 出库策略ID */
  id: number;
  /** 接口操作 */
  operation: string;
  /** Proto消息完整名称 */
  message_ref: string;
  /** 返回字段路径 */
  field_path: string;
  /** 服务名 */
  service_name: string;
  /** 处理模式 */
  mode: BaseRedactOutputPolicyMode;
  /** 规则ID */
  rule_id: number;
  /** 规则参数 */
  rule_params: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建出库脱敏策略请求参数。 */
export interface CreateBaseRedactOutputPolicyRequest {
  /** 出库脱敏策略列表 */
  base_redact_output_policy: BaseRedactOutputPolicyForm[];
}

/** 更新出库脱敏策略请求参数。 */
export interface UpdateBaseRedactOutputPolicyRequest {
  /** 出库脱敏策略列表 */
  base_redact_output_policy: BaseRedactOutputPolicyForm[];
}

/** 删除出库脱敏策略请求参数。 */
export interface DeleteBaseRedactOutputPolicyRequest {
  id: string;
}

/** 设置出库脱敏策略状态请求参数。 */
export interface SetBaseRedactOutputPolicyStatusRequest {
  /** 出库策略ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 出库脱敏策略。 */
export interface BaseRedactOutputPolicy {
  /** 出库策略ID */
  id: number;
  /** 接口操作 */
  operation: string;
  /** Proto消息完整名称 */
  message_ref: string;
  /** 返回字段路径 */
  field_path: string;
  /** 处理模式 */
  mode: BaseRedactOutputPolicyMode;
  /** 规则ID */
  rule_id: number;
  /** 规则编码 */
  rule_code: string;
  /** 规则名称 */
  rule_name: string;
  /** 规则类型 */
  rule_type: string;
  /** 规则参数 */
  rule_params: string;
  /** 服务名 */
  service_name: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin出库脱敏策略服务。 */
export interface BaseRedactOutputPolicyService {
  /** 查询出库脱敏策略分页列表。 */
  PageBaseRedactOutputPolicy(request: PageBaseRedactOutputPolicyRequest): Promise<PageBaseRedactOutputPolicyResponse>;
  /** 查询出库脱敏策略详情。 */
  GetBaseRedactOutputPolicy(request: GetBaseRedactOutputPolicyRequest): Promise<BaseRedactOutputPolicyForm>;
  /** 批量创建出库脱敏策略。 */
  CreateBaseRedactOutputPolicy(request: CreateBaseRedactOutputPolicyRequest): Promise<Empty>;
  /** 批量更新出库脱敏策略。 */
  UpdateBaseRedactOutputPolicy(request: UpdateBaseRedactOutputPolicyRequest): Promise<Empty>;
  /** 删除出库脱敏策略。 */
  DeleteBaseRedactOutputPolicy(request: DeleteBaseRedactOutputPolicyRequest): Promise<Empty>;
  /** 设置出库脱敏策略状态。 */
  SetBaseRedactOutputPolicyStatus(request: SetBaseRedactOutputPolicyStatusRequest): Promise<Empty>;
}
