// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_dict_item.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseI18n } from "./base_i18n";

/** 字典属性分页查询条件 */
export interface PageBaseDictItemRequest {
  /** 字典ID */
  dict_id: number;
  /** 字典属性名称 */
  label: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 字典属性分页响应 */
export interface PageBaseDictItemResponse {
  /** 分页数据 */
  base_dict_items: BaseDictItem[];
  /** 总数 */
  total: number;
}

/** 查询字典属性请求参数 */
export interface GetBaseDictItemRequest {
  /** 字典属性ID */
  id: number;
}

/** 字典属性表单 */
export interface BaseDictItemForm {
  /** 字典项ID */
  id: number;
  /** 字典ID */
  dict_id: number;
  /** 字典项值 */
  value: string;
  /** 字典项标签 */
  label: string;
  /** 标签类型，用于前端样式展示（如success、warning等） */
  tag_type: string;
  /** 排序 */
  sort: number;
  /** 非主语言翻译 */
  i18ns: BaseI18n[];
  /** 状态 */
  status: Status;
}

/** 创建字典属性请求参数 */
export interface CreateBaseDictItemRequest {
  /** 字典属性表单 */
  base_dict_item: BaseDictItemForm | undefined;
}

/** 更新字典属性请求参数 */
export interface UpdateBaseDictItemRequest {
  /** 字典属性表单 */
  base_dict_item: BaseDictItemForm | undefined;
}

/** 删除字典属性请求参数 */
export interface DeleteBaseDictItemRequest {
  /** 字典属性ID列表 */
  id: string;
}

/** 设置字典属性状态请求参数 */
export interface SetBaseDictItemStatusRequest {
  /** 字典属性ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 字典项 */
export interface BaseDictItem {
  /** 字典项ID */
  id: number;
  /** 字典ID */
  dict_id: number;
  /** 字典项值 */
  value: string;
  /** 字典项标签 */
  label: string;
  /** 标签类型，用于前端样式展示（如success、warning等） */
  tag_type: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 非主语言翻译 */
  i18ns: BaseI18n[];
}

/** Admin字典项服务 */
export interface BaseDictItemService {
  /** 查询字典属性分页列表 */
  PageBaseDictItem(request: PageBaseDictItemRequest): Promise<PageBaseDictItemResponse>;
  /** 查询字典属性 */
  GetBaseDictItem(request: GetBaseDictItemRequest): Promise<BaseDictItemForm>;
  /** 创建字典属性 */
  CreateBaseDictItem(request: CreateBaseDictItemRequest): Promise<Empty>;
  /** 更新字典属性 */
  UpdateBaseDictItem(request: UpdateBaseDictItemRequest): Promise<Empty>;
  /** 删除字典属性 */
  DeleteBaseDictItem(request: DeleteBaseDictItemRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseDictItemStatus(request: SetBaseDictItemStatusRequest): Promise<Empty>;
}
