// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_redact_storage_policy.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 入库脱敏策略分页查询条件。 */
export interface PageBaseRedactStoragePolicyRequest {
  /** 数据库表名 */
  table_name: string;
  /** 数据库字段名 */
  column_name: string;
  /** 规则ID */
  rule_id?:
    | number
    | undefined;
  /** 数据源名称 */
  source_name: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 入库脱敏策略分页响应。 */
export interface PageBaseRedactStoragePolicyResponse {
  /** 入库脱敏策略列表 */
  base_redact_storage_policies: BaseRedactStoragePolicy[];
  /** 总数 */
  total: number;
}

/** 入库脱敏策略详情查询条件。 */
export interface GetBaseRedactStoragePolicyRequest {
  id: number;
}

/** 入库脱敏策略表单。 */
export interface BaseRedactStoragePolicyForm {
  /** 入库策略ID */
  id: number;
  /** 数据库表名 */
  table_name: string;
  /** 数据库字段名 */
  column_name: string;
  /** 规则ID */
  rule_id: number;
  /** 规则参数 */
  rule_params: string;
  /** 数据源名称 */
  source_name: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建入库脱敏策略请求参数。 */
export interface CreateBaseRedactStoragePolicyRequest {
  /** 入库脱敏策略列表 */
  base_redact_storage_policy: BaseRedactStoragePolicyForm[];
}

/** 更新入库脱敏策略请求参数。 */
export interface UpdateBaseRedactStoragePolicyRequest {
  /** 入库脱敏策略列表 */
  base_redact_storage_policy: BaseRedactStoragePolicyForm[];
}

/** 删除入库脱敏策略请求参数。 */
export interface DeleteBaseRedactStoragePolicyRequest {
  id: string;
}

/** 设置入库脱敏策略状态请求参数。 */
export interface SetBaseRedactStoragePolicyStatusRequest {
  /** 入库策略ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 入库脱敏策略。 */
export interface BaseRedactStoragePolicy {
  /** 入库策略ID */
  id: number;
  /** 数据库表名 */
  table_name: string;
  /** 数据库字段名 */
  column_name: string;
  /** 规则ID */
  rule_id: number;
  /** 规则编码 */
  rule_code: string;
  /** 规则名称 */
  rule_name: string;
  /** 规则类型 */
  rule_type: string;
  /** 规则参数 */
  rule_params: string;
  /** 数据源名称 */
  source_name: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin入库脱敏策略服务。 */
export interface BaseRedactStoragePolicyService {
  /** 查询入库脱敏策略分页列表。 */
  PageBaseRedactStoragePolicy(
    request: PageBaseRedactStoragePolicyRequest,
  ): Promise<PageBaseRedactStoragePolicyResponse>;
  /** 查询入库脱敏策略详情。 */
  GetBaseRedactStoragePolicy(request: GetBaseRedactStoragePolicyRequest): Promise<BaseRedactStoragePolicyForm>;
  /** 批量创建入库脱敏策略。 */
  CreateBaseRedactStoragePolicy(request: CreateBaseRedactStoragePolicyRequest): Promise<Empty>;
  /** 批量更新入库脱敏策略。 */
  UpdateBaseRedactStoragePolicy(request: UpdateBaseRedactStoragePolicyRequest): Promise<Empty>;
  /** 删除入库脱敏策略。 */
  DeleteBaseRedactStoragePolicy(request: DeleteBaseRedactStoragePolicyRequest): Promise<Empty>;
  /** 设置入库脱敏策略状态。 */
  SetBaseRedactStoragePolicyStatus(request: SetBaseRedactStoragePolicyStatusRequest): Promise<Empty>;
}
