// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_api.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** API选项查询条件 */
export interface OptionBaseApiRequest {
  /** 是否包含免鉴权和可选鉴权接口 */
  include_public?: boolean | undefined;
}

/** API选项响应 */
export interface OptionBaseApiResponse {
  /** API列表 */
  base_apis: BaseApi[];
}

/** API分页查询条件 */
export interface PageBaseApiRequest {
  /** 工具名 */
  tool_name?:
    | string
    | undefined;
  /** Agent/MCP工具提示词搜索关键字 */
  tool_prompt?:
    | string
    | undefined;
  /** 服务名 */
  service_name?:
    | string
    | undefined;
  /** 服务描述 */
  service_desc?:
    | string
    | undefined;
  /** 描述 */
  desc?:
    | string
    | undefined;
  /** 操作方法 */
  operation?:
    | string
    | undefined;
  /** 请求方式 */
  method?:
    | string
    | undefined;
  /** 请求地址 */
  path?:
    | string
    | undefined;
  /** MCP工具状态：枚举【Status】 */
  mcp_status?:
    | Status
    | undefined;
  /** Agent工具状态：枚举【Status】 */
  agent_status?:
    | Status
    | undefined;
  /** OpenAPI文档key */
  openapi_service_code?:
    | string
    | undefined;
  /** 页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** API分页查询响应 */
export interface PageBaseApiResponse {
  /** API列表 */
  base_apis: BaseApi[];
  /** 总数 */
  total: number;
}

/** API详情查询条件 */
export interface GetBaseApiRequest {
  /** API ID */
  id: number;
}

/** API */
export interface BaseApi {
  /** API ID */
  id: number;
  /** 工具名 */
  tool_name: string;
  /** Agent/MCP工具提示词 */
  tool_prompts: string[];
  /** 服务名 */
  service_name: string;
  /** 服务描述 */
  service_desc: string;
  /** 描述 */
  desc: string;
  /** 操作方法 */
  operation: string;
  /** 请求方法 */
  method: string;
  /** 请求地址 */
  path: string;
  /** MCP工具状态：枚举【Status】 */
  mcp_status: Status;
  /** Agent工具状态：枚举【Status】 */
  agent_status: Status;
  /** OpenAPI文档key */
  openapi_service_code: string;
  /** OpenAPI文档名称 */
  openapi_service_name: string;
}

/** API文档查询条件 */
export interface GetBaseApiDocRequest {
  /** API ID */
  id: number;
}

/** API文档 */
export interface BaseApiDoc {
  /** API ID */
  id: number;
  /** 摘要 */
  summary: string;
  /** 描述 */
  description: string;
  /** 请求参数 */
  parameters: BaseApiDocSchema[];
  /** 请求体 */
  request_body:
    | BaseApiDocSchema
    | undefined;
  /** 返回值 */
  responses: BaseApiDocResponse[];
}

/** API更新条件 */
export interface UpdateBaseApiRequest {
  /** API ID */
  id: number;
  /** Agent/MCP工具提示词 */
  tool_prompts: string[];
  /** MCP工具状态：枚举【Status】 */
  mcp_status: Status;
  /** Agent工具状态：枚举【Status】 */
  agent_status: Status;
}

/** API Agent工具状态设置条件 */
export interface SetBaseApiAgentStatusRequest {
  /** API ID */
  id: number;
  /** Agent工具状态：枚举【Status】 */
  agent_status: Status;
}

/** API MCP工具状态设置条件 */
export interface SetBaseApiMcpStatusRequest {
  /** API ID */
  id: number;
  /** MCP工具状态：枚举【Status】 */
  mcp_status: Status;
}

/** API文档Schema */
export interface BaseApiDocSchema {
  /** 字段名 */
  name: string;
  /** 字段路径 */
  path: string;
  /** 参数位置 */
  in: string;
  /** 字段类型 */
  type: string;
  /** 字段格式 */
  format: string;
  /** 是否必填 */
  required: boolean;
  /** 字段描述 */
  description: string;
  /** 引用类型 */
  ref: string;
  /** 枚举值 */
  enum: string[];
  /** 子字段 */
  children: BaseApiDocSchema[];
}

/** API文档响应 */
export interface BaseApiDocResponse {
  /** 状态码 */
  status: string;
  /** 响应描述 */
  description: string;
  /** 响应体 */
  body: BaseApiDocSchema | undefined;
}

/** OpenAPI业务服务选项查询条件 */
export interface OptionOpenApiServiceRequest {
  /** OpenAPI文档key */
  service_code?: string | undefined;
}

/** OpenAPI业务服务选项响应 */
export interface OptionOpenApiServiceResponse {
  /** OpenAPI文档列表 */
  list: OpenApiServiceOption[];
}

/** OpenAPI业务服务选项 */
export interface OpenApiServiceOption {
  /** OpenAPI文档key */
  key: string;
  /** OpenAPI文档名称 */
  name: string;
  /** OpenAPI接口列表 */
  operations: OpenApiServiceOperation[];
}

/** OpenAPI业务服务接口 */
export interface OpenApiServiceOperation {
  /** HTTP请求路径 */
  path: string;
  /** HTTP请求方法 */
  method: string;
}

/** AdminAPI服务 */
export interface BaseApiService {
  /** 查询菜单分配API选项列表 */
  OptionBaseApi(request: OptionBaseApiRequest): Promise<OptionBaseApiResponse>;
  /** 分页查询API列表 */
  PageBaseApi(request: PageBaseApiRequest): Promise<PageBaseApiResponse>;
  /** 查询API详情 */
  GetBaseApi(request: GetBaseApiRequest): Promise<BaseApi>;
  /** 查询API文档 */
  GetBaseApiDoc(request: GetBaseApiDocRequest): Promise<BaseApiDoc>;
  /** 更新API配置 */
  UpdateBaseApi(request: UpdateBaseApiRequest): Promise<Empty>;
  /** 设置API Agent工具状态 */
  SetBaseApiAgentStatus(request: SetBaseApiAgentStatusRequest): Promise<Empty>;
  /** 设置API MCP工具状态 */
  SetBaseApiMcpStatus(request: SetBaseApiMcpStatusRequest): Promise<Empty>;
  /** 查询OpenAPI业务服务选项列表 */
  OptionOpenApiService(request: OptionOpenApiServiceRequest): Promise<OptionOpenApiServiceResponse>;
}
