// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_operation_log.proto

/* eslint-disable */
import type { BaseLogResult } from "./base_log";

/**
 * BaseOperationAction 定义管理端资源变更的业务动作。
 * 动作与资源类型组合后用于生成可检索的操作审计记录。
 */
export enum BaseOperationAction {
  /** BASE_OPERATION_ACTION_UNSPECIFIED - 未指定业务操作动作。 */
  BASE_OPERATION_ACTION_UNSPECIFIED = 0,
  /** BASE_OPERATION_ACTION_CREATE - 新增资源。 */
  BASE_OPERATION_ACTION_CREATE = 1,
  /** BASE_OPERATION_ACTION_UPDATE - 修改资源。 */
  BASE_OPERATION_ACTION_UPDATE = 2,
  /** BASE_OPERATION_ACTION_DELETE - 删除资源。 */
  BASE_OPERATION_ACTION_DELETE = 3,
  /** BASE_OPERATION_ACTION_PUBLISH - 发布资源。 */
  BASE_OPERATION_ACTION_PUBLISH = 4,
  /** BASE_OPERATION_ACTION_REVOKE - 撤回资源。 */
  BASE_OPERATION_ACTION_REVOKE = 5,
  /** BASE_OPERATION_ACTION_IMPORT - 导入数据。 */
  BASE_OPERATION_ACTION_IMPORT = 6,
  /** BASE_OPERATION_ACTION_EXPORT - 导出数据。 */
  BASE_OPERATION_ACTION_EXPORT = 7,
  /** BASE_OPERATION_ACTION_OTHER - 其他业务动作。 */
  BASE_OPERATION_ACTION_OTHER = 8,
}

/** 业务操作日志分页查询条件。 */
export interface PageBaseOperationLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 操作动作 */
  action?:
    | BaseOperationAction
    | undefined;
  /** 结果 */
  result?:
    | BaseLogResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 资源类型 */
  resource_type: string;
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 业务操作日志分页响应。 */
export interface PageBaseOperationLogResponse {
  /** 业务操作日志列表 */
  base_operation_logs: BaseOperationLog[];
  /** 总数 */
  total: number;
}

/** 查询业务操作日志详情请求。 */
export interface GetBaseOperationLogRequest {
  /** 操作日志ID */
  id: string;
}

/** 业务操作日志。 */
export interface BaseOperationLog {
  /** 操作日志ID */
  id: string;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 资源类型 */
  resource_type: string;
  /** 资源ID */
  resource_id: string;
  /** 资源名称 */
  resource_name: string;
  /** 操作动作 */
  action: BaseOperationAction;
  /** 变更字段 */
  changed_fields: string;
  /** 变更前数据 */
  before_data: string;
  /** 变更后数据 */
  after_data: string;
  /** 结果 */
  result: BaseLogResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志落库时间 */
  created_at: string;
}

/** Admin业务操作日志服务。 */
export interface BaseOperationLogService {
  /** 分页查询业务操作日志。 */
  PageBaseOperationLog(request: PageBaseOperationLogRequest): Promise<PageBaseOperationLogResponse>;
  /** 查询业务操作日志详情。 */
  GetBaseOperationLog(request: GetBaseOperationLogRequest): Promise<BaseOperationLog>;
}
