// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: system/admin/v1/base_application.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Empty } from "../../../google/protobuf/empty";

/** 应用信息下拉选择查询条件 */
export interface OptionBaseApplicationRequest {
}

/** 应用信息分页查询条件 */
export interface PageBaseApplicationRequest {
  /** 租户 */
  tenant_id?:
    | number
    | undefined;
  /** 应用名称 */
  name?:
    | string
    | undefined;
  /** 应用编码 */
  code?:
    | string
    | undefined;
  /** 状态 */
  status?:
    | number
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 应用信息分页响应 */
export interface PageBaseApplicationResponse {
  /** 应用信息列表 */
  base_applications: BaseApplication[];
  /** 总数 */
  total: number;
}

/** 应用信息 */
export interface BaseApplication {
  /** 应用ID */
  id: number;
  /** 租户 */
  tenant_id: number;
  /** 应用名称 */
  name: string;
  /** 应用编码 */
  code: string;
  /** 显示顺序 */
  sort: number;
  /** 应用备注 */
  remark: string;
  /** 状态 */
  status: number;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 应用链接地址 */
  url: string;
  /** 应用图标 */
  ico: string;
}

/** 应用信息详情查询条件 */
export interface GetBaseApplicationRequest {
  /** 应用信息ID */
  id: number;
}

/** 应用信息表单 */
export interface BaseApplicationForm {
  /** 应用ID */
  id: number;
  /** 租户 */
  tenant_id: number;
  /** 应用名称 */
  name: string;
  /** 应用编码 */
  code: string;
  /** 显示顺序 */
  sort: number;
  /** 应用备注 */
  remark?:
    | string
    | undefined;
  /** 状态 */
  status: number;
  /** 应用链接地址 */
  url?:
    | string
    | undefined;
  /** 应用图标 */
  ico?: string | undefined;
}

/** 应用信息创建条件 */
export interface CreateBaseApplicationRequest {
  /** 应用信息表单 */
  base_application: BaseApplicationForm | undefined;
}

/** 应用信息更新条件 */
export interface UpdateBaseApplicationRequest {
  /** 应用信息ID */
  id: number;
  /** 应用信息表单 */
  base_application: BaseApplicationForm | undefined;
}

/** 应用信息删除条件 */
export interface DeleteBaseApplicationRequest {
  /** 应用信息ID列表，多个用逗号分隔 */
  ids: string;
}

/** 应用信息状态设置条件 */
export interface SetBaseApplicationStatusRequest {
  /** 应用信息ID */
  id: number;
  /** 状态 */
  status: number;
}

/** Admin应用信息服务 */
export interface BaseApplicationService {
  /** 查询应用信息下拉选择 */
  OptionBaseApplication(request: OptionBaseApplicationRequest): Promise<SelectOptionResponse>;
  /** 查询应用信息分页列表 */
  PageBaseApplication(request: PageBaseApplicationRequest): Promise<PageBaseApplicationResponse>;
  /** 查询应用信息详情 */
  GetBaseApplication(request: GetBaseApplicationRequest): Promise<BaseApplicationForm>;
  /** 创建应用信息 */
  CreateBaseApplication(request: CreateBaseApplicationRequest): Promise<Empty>;
  /** 更新应用信息 */
  UpdateBaseApplication(request: UpdateBaseApplicationRequest): Promise<Empty>;
  /** 删除应用信息 */
  DeleteBaseApplication(request: DeleteBaseApplicationRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseApplicationStatus(request: SetBaseApplicationStatusRequest): Promise<Empty>;
}
