// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_table_archive.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** BaseTableArchiveMode 表示表归档目标模式。 */
export enum BaseTableArchiveMode {
  /** BASE_TABLE_ARCHIVE_MODE_UNSPECIFIED - 未指定归档目标模式。 */
  BASE_TABLE_ARCHIVE_MODE_UNSPECIFIED = 0,
  /** BASE_TABLE_ARCHIVE_MODE_INTERNAL_DATABASE - 保存到当前数据源的归档表。 */
  BASE_TABLE_ARCHIVE_MODE_INTERNAL_DATABASE = 1,
  /** BASE_TABLE_ARCHIVE_MODE_OSS - 保存到对象存储。 */
  BASE_TABLE_ARCHIVE_MODE_OSS = 2,
}

/** BaseTableArchiveForm 表归档配置表单。 */
export interface BaseTableArchiveForm {
  /** 归档配置ID */
  id: number;
  /** 数据表名称 */
  table_name: string;
  /** 归档模式 */
  archive_mode: BaseTableArchiveMode;
  /** 在线保留天数 */
  online_retention_days: number;
  /** 归档保留天数 */
  archive_retention_days: number;
  /** 批处理数量 */
  batch_size: number;
  /** 校验后删除在线数据 */
  delete_after_verify: boolean;
  /** OSS对象前缀 */
  oss_prefix: string;
  /** 数据源名称 */
  source_name: string;
  /** 状态 */
  status: Status;
}

/** PageBaseTableArchiveRequest 表归档配置分页请求。 */
export interface PageBaseTableArchiveRequest {
  /** 数据表名称 */
  table_name: string;
  /** 数据源名称 */
  source_name: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** PageBaseTableArchiveResponse 表归档配置分页响应。 */
export interface PageBaseTableArchiveResponse {
  /** 归档配置列表 */
  base_table_archives: BaseTableArchiveForm[];
  /** 总数 */
  total: number;
}

/** GetBaseTableArchiveRequest 查询表归档配置请求。 */
export interface GetBaseTableArchiveRequest {
  id: number;
}

/** CreateBaseTableArchiveRequest 创建表归档配置请求。 */
export interface CreateBaseTableArchiveRequest {
  base_table_archive: BaseTableArchiveForm | undefined;
}

/** UpdateBaseTableArchiveRequest 更新表归档配置请求。 */
export interface UpdateBaseTableArchiveRequest {
  base_table_archive: BaseTableArchiveForm | undefined;
}

/** DeleteBaseTableArchiveRequest 删除表归档配置请求。 */
export interface DeleteBaseTableArchiveRequest {
  id: string;
}

/** SetBaseTableArchiveStatusRequest 设置表归档配置状态请求。 */
export interface SetBaseTableArchiveStatusRequest {
  id: number;
  status: number;
}

/** Admin数据库表归档配置服务。 */
export interface BaseTableArchiveService {
  /** 查询表归档配置分页列表。 */
  PageBaseTableArchive(request: PageBaseTableArchiveRequest): Promise<PageBaseTableArchiveResponse>;
  /** 查询表归档配置。 */
  GetBaseTableArchive(request: GetBaseTableArchiveRequest): Promise<BaseTableArchiveForm>;
  /** 创建表归档配置。 */
  CreateBaseTableArchive(request: CreateBaseTableArchiveRequest): Promise<Empty>;
  /** 更新表归档配置。 */
  UpdateBaseTableArchive(request: UpdateBaseTableArchiveRequest): Promise<Empty>;
  /** 删除表归档配置。 */
  DeleteBaseTableArchive(request: DeleteBaseTableArchiveRequest): Promise<Empty>;
  /** 设置表归档配置状态。 */
  SetBaseTableArchiveStatus(request: SetBaseTableArchiveStatusRequest): Promise<Empty>;
}
