// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_migration.proto

/* eslint-disable */

/** 数据库迁移记录分页查询条件 */
export interface PageBaseMigrationRequest {
  /** 数据源 */
  data_source: string;
  /** 迁移模块 */
  module?:
    | string
    | undefined;
  /** 迁移版本 */
  version?:
    | string
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 数据库迁移记录列表项 */
export interface BaseMigrationListItem {
  /** 主键 */
  id: number;
  /** 迁移模块 */
  module: string;
  /** 数据源 */
  data_source: string;
  /** 迁移版本 */
  version: string;
  /** 创建时间 */
  created_at: string;
}

/** 数据库迁移记录分页响应 */
export interface PageBaseMigrationResponse {
  /** 迁移记录列表 */
  base_migrations: BaseMigrationListItem[];
  /** 总数 */
  total: number;
}

/** 查询数据库迁移记录详情请求参数 */
export interface GetBaseMigrationRequest {
  /** 主键 */
  id: number;
}

/** 数据库迁移记录详情 */
export interface BaseMigration {
  /** 主键 */
  id: number;
  /** 迁移模块 */
  module: string;
  /** 数据源 */
  data_source: string;
  /** 迁移版本 */
  version: string;
  /** 迁移文件列表 */
  files: BaseMigrationFile[];
  /** 创建时间 */
  created_at: string;
}

/** 数据库迁移文件内容 */
export interface BaseMigrationFile {
  /** 文件相对路径 */
  path: string;
  /** 文件内容 */
  content: string;
}

/** Admin数据库迁移服务。 */
export interface BaseMigrationService {
  /** 分页查询数据库升级历史 */
  PageBaseMigration(request: PageBaseMigrationRequest): Promise<PageBaseMigrationResponse>;
  /** 查询数据库迁移记录详情 */
  GetBaseMigration(request: GetBaseMigrationRequest): Promise<BaseMigration>;
}
