// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_i18n_custom.proto

/* eslint-disable */
import type { BaseConfigSite } from "../../../base/v1/config";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 国际化自定义翻译分页查询条件。 */
export interface PageBaseI18nCustomRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 位置：枚举【BaseConfigSite】 */
  site?:
    | BaseConfigSite
    | undefined;
  /** 国际化语言键 */
  key: string;
  /** 语言区域 */
  locale: string;
  /** 状态：枚举【Status】 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 国际化自定义翻译分页响应。 */
export interface PageBaseI18nCustomResponse {
  /** 国际化自定义翻译列表 */
  items: BaseI18nCustom[];
  /** 总数 */
  total: number;
}

/** 国际化自定义翻译详情查询条件。 */
export interface GetBaseI18nCustomRequest {
  /** 国际化自定义翻译ID */
  id: number;
}

/** 国际化自定义翻译表单。 */
export interface BaseI18nCustomForm {
  /** 国际化自定义翻译ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
  /** 国际化语言键 */
  key: string;
  /** 语言区域 */
  locale: string;
  /** 自定义翻译内容 */
  value: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建国际化自定义翻译请求。 */
export interface CreateBaseI18nCustomRequest {
  /** 国际化自定义翻译表单 */
  i18n_custom: BaseI18nCustomForm | undefined;
}

/** 更新国际化自定义翻译请求。 */
export interface UpdateBaseI18nCustomRequest {
  /** 国际化自定义翻译表单 */
  i18n_custom: BaseI18nCustomForm | undefined;
}

/** 删除国际化自定义翻译请求。 */
export interface DeleteBaseI18nCustomRequest {
  /** 国际化自定义翻译ID列表 */
  id: string;
}

/** 设置国际化自定义翻译状态请求。 */
export interface SetBaseI18nCustomStatusRequest {
  /** 国际化自定义翻译ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 国际化自定义翻译信息。 */
export interface BaseI18nCustom {
  /** 国际化自定义翻译ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
  /** 国际化语言键 */
  key: string;
  /** 语言区域 */
  locale: string;
  /** 自定义翻译内容 */
  value: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin国际化自定义翻译信息服务。 */
export interface BaseI18nCustomService {
  /** 查询国际化自定义翻译分页列表。 */
  PageBaseI18nCustom(request: PageBaseI18nCustomRequest): Promise<PageBaseI18nCustomResponse>;
  /** 查询国际化自定义翻译详情。 */
  GetBaseI18nCustom(request: GetBaseI18nCustomRequest): Promise<BaseI18nCustomForm>;
  /** 创建国际化自定义翻译。 */
  CreateBaseI18nCustom(request: CreateBaseI18nCustomRequest): Promise<Empty>;
  /** 更新国际化自定义翻译。 */
  UpdateBaseI18nCustom(request: UpdateBaseI18nCustomRequest): Promise<Empty>;
  /** 删除国际化自定义翻译。 */
  DeleteBaseI18nCustom(request: DeleteBaseI18nCustomRequest): Promise<Empty>;
  /** 设置国际化自定义翻译状态。 */
  SetBaseI18nCustomStatus(request: SetBaseI18nCustomStatusRequest): Promise<Empty>;
}
