// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_permission_log.proto

/* eslint-disable */
import type { BaseLogResult } from "./base_log";

/**
 * BasePermissionTargetType 定义权限变更所作用的安全对象类型。
 * 目标可为用户、角色、菜单、API 或租户，便于审计定位授权边界。
 */
export enum BasePermissionTargetType {
  /** BASE_PERMISSION_TARGET_TYPE_UNSPECIFIED - 未指定权限目标类型。 */
  BASE_PERMISSION_TARGET_TYPE_UNSPECIFIED = 0,
  /** BASE_PERMISSION_TARGET_TYPE_USER - 用户权限。 */
  BASE_PERMISSION_TARGET_TYPE_USER = 1,
  /** BASE_PERMISSION_TARGET_TYPE_ROLE - 角色权限。 */
  BASE_PERMISSION_TARGET_TYPE_ROLE = 2,
  /** BASE_PERMISSION_TARGET_TYPE_MENU - 菜单权限。 */
  BASE_PERMISSION_TARGET_TYPE_MENU = 3,
  /** BASE_PERMISSION_TARGET_TYPE_API - API 权限。 */
  BASE_PERMISSION_TARGET_TYPE_API = 4,
  /** BASE_PERMISSION_TARGET_TYPE_TENANT - 租户权限。 */
  BASE_PERMISSION_TARGET_TYPE_TENANT = 5,
}

/**
 * BasePermissionAction 定义安全对象及其授权关系的变更动作。
 * 授予、回收和对象增删改均应保留对应的审计上下文。
 */
export enum BasePermissionAction {
  /** BASE_PERMISSION_ACTION_UNSPECIFIED - 未指定权限动作。 */
  BASE_PERMISSION_ACTION_UNSPECIFIED = 0,
  /** BASE_PERMISSION_ACTION_GRANT - 授予权限。 */
  BASE_PERMISSION_ACTION_GRANT = 1,
  /** BASE_PERMISSION_ACTION_REVOKE - 回收权限。 */
  BASE_PERMISSION_ACTION_REVOKE = 2,
  /** BASE_PERMISSION_ACTION_CREATE - 新增权限对象。 */
  BASE_PERMISSION_ACTION_CREATE = 3,
  /** BASE_PERMISSION_ACTION_UPDATE - 修改权限对象。 */
  BASE_PERMISSION_ACTION_UPDATE = 4,
  /** BASE_PERMISSION_ACTION_DELETE - 删除权限对象。 */
  BASE_PERMISSION_ACTION_DELETE = 5,
  /** BASE_PERMISSION_ACTION_ASSIGN - 分配权限。 */
  BASE_PERMISSION_ACTION_ASSIGN = 6,
}

/** 权限日志分页查询条件。 */
export interface PageBasePermissionLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 目标类型 */
  target_type?:
    | BasePermissionTargetType
    | undefined;
  /** 权限动作 */
  action?:
    | BasePermissionAction
    | undefined;
  /** 结果 */
  result?:
    | BaseLogResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 权限日志分页响应。 */
export interface PageBasePermissionLogResponse {
  /** 权限日志列表 */
  base_permission_logs: BasePermissionLog[];
  /** 总数 */
  total: number;
}

/** 查询权限日志详情请求。 */
export interface GetBasePermissionLogRequest {
  /** 权限日志ID */
  id: string;
}

/** 权限日志。 */
export interface BasePermissionLog {
  /** 权限日志ID */
  id: string;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 目标类型 */
  target_type: BasePermissionTargetType;
  /** 目标ID */
  target_id: string;
  /** 目标名称 */
  target_name: string;
  /** 权限动作 */
  action: BasePermissionAction;
  /** 变更前权限 */
  old_value: string;
  /** 变更后权限 */
  new_value: string;
  /** 结果 */
  result: BaseLogResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志落库时间 */
  created_at: string;
}

/** Admin权限日志服务。 */
export interface BasePermissionLogService {
  /** 分页查询权限日志。 */
  PageBasePermissionLog(request: PageBasePermissionLogRequest): Promise<PageBasePermissionLogResponse>;
  /** 查询权限日志详情。 */
  GetBasePermissionLog(request: GetBasePermissionLogRequest): Promise<BasePermissionLog>;
}
