// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_role.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 角色数据范围。 */
export enum BaseRoleDataScope {
  /** BASE_ROLE_DATA_SCOPE_UNSPECIFIED - 未指定角色数据范围。 */
  BASE_ROLE_DATA_SCOPE_UNSPECIFIED = 0,
  /** BASE_ROLE_DATA_SCOPE_ALL - 全部数据。 */
  BASE_ROLE_DATA_SCOPE_ALL = 1,
  /** BASE_ROLE_DATA_SCOPE_DEPT_AND_CHILDREN - 部门及子部门数据。 */
  BASE_ROLE_DATA_SCOPE_DEPT_AND_CHILDREN = 2,
  /** BASE_ROLE_DATA_SCOPE_SELF_DEPT - 本部门数据。 */
  BASE_ROLE_DATA_SCOPE_SELF_DEPT = 3,
  /** BASE_ROLE_DATA_SCOPE_SELF_USER - 本人数据。 */
  BASE_ROLE_DATA_SCOPE_SELF_USER = 4,
}

/** 角色选项查询条件 */
export interface OptionBaseRoleRequest {
  /** 租户ID */
  tenant_id?: number | undefined;
}

/** 角色分页查询条件 */
export interface PageBaseRoleRequest {
  /** 角色名称 */
  name: string;
  /** 角色编号 */
  code: string;
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 角色分页响应 */
export interface PageBaseRoleResponse {
  /** 分页数据 */
  base_roles: BaseRole[];
  /** 总数 */
  total: number;
}

/** 查询角色请求参数 */
export interface GetBaseRoleRequest {
  /** 角色ID */
  id: number;
}

/** 角色表单 */
export interface BaseRoleForm {
  /** 角色ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 角色名称 */
  name: string;
  /** 角色编号 */
  code: string;
  /** 数据权限：0全部数据1部门及子部门数据2本部门数据3本人数据 */
  data_scope: BaseRoleDataScope;
  /** 分配的菜单列表 */
  menus: number[];
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建角色请求参数 */
export interface CreateBaseRoleRequest {
  /** 角色表单 */
  base_role: BaseRoleForm | undefined;
}

/** 更新角色请求参数 */
export interface UpdateBaseRoleRequest {
  /** 角色表单 */
  base_role: BaseRoleForm | undefined;
}

/** 删除角色请求参数 */
export interface DeleteBaseRoleRequest {
  /** 角色ID列表 */
  id: string;
}

/** 设置角色菜单权限请求参数 */
export interface SetBaseRoleMenuRequest {
  /** 角色ID */
  id: number;
  /** 分配的菜单列表 */
  menus: number[];
}

/** 设置角色状态请求参数 */
export interface SetBaseRoleStatusRequest {
  /** 角色ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 角色 */
export interface BaseRole {
  /** 角色ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 角色名称 */
  name: string;
  /** 角色编号 */
  code: string;
  /** 数据权限：0全部数据1部门及子部门数据2本部门数据3本人数据 */
  data_scope: BaseRoleDataScope;
  /** 分配的菜单列表 */
  menus: number[];
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 是否禁止通过角色管理操作 */
  is_protected: boolean;
}

/** Admin角色管理服务 */
export interface BaseRoleService {
  /** 查询角色下拉选择 */
  OptionBaseRole(request: OptionBaseRoleRequest): Promise<SelectOptionResponse>;
  /** 查询角色分页列表 */
  PageBaseRole(request: PageBaseRoleRequest): Promise<PageBaseRoleResponse>;
  /** 查询角色 */
  GetBaseRole(request: GetBaseRoleRequest): Promise<BaseRoleForm>;
  /** 创建角色 */
  CreateBaseRole(request: CreateBaseRoleRequest): Promise<Empty>;
  /** 更新角色 */
  UpdateBaseRole(request: UpdateBaseRoleRequest): Promise<Empty>;
  /** 删除角色 */
  DeleteBaseRole(request: DeleteBaseRoleRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseRoleStatus(request: SetBaseRoleStatusRequest): Promise<Empty>;
  /** 设置角色菜单权限 */
  SetBaseRoleMenu(request: SetBaseRoleMenuRequest): Promise<Empty>;
}
