// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_redact_rule.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 脱敏规则选项查询条件。 */
export interface OptionBaseRedactRuleRequest {
  keyword: string;
}

/** 脱敏规则分页查询条件。 */
export interface PageBaseRedactRuleRequest {
  /** 规则编码 */
  code: string;
  /** 规则名称 */
  name: string;
  /** 规则类型 */
  rule_type: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 脱敏规则分页响应。 */
export interface PageBaseRedactRuleResponse {
  /** 规则列表 */
  base_redact_rules: BaseRedactRule[];
  /** 总数 */
  total: number;
}

/** 脱敏规则详情查询条件。 */
export interface GetBaseRedactRuleRequest {
  id: number;
}

/** 脱敏规则表单。 */
export interface BaseRedactRuleForm {
  /** 规则ID */
  id: number;
  /** 规则编码 */
  code: string;
  /** 规则名称 */
  name: string;
  /** 规则类型 */
  rule_type: string;
  /** 规则参数 */
  rule: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建脱敏规则请求参数。 */
export interface CreateBaseRedactRuleRequest {
  base_redact_rule: BaseRedactRuleForm | undefined;
}

/** 更新脱敏规则请求参数。 */
export interface UpdateBaseRedactRuleRequest {
  base_redact_rule: BaseRedactRuleForm | undefined;
}

/** 删除脱敏规则请求参数。 */
export interface DeleteBaseRedactRuleRequest {
  id: string;
}

/** 设置脱敏规则状态请求参数。 */
export interface SetBaseRedactRuleStatusRequest {
  /** 规则ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 脱敏规则模板。 */
export interface BaseRedactRule {
  /** 规则ID */
  id: number;
  /** 规则编码 */
  code: string;
  /** 规则名称 */
  name: string;
  /** 规则类型 */
  rule_type: string;
  /** 规则参数 */
  rule: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin脱敏规则模板服务。 */
export interface BaseRedactRuleService {
  /** 查询脱敏规则选项。 */
  OptionBaseRedactRule(request: OptionBaseRedactRuleRequest): Promise<SelectOptionResponse>;
  /** 查询脱敏规则分页列表。 */
  PageBaseRedactRule(request: PageBaseRedactRuleRequest): Promise<PageBaseRedactRuleResponse>;
  /** 查询脱敏规则详情。 */
  GetBaseRedactRule(request: GetBaseRedactRuleRequest): Promise<BaseRedactRuleForm>;
  /** 创建脱敏规则。 */
  CreateBaseRedactRule(request: CreateBaseRedactRuleRequest): Promise<Empty>;
  /** 更新脱敏规则。 */
  UpdateBaseRedactRule(request: UpdateBaseRedactRuleRequest): Promise<Empty>;
  /** 删除脱敏规则。 */
  DeleteBaseRedactRule(request: DeleteBaseRedactRuleRequest): Promise<Empty>;
  /** 设置脱敏规则状态。 */
  SetBaseRedactRuleStatus(request: SetBaseRedactRuleStatusRequest): Promise<Empty>;
}
