// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_data_access_log.proto

/* eslint-disable */
import type { BaseLogResult } from "./base_log";

/**
 * BaseDataAccessType 定义读取、导入、导出和下载等数据访问方式。
 * 该枚举只描述访问事实，不代表访问是否经过授权。
 */
export enum BaseDataAccessType {
  /** BASE_DATA_ACCESS_TYPE_UNSPECIFIED - 未指定数据访问类型。 */
  BASE_DATA_ACCESS_TYPE_UNSPECIFIED = 0,
  /** BASE_DATA_ACCESS_TYPE_LIST - 列表访问。 */
  BASE_DATA_ACCESS_TYPE_LIST = 1,
  /** BASE_DATA_ACCESS_TYPE_DETAIL - 详情访问。 */
  BASE_DATA_ACCESS_TYPE_DETAIL = 2,
  /** BASE_DATA_ACCESS_TYPE_QUERY - 条件查询。 */
  BASE_DATA_ACCESS_TYPE_QUERY = 3,
  /** BASE_DATA_ACCESS_TYPE_EXPORT - 导出数据。 */
  BASE_DATA_ACCESS_TYPE_EXPORT = 4,
  /** BASE_DATA_ACCESS_TYPE_DOWNLOAD - 下载数据。 */
  BASE_DATA_ACCESS_TYPE_DOWNLOAD = 5,
  /** BASE_DATA_ACCESS_TYPE_IMPORT - 导入数据。 */
  BASE_DATA_ACCESS_TYPE_IMPORT = 6,
}

/** 数据访问日志分页查询条件。 */
export interface PageBaseDataAccessLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 访问类型 */
  access_type?:
    | BaseDataAccessType
    | undefined;
  /** 是否敏感数据 */
  sensitive?:
    | boolean
    | undefined;
  /** 结果 */
  result?:
    | BaseLogResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 资源类型 */
  resource_type: string;
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 数据访问日志分页响应。 */
export interface PageBaseDataAccessLogResponse {
  /** 数据访问日志列表 */
  base_data_access_logs: BaseDataAccessLog[];
  /** 总数 */
  total: number;
}

/** 查询数据访问日志详情请求。 */
export interface GetBaseDataAccessLogRequest {
  /** 数据访问日志ID */
  id: string;
}

/** 数据访问日志。 */
export interface BaseDataAccessLog {
  /** 数据访问日志ID */
  id: string;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 资源类型 */
  resource_type: string;
  /** 资源ID */
  resource_id: string;
  /** 访问类型 */
  access_type: BaseDataAccessType;
  /** 数据源 */
  data_source: string;
  /** 数据表名 */
  table_name: string;
  /** 访问字段范围 */
  field_scope: string;
  /** 数据范围 */
  data_scope: string;
  /** 影响行数 */
  affected_rows: number;
  /** 是否敏感数据 */
  sensitive: boolean;
  /** 脱敏SQL */
  sql_text: string;
  /** SQL指纹 */
  sql_digest: string;
  /** 结果 */
  result: BaseLogResult;
  /** 原因编码 */
  reason_code: string;
  /** 数据层耗时毫秒，未采集时为0 */
  latency_ms: number;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志落库时间 */
  created_at: string;
}

/** Admin数据访问日志服务。 */
export interface BaseDataAccessLogService {
  /** 分页查询数据访问日志。 */
  PageBaseDataAccessLog(request: PageBaseDataAccessLogRequest): Promise<PageBaseDataAccessLogResponse>;
  /** 查询数据访问日志详情。 */
  GetBaseDataAccessLog(request: GetBaseDataAccessLogRequest): Promise<BaseDataAccessLog>;
}
