// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_user.proto

/* eslint-disable */
import type { AnalyticsTimeType } from "../../../common/v1/analytics";
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { PasswordCrypto } from "../../../common/v1/types";
import type { Empty } from "../../../google/protobuf/empty";
import type { Timestamp } from "../../../google/protobuf/timestamp";
import type { BaseUserIDType, BaseUserPasswordChangeStatus } from "../../common/v1/common";

/** 用户性别。 */
export enum BaseUserGender {
  /** BASE_USER_GENDER_UNSPECIFIED - 未指定用户性别。 */
  BASE_USER_GENDER_UNSPECIFIED = 0,
  /** BASE_USER_GENDER_SECRET - 保密。 */
  BASE_USER_GENDER_SECRET = 1,
  /** BASE_USER_GENDER_MALE - 男。 */
  BASE_USER_GENDER_MALE = 2,
  /** BASE_USER_GENDER_FEMALE - 女。 */
  BASE_USER_GENDER_FEMALE = 3,
}

/** 用户选项查询条件 */
export interface OptionBaseUserRequest {
  /** 关键字 */
  keyword: string;
  /** 租户ID */
  tenant_id?: number | undefined;
}

/** 用户列表查询条件 */
export interface ListBaseUserRequest {
  /** 用户ID列表 */
  ids: number[];
}

/** 用户列表响应 */
export interface ListBaseUserResponse {
  /** 用户列表 */
  base_users: BaseUser[];
}

/** 用户分页查询条件 */
export interface PageBaseUserRequest {
  /** 用户编号 */
  user_code: string;
  /** 用户账号 */
  user_name: string;
  /** 用户昵称 */
  nick_name: string;
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 部门ID */
  dept_id?:
    | number
    | undefined;
  /** 手机号 */
  phone: string;
  /** 性别 */
  gender?:
    | BaseUserGender
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 用户分页响应 */
export interface PageBaseUserResponse {
  /** 分页数据 */
  base_users: BaseUser[];
  /** 总数 */
  total: number;
}

/** 查询用户请求参数 */
export interface GetBaseUserRequest {
  /** 用户ID */
  id: number;
}

/** 创建用户请求参数 */
export interface CreateBaseUserRequest {
  /** 用户表单 */
  base_user: BaseUserForm | undefined;
}

/** 更新用户请求参数 */
export interface UpdateBaseUserRequest {
  /** 用户表单 */
  base_user: BaseUserForm | undefined;
}

/** 删除用户请求参数 */
export interface DeleteBaseUserRequest {
  /** 用户ID列表 */
  id: string;
}

/** 设置用户状态请求参数 */
export interface SetBaseUserStatusRequest {
  /** 用户ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 用户 */
export interface BaseUser {
  /** 用户ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 用户账号 */
  user_name: string;
  /** 用户编号 */
  user_code: string;
  /** 用户昵称 */
  nick_name: string;
  /** 角色ID */
  role_id: number;
  /** 部门ID */
  dept_id: number;
  /** 岗位ID */
  post_id: number;
  /** 手机号 */
  phone: string;
  /** 邮箱 */
  email: string;
  /** 证件类型：枚举【BaseUserIDType】 */
  id_type: BaseUserIDType;
  /** 证件号 */
  id_code: string;
  /** 性别 */
  gender: BaseUserGender;
  /** 头像 */
  avatar: string;
  /** 用户状态 */
  status: Status;
  /** 备注名 */
  remark: string;
  /** 密码修改状态：枚举【BaseUserPasswordChangeStatus】 */
  must_change_password: BaseUserPasswordChangeStatus;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 是否禁止通过用户管理操作 */
  is_protected: boolean;
}

/** 用户表单 */
export interface BaseUserForm {
  /** 用户ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 用户账号 */
  user_name: string;
  /** 用户编号 */
  user_code: string;
  /** 用户昵称 */
  nick_name: string;
  /** 角色ID */
  role_id: number;
  /** 部门ID */
  dept_id: number;
  /** 岗位ID */
  post_id: number;
  /** 手机号 */
  phone: string;
  /** 邮箱 */
  email: string;
  /** 证件类型：枚举【BaseUserIDType】 */
  id_type: BaseUserIDType;
  /** 证件号 */
  id_code: string;
  /** 头像 */
  avatar: string;
  /** 性别 */
  gender: BaseUserGender;
  /** 密码 */
  pwd:
    | PasswordCrypto
    | undefined;
  /** 用户状态 */
  status: Status;
  /** 备注名 */
  remark: string;
}

/** 重置用户密码请求参数 */
export interface ResetBaseUserPasswordRequest {
  /** 用户ID */
  id: number;
  /** 密码 */
  pwd: PasswordCrypto | undefined;
}

/** 基础用户应用端角色设置参数 */
export interface SetBaseUserAppRoleRequest {
  /** 用户ID */
  user_id: number;
  /** 应用端角色编码 */
  role_code: string;
}

/** 用户注册汇总查询条件 */
export interface SummaryBaseUserRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 开始时间 */
  start_at:
    | Timestamp
    | undefined;
  /** 结束时间 */
  end_at:
    | Timestamp
    | undefined;
  /** 统计时间类型 */
  time_type: AnalyticsTimeType;
}

/** 用户注册汇总响应 */
export interface SummaryBaseUserResponse {
  /** 用户总数 */
  total: number;
  /** 用户注册时间维度汇总 */
  summaries: BaseUserSummaryItem[];
}

/** 用户注册时间维度汇总项 */
export interface BaseUserSummaryItem {
  /** 统计周期值：按周统计时1至7依次表示星期一至星期日，按月统计时表示日期1至31，按年统计时表示月份1至12 */
  key: number;
  /** 用户数 */
  count: number;
}

/** Admin用户管理服务 */
export interface BaseUserService {
  /** 查询用户下拉选择 */
  OptionBaseUser(request: OptionBaseUserRequest): Promise<SelectOptionResponse>;
  /** 查询用户列表 */
  ListBaseUser(request: ListBaseUserRequest): Promise<ListBaseUserResponse>;
  /** 查询用户分页列表 */
  PageBaseUser(request: PageBaseUserRequest): Promise<PageBaseUserResponse>;
  /** 查询用户 */
  GetBaseUser(request: GetBaseUserRequest): Promise<BaseUserForm>;
  /** 创建用户 */
  CreateBaseUser(request: CreateBaseUserRequest): Promise<Empty>;
  /** 更新用户 */
  UpdateBaseUser(request: UpdateBaseUserRequest): Promise<Empty>;
  /** 删除用户 */
  DeleteBaseUser(request: DeleteBaseUserRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseUserStatus(request: SetBaseUserStatusRequest): Promise<Empty>;
  /** 重置密码 */
  ResetBaseUserPassword(request: ResetBaseUserPasswordRequest): Promise<Empty>;
  /** 设置基础用户应用端角色 */
  SetBaseUserAppRole(request: SetBaseUserAppRoleRequest): Promise<Empty>;
  /** 汇总用户注册数据 */
  SummaryBaseUser(request: SummaryBaseUserRequest): Promise<SummaryBaseUserResponse>;
}
