// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_tenant_project.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 项目选项查询条件 */
export interface OptionBaseTenantProjectRequest {
  /** 租户ID */
  tenant_id?: number | undefined;
}

/** 项目树查询条件 */
export interface TreeBaseTenantProjectRequest {
  /** 项目编号或名称关键字 */
  keyword: string;
}

/** 项目树响应 */
export interface TreeBaseTenantProjectResponse {
  /** 租户项目树 */
  list: TreeBaseTenantProjectResponse_Option[];
}

/** 项目树节点 */
export interface TreeBaseTenantProjectResponse_Option {
  /** 节点值 */
  value: string;
  /** 节点名称 */
  label: string;
  /** 节点类型 */
  type: string;
  /** 租户ID */
  tenant_id: number;
  /** 项目ID */
  project_id: number;
  /** 是否禁用 */
  disabled: boolean;
  /** 子节点 */
  children: TreeBaseTenantProjectResponse_Option[];
}

/** 项目分页查询条件 */
export interface PageBaseTenantProjectRequest {
  /** 项目名称 */
  name: string;
  /** 项目编号 */
  code: string;
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 项目分页响应 */
export interface PageBaseTenantProjectResponse {
  /** 分页数据 */
  base_tenant_projects: BaseTenantProject[];
  /** 总数 */
  total: number;
}

/** 查询项目请求参数 */
export interface GetBaseTenantProjectRequest {
  /** 项目ID */
  id: number;
}

/** 项目表单 */
export interface BaseTenantProjectForm {
  /** 项目ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 项目编号 */
  code: string;
  /** 项目名称 */
  name: string;
  /** 状态 */
  status: Status;
  /** 显示顺序 */
  sort: number;
  /** 备注 */
  remark: string;
}

/** 创建项目请求参数 */
export interface CreateBaseTenantProjectRequest {
  /** 项目表单 */
  base_tenant_project: BaseTenantProjectForm | undefined;
}

/** 更新项目请求参数 */
export interface UpdateBaseTenantProjectRequest {
  /** 项目表单 */
  base_tenant_project: BaseTenantProjectForm | undefined;
}

/** 删除项目请求参数 */
export interface DeleteBaseTenantProjectRequest {
  /** 项目ID列表 */
  id: string;
}

/** 设置项目状态请求参数 */
export interface SetBaseTenantProjectStatusRequest {
  /** 项目ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 项目 */
export interface BaseTenantProject {
  /** 项目ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 项目编号 */
  code: string;
  /** 项目名称 */
  name: string;
  /** 状态 */
  status: Status;
  /** 显示顺序 */
  sort: number;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin项目管理服务 */
export interface BaseTenantProjectService {
  /** 查询项目下拉选择 */
  OptionBaseTenantProject(request: OptionBaseTenantProjectRequest): Promise<SelectOptionResponse>;
  /** 查询当前账号可用的租户项目树 */
  TreeBaseTenantProject(request: TreeBaseTenantProjectRequest): Promise<TreeBaseTenantProjectResponse>;
  /** 查询项目分页列表 */
  PageBaseTenantProject(request: PageBaseTenantProjectRequest): Promise<PageBaseTenantProjectResponse>;
  /** 查询项目 */
  GetBaseTenantProject(request: GetBaseTenantProjectRequest): Promise<BaseTenantProjectForm>;
  /** 创建项目 */
  CreateBaseTenantProject(request: CreateBaseTenantProjectRequest): Promise<Empty>;
  /** 更新项目 */
  UpdateBaseTenantProject(request: UpdateBaseTenantProjectRequest): Promise<Empty>;
  /** 删除项目 */
  DeleteBaseTenantProject(request: DeleteBaseTenantProjectRequest): Promise<Empty>;
  /** 设置项目状态 */
  SetBaseTenantProjectStatus(request: SetBaseTenantProjectStatusRequest): Promise<Empty>;
}
