// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_dashboard.proto

/* eslint-disable */

/** 首页概览统计查询条件。 */
export interface GetBaseDashboardOverviewRequest {
}

/** 操作动作分布查询条件。 */
export interface GetBaseDashboardOperationDistributionRequest {
}

/** 登录结果分布查询条件。 */
export interface GetBaseDashboardLoginDistributionRequest {
}

/** 首页概览统计。 */
export interface BaseDashboardOverview {
  /** 用户总数 */
  user_count: number;
  /** 角色总数 */
  role_count: number;
  /** 今日登录次数 */
  today_login_count: number;
  /** 今日操作次数 */
  today_operation_count: number;
}

/** 登录趋势查询条件。 */
export interface GetBaseDashboardLoginTrendRequest {
  /** 统计天数，默认7天 */
  days: number;
}

/** 趋势统计响应。 */
export interface BaseDashboardTrendResponse {
  /** 趋势数据点 */
  points: BaseDashboardTrendPoint[];
}

/** 趋势数据点。 */
export interface BaseDashboardTrendPoint {
  /** 日期，格式为YYYY-MM-DD */
  date: string;
  /** 数量 */
  count: number;
}

/** 分布统计响应。 */
export interface BaseDashboardDistributionResponse {
  /** 分布数据 */
  items: BaseDashboardDistributionItem[];
}

/** 分布统计数据项。 */
export interface BaseDashboardDistributionItem {
  /** 分布标签 */
  label: string;
  /** 数量 */
  count: number;
}

/** Admin首页业务统计服务。 */
export interface BaseDashboardService {
  /** 查询首页概览统计。 */
  GetBaseDashboardOverview(request: GetBaseDashboardOverviewRequest): Promise<BaseDashboardOverview>;
  /** 查询登录趋势。 */
  GetBaseDashboardLoginTrend(request: GetBaseDashboardLoginTrendRequest): Promise<BaseDashboardTrendResponse>;
  /** 查询操作动作分布。 */
  GetBaseDashboardOperationDistribution(
    request: GetBaseDashboardOperationDistributionRequest,
  ): Promise<BaseDashboardDistributionResponse>;
  /** 查询登录结果分布。 */
  GetBaseDashboardLoginDistribution(
    request: GetBaseDashboardLoginDistributionRequest,
  ): Promise<BaseDashboardDistributionResponse>;
}
