// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_session.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** 查询本人全部会话请求。 */
export interface ListCurrentBaseSessionsRequest {
}

/** 本人有效会话列表。 */
export interface ListCurrentBaseSessionsResponse {
  /** 本人有效会话列表 */
  sessions: BaseSession[];
}

/** 查询当前会话请求参数。 */
export interface GetCurrentBaseSessionRequest {
}

/** 撤销全部会话请求参数。 */
export interface RevokeAllBaseSessionsRequest {
}

/** 在线会话分页查询请求。 */
export interface PageOnlineBaseSessionsRequest {
  /** 关键字 */
  keyword: string;
  /** 租户编码 */
  tenant_code: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 在线会话分页响应。 */
export interface PageOnlineBaseSessionsResponse {
  /** 在线会话列表 */
  sessions: BaseSession[];
  /** 总数 */
  total: number;
}

/** 下线指定会话请求。 */
export interface RevokeBaseSessionRequest {
  /** 会话ID */
  session_id: string;
}

/** 当前会话信息。 */
export interface BaseSession {
  /** 会话ID */
  session_id: string;
  /** 用户ID */
  user_id: number;
  /** 用户账号 */
  user_name: string;
  /** 租户编码 */
  tenant_code: string;
  /** 客户端IP */
  client_ip: string;
  /** 登录设备 */
  device: string;
  /** 用户代理 */
  user_agent: string;
  /** 签发时间 */
  issued_at: string;
  /** 令牌有效期（秒） */
  expires_in: number;
  /** 是否为当前请求会话 */
  current: boolean;
}

/** Admin会话管理服务。 */
export interface BaseSessionService {
  /** 查询当前用户全部有效会话。 */
  ListCurrentBaseSessions(request: ListCurrentBaseSessionsRequest): Promise<ListCurrentBaseSessionsResponse>;
  /** 查询当前用户会话。 */
  GetCurrentBaseSession(request: GetCurrentBaseSessionRequest): Promise<BaseSession>;
  /** 撤销当前用户全部会话。 */
  RevokeAllBaseSessions(request: RevokeAllBaseSessionsRequest): Promise<Empty>;
  /** 分页查询当前在线用户会话。 */
  PageOnlineBaseSessions(request: PageOnlineBaseSessionsRequest): Promise<PageOnlineBaseSessionsResponse>;
  /** 下线指定用户会话。 */
  RevokeBaseSession(request: RevokeBaseSessionRequest): Promise<Empty>;
}
