// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_table_backup_restore.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** BaseTableBackupRestoreMode 表示备份恢复模式。 */
export enum BaseTableBackupRestoreMode {
  /** BASE_TABLE_BACKUP_RESTORE_MODE_UNSPECIFIED - 未指定备份恢复模式。 */
  BASE_TABLE_BACKUP_RESTORE_MODE_UNSPECIFIED = 0,
  /** BASE_TABLE_BACKUP_RESTORE_MODE_VERIFY_ONLY - 只校验备份，不写入数据库。 */
  BASE_TABLE_BACKUP_RESTORE_MODE_VERIFY_ONLY = 1,
  /** BASE_TABLE_BACKUP_RESTORE_MODE_FULL - 完整恢复数据库。 */
  BASE_TABLE_BACKUP_RESTORE_MODE_FULL = 2,
}

/** BaseTableBackupRestoreStatus 表示备份恢复状态。 */
export enum BaseTableBackupRestoreStatus {
  /** BASE_TABLE_BACKUP_RESTORE_STATUS_UNSPECIFIED - 未指定备份恢复状态。 */
  BASE_TABLE_BACKUP_RESTORE_STATUS_UNSPECIFIED = 0,
  /** BASE_TABLE_BACKUP_RESTORE_STATUS_PENDING - 等待人工确认。 */
  BASE_TABLE_BACKUP_RESTORE_STATUS_PENDING = 1,
  /** BASE_TABLE_BACKUP_RESTORE_STATUS_RUNNING - 执行中。 */
  BASE_TABLE_BACKUP_RESTORE_STATUS_RUNNING = 2,
  /** BASE_TABLE_BACKUP_RESTORE_STATUS_SUCCESS - 执行成功。 */
  BASE_TABLE_BACKUP_RESTORE_STATUS_SUCCESS = 3,
  /** BASE_TABLE_BACKUP_RESTORE_STATUS_FAILED - 执行失败。 */
  BASE_TABLE_BACKUP_RESTORE_STATUS_FAILED = 4,
}

/** BaseTableBackupRestore 数据库备份恢复记录。 */
export interface BaseTableBackupRestore {
  /** 恢复记录ID */
  id: number;
  /** 备份记录ID */
  backup_record_id: number;
  /** 源数据源 */
  source_name: string;
  /** 目标数据源 */
  target_source_name: string;
  /** 目标数据库 */
  target_database: string;
  /** 恢复模式 */
  restore_mode: BaseTableBackupRestoreMode;
  /** 操作人ID */
  operator_id: number;
  /** 恢复状态 */
  status: BaseTableBackupRestoreStatus;
  /** 错误信息 */
  error: string;
  /** 开始时间 */
  started_at: string;
  /** 完成时间 */
  finished_at: string;
}

/** PageBaseTableBackupRestoreRequest 数据库备份恢复记录分页请求。 */
export interface PageBaseTableBackupRestoreRequest {
  status?: BaseTableBackupRestoreStatus | undefined;
  page_num: number;
  page_size: number;
}

/** PageBaseTableBackupRestoreResponse 数据库备份恢复记录分页响应。 */
export interface PageBaseTableBackupRestoreResponse {
  base_table_backup_restores: BaseTableBackupRestore[];
  total: number;
}

/** GetBaseTableBackupRestoreRequest 查询数据库备份恢复记录请求。 */
export interface GetBaseTableBackupRestoreRequest {
  id: number;
}

/** ExecuteBaseTableBackupRestoreRequest 执行数据库备份恢复请求。 */
export interface ExecuteBaseTableBackupRestoreRequest {
  base_table_backup_restore: BaseTableBackupRestore | undefined;
}

/** Admin数据库备份恢复服务。 */
export interface BaseTableBackupRestoreService {
  /** 查询备份恢复记录分页列表。 */
  PageBaseTableBackupRestore(request: PageBaseTableBackupRestoreRequest): Promise<PageBaseTableBackupRestoreResponse>;
  /** 查询备份恢复记录。 */
  GetBaseTableBackupRestore(request: GetBaseTableBackupRestoreRequest): Promise<BaseTableBackupRestore>;
  /** 手工执行数据库备份恢复。 */
  ExecuteBaseTableBackupRestore(request: ExecuteBaseTableBackupRestoreRequest): Promise<Empty>;
}
