// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_message_category.proto

/* eslint-disable */
import type { MessagePriority } from "../../../base/v1/notification";
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 消息分类选项查询条件。 */
export interface OptionBaseMessageCategoryRequest {
}

/** 消息分类分页查询条件。 */
export interface PageBaseMessageCategoryRequest {
  /** 分类名称 */
  name?:
    | string
    | undefined;
  /** 分类编码 */
  code?:
    | string
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 消息分类分页响应。 */
export interface PageBaseMessageCategoryResponse {
  /** 消息分类列表 */
  base_message_categories: BaseMessageCategory[];
  /** 总数 */
  total: number;
}

/** 消息分类详情查询条件。 */
export interface GetBaseMessageCategoryRequest {
  /** 消息分类ID */
  id: number;
}

/** 创建消息分类请求。 */
export interface CreateBaseMessageCategoryRequest {
  /** 消息分类表单 */
  base_message_category: BaseMessageCategoryForm | undefined;
}

/** 更新消息分类请求。 */
export interface UpdateBaseMessageCategoryRequest {
  /** 消息分类表单 */
  base_message_category: BaseMessageCategoryForm | undefined;
}

/** 删除消息分类请求。 */
export interface DeleteBaseMessageCategoryRequest {
  /** 消息分类ID列表 */
  id: string;
}

/** 设置消息分类状态请求。 */
export interface SetBaseMessageCategoryStatusRequest {
  /** 消息分类ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 消息分类表单。 */
export interface BaseMessageCategoryForm {
  /** 消息分类ID */
  id: number;
  /** 分类编码 */
  code: string;
  /** 分类名称 */
  name: string;
  /** 分类图标 */
  icon: string;
  /** 分类颜色 */
  color: string;
  /** 排序 */
  sort: number;
  /** 默认优先级 */
  default_priority: MessagePriority;
  /** 保留天数 */
  retention_days: number;
  /** 是否允许归档 */
  allow_archive: boolean;
  /** 是否允许删除 */
  allow_delete: boolean;
  /** 状态 */
  status: Status;
}

/** 消息分类。 */
export interface BaseMessageCategory {
  /** 消息分类ID */
  id: number;
  /** 分类编码 */
  code: string;
  /** 分类名称 */
  name: string;
  /** 分类图标 */
  icon: string;
  /** 分类颜色 */
  color: string;
  /** 排序 */
  sort: number;
  /** 默认优先级 */
  default_priority: MessagePriority;
  /** 保留天数 */
  retention_days: number;
  /** 是否允许归档 */
  allow_archive: boolean;
  /** 是否允许删除 */
  allow_delete: boolean;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin消息分类管理服务。 */
export interface BaseMessageCategoryService {
  /** 查询消息分类选项。 */
  OptionBaseMessageCategory(request: OptionBaseMessageCategoryRequest): Promise<SelectOptionResponse>;
  /** 分页查询消息分类。 */
  PageBaseMessageCategory(request: PageBaseMessageCategoryRequest): Promise<PageBaseMessageCategoryResponse>;
  /** 查询消息分类详情。 */
  GetBaseMessageCategory(request: GetBaseMessageCategoryRequest): Promise<BaseMessageCategoryForm>;
  /** 创建消息分类。 */
  CreateBaseMessageCategory(request: CreateBaseMessageCategoryRequest): Promise<Empty>;
  /** 更新消息分类。 */
  UpdateBaseMessageCategory(request: UpdateBaseMessageCategoryRequest): Promise<Empty>;
  /** 删除消息分类。 */
  DeleteBaseMessageCategory(request: DeleteBaseMessageCategoryRequest): Promise<Empty>;
  /** 设置消息分类状态。 */
  SetBaseMessageCategoryStatus(request: SetBaseMessageCategoryStatusRequest): Promise<Empty>;
}
