// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_log.proto

/* eslint-disable */

/**
 * BaseLogResult 定义日志事件的最终处理结果。
 * SUCCESS 表示业务完成，FAILURE 表示可预期拒绝，ERROR 表示系统异常。
 */
export enum BaseLogResult {
  /** BASE_LOG_RESULT_UNSPECIFIED - 未指定审计结果。 */
  BASE_LOG_RESULT_UNSPECIFIED = 0,
  /** BASE_LOG_RESULT_SUCCESS - 操作成功。 */
  BASE_LOG_RESULT_SUCCESS = 1,
  /** BASE_LOG_RESULT_FAILURE - 操作失败。 */
  BASE_LOG_RESULT_FAILURE = 2,
  /** BASE_LOG_RESULT_ERROR - 执行异常。 */
  BASE_LOG_RESULT_ERROR = 3,
}

/** BaseLogType 定义关联日志时间线中的日志类型。 */
export enum BaseLogType {
  /** BASE_LOG_TYPE_UNSPECIFIED - 未指定日志类型。 */
  BASE_LOG_TYPE_UNSPECIFIED = 0,
  /** BASE_LOG_TYPE_LOGIN - 登录日志。 */
  BASE_LOG_TYPE_LOGIN = 1,
  /** BASE_LOG_TYPE_API - API 访问日志。 */
  BASE_LOG_TYPE_API = 2,
  /** BASE_LOG_TYPE_OPERATION - 业务操作日志。 */
  BASE_LOG_TYPE_OPERATION = 3,
  /** BASE_LOG_TYPE_DATA_ACCESS - 数据访问日志。 */
  BASE_LOG_TYPE_DATA_ACCESS = 4,
  /** BASE_LOG_TYPE_PERMISSION - 权限日志。 */
  BASE_LOG_TYPE_PERMISSION = 5,
  /** BASE_LOG_TYPE_POLICY_EVALUATION - 策略评估日志。 */
  BASE_LOG_TYPE_POLICY_EVALUATION = 6,
}

/** 关联审计查询条件。 */
export interface GetBaseLogTraceRequest {
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
}

/** 关联审计查询响应。 */
export interface GetBaseLogTraceResponse {
  /** 关联日志时间线 */
  items: BaseLogTraceItem[];
}

/** 关联审计时间线项目。 */
export interface BaseLogTraceItem {
  /** 日志类型 */
  log_type: BaseLogType;
  /** 日志ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 资源或接口 */
  resource: string;
  /** 结果 */
  result: BaseLogResult;
  /** 原因说明 */
  reason: string;
  /** 本层耗时毫秒 */
  duration_ms: number;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志落库时间 */
  created_at: string;
}

/** Admin公共日志聚合查询服务。 */
export interface BaseLogService {
  /** 查询同一请求或链路关联的六类审计记录。 */
  GetBaseLogTrace(request: GetBaseLogTraceRequest): Promise<GetBaseLogTraceResponse>;
}
