// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_area.proto

/* eslint-disable */
import type { TreeOptionResponse } from "../../../common/v1/common";
import type { Empty } from "../../../google/protobuf/empty";

/** 行政区域树形选择查询条件 */
export interface OptionBaseAreaRequest {
  /** 父节点ID */
  parent_id?:
    | number
    | undefined;
  /** 是否懒加载 */
  lazy?: boolean | undefined;
}

/** 行政区域树形列表查询条件 */
export interface TreeBaseAreaRequest {
  /** 区域名称 */
  name?:
    | string
    | undefined;
  /** 父级区域ID */
  parent_id?:
    | number
    | undefined;
  /** 是否懒加载 */
  lazy?: boolean | undefined;
}

/** 行政区域树形列表响应 */
export interface TreeBaseAreaResponse {
  /** 行政区域树形列表 */
  base_areas: BaseArea[];
}

/** 行政区域 */
export interface BaseArea {
  /** 区域ID */
  id: number;
  /** 父级区域 */
  parent_id: number;
  /** 区域名称 */
  name: string;
  /** 是否存在子节点 */
  has_children: boolean;
  /** 子区域 */
  children: BaseArea[];
}

/** 行政区域详情查询条件 */
export interface GetBaseAreaRequest {
  /** 行政区域ID */
  id: number;
}

/** 行政区域表单 */
export interface BaseAreaForm {
  /** 区域ID */
  id: number;
  /** 父级区域 */
  parent_id: number;
  /** 区域名称 */
  name: string;
}

/** 行政区域创建条件 */
export interface CreateBaseAreaRequest {
  /** 行政区域表单 */
  base_area: BaseAreaForm | undefined;
}

/** 行政区域更新条件 */
export interface UpdateBaseAreaRequest {
  /** 行政区域ID */
  id: number;
  /** 行政区域表单 */
  base_area: BaseAreaForm | undefined;
}

/** 行政区域删除条件 */
export interface DeleteBaseAreaRequest {
  /** 行政区域ID列表，多个用逗号分隔 */
  ids: string;
}

/** Admin行政区域服务 */
export interface BaseAreaService {
  /** 查询行政区域树形选择 */
  OptionBaseArea(request: OptionBaseAreaRequest): Promise<TreeOptionResponse>;
  /** 查询行政区域树形列表 */
  TreeBaseArea(request: TreeBaseAreaRequest): Promise<TreeBaseAreaResponse>;
  /** 查询行政区域详情 */
  GetBaseArea(request: GetBaseAreaRequest): Promise<BaseAreaForm>;
  /** 创建行政区域 */
  CreateBaseArea(request: CreateBaseAreaRequest): Promise<Empty>;
  /** 更新行政区域 */
  UpdateBaseArea(request: UpdateBaseAreaRequest): Promise<Empty>;
  /** 删除行政区域 */
  DeleteBaseArea(request: DeleteBaseAreaRequest): Promise<Empty>;
}
