// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_table_archive_record.proto

/* eslint-disable */
import type { BaseTableArchiveMode } from "./base_table_archive";

/** BaseTableArchiveRecordStatus 表示归档记录执行状态。 */
export enum BaseTableArchiveRecordStatus {
  /** BASE_TABLE_ARCHIVE_RECORD_STATUS_UNSPECIFIED - 未指定归档记录状态。 */
  BASE_TABLE_ARCHIVE_RECORD_STATUS_UNSPECIFIED = 0,
  /** BASE_TABLE_ARCHIVE_RECORD_STATUS_PENDING - 等待执行。 */
  BASE_TABLE_ARCHIVE_RECORD_STATUS_PENDING = 1,
  /** BASE_TABLE_ARCHIVE_RECORD_STATUS_RUNNING - 执行中。 */
  BASE_TABLE_ARCHIVE_RECORD_STATUS_RUNNING = 2,
  /** BASE_TABLE_ARCHIVE_RECORD_STATUS_VERIFYING - 校验中。 */
  BASE_TABLE_ARCHIVE_RECORD_STATUS_VERIFYING = 3,
  /** BASE_TABLE_ARCHIVE_RECORD_STATUS_SUCCESS - 执行成功。 */
  BASE_TABLE_ARCHIVE_RECORD_STATUS_SUCCESS = 4,
  /** BASE_TABLE_ARCHIVE_RECORD_STATUS_FAILED - 执行失败。 */
  BASE_TABLE_ARCHIVE_RECORD_STATUS_FAILED = 5,
  /** BASE_TABLE_ARCHIVE_RECORD_STATUS_DELETED - 归档对象已过期清理。 */
  BASE_TABLE_ARCHIVE_RECORD_STATUS_DELETED = 6,
}

/** BaseTableArchiveRecord 表归档执行记录。 */
export interface BaseTableArchiveRecord {
  /** 归档记录ID */
  id: number;
  /** 归档配置ID */
  archive_id: number;
  /** 数据表名称 */
  table_name: string;
  /** 归档模式 */
  archive_mode: BaseTableArchiveMode;
  /** 归档截止时间 */
  cutoff_at: string;
  /** 断点游标 */
  cursor: string;
  /** 扫描条数 */
  scanned_rows: number;
  /** 归档条数 */
  archived_rows: number;
  /** 删除条数 */
  deleted_rows: number;
  /** 内部归档表名 */
  archive_table_name: string;
  /** OSS对象Key */
  object_key: string;
  /** 对象大小 */
  size_bytes: number;
  /** SHA-256 */
  sha256: string;
  /** 归档状态 */
  status: BaseTableArchiveRecordStatus;
  /** 错误信息 */
  error: string;
  /** 开始时间 */
  started_at: string;
  /** 完成时间 */
  finished_at: string;
  /** 数据源名称 */
  source_name: string;
}

/** PageBaseTableArchiveRecordRequest 表归档记录分页请求。 */
export interface PageBaseTableArchiveRecordRequest {
  archive_id: number;
  table_name: string;
  status?: BaseTableArchiveRecordStatus | undefined;
  source_name: string;
  page_num: number;
  page_size: number;
}

/** PageBaseTableArchiveRecordResponse 表归档记录分页响应。 */
export interface PageBaseTableArchiveRecordResponse {
  base_table_archive_records: BaseTableArchiveRecord[];
  total: number;
}

/** GetBaseTableArchiveRecordRequest 查询表归档记录请求。 */
export interface GetBaseTableArchiveRecordRequest {
  id: number;
}

/** Admin表归档执行记录服务。 */
export interface BaseTableArchiveRecordService {
  /** 查询表归档记录分页列表。 */
  PageBaseTableArchiveRecord(request: PageBaseTableArchiveRecordRequest): Promise<PageBaseTableArchiveRecordResponse>;
  /** 查询表归档记录。 */
  GetBaseTableArchiveRecord(request: GetBaseTableArchiveRecordRequest): Promise<BaseTableArchiveRecord>;
}
