// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_table_backup_record.proto

/* eslint-disable */
import type { BaseTableBackupType } from "./base_table_backup";

/** BaseTableBackupRecordStatus 表示备份记录执行状态。 */
export enum BaseTableBackupRecordStatus {
  /** BASE_TABLE_BACKUP_RECORD_STATUS_UNSPECIFIED - 未指定备份记录状态。 */
  BASE_TABLE_BACKUP_RECORD_STATUS_UNSPECIFIED = 0,
  /** BASE_TABLE_BACKUP_RECORD_STATUS_RUNNING - 执行中。 */
  BASE_TABLE_BACKUP_RECORD_STATUS_RUNNING = 1,
  /** BASE_TABLE_BACKUP_RECORD_STATUS_SUCCESS - 执行成功。 */
  BASE_TABLE_BACKUP_RECORD_STATUS_SUCCESS = 2,
  /** BASE_TABLE_BACKUP_RECORD_STATUS_FAILED - 执行失败。 */
  BASE_TABLE_BACKUP_RECORD_STATUS_FAILED = 3,
  /** BASE_TABLE_BACKUP_RECORD_STATUS_DELETED - 对象已删除。 */
  BASE_TABLE_BACKUP_RECORD_STATUS_DELETED = 4,
}

/** BaseTableBackupRecord 数据库备份执行记录。 */
export interface BaseTableBackupRecord {
  /** 备份记录ID */
  id: number;
  /** 备份配置ID */
  backup_id: number;
  /** 数据源名称 */
  source_name: string;
  /** 数据库名称 */
  database_name: string;
  /** 备份类型 */
  backup_type: BaseTableBackupType;
  /** OSS对象Key */
  object_key: string;
  /** 对象大小 */
  size_bytes: number;
  /** SHA-256 */
  sha256: string;
  /** HMAC */
  hmac: string;
  /** 备份状态 */
  status: BaseTableBackupRecordStatus;
  /** 错误信息 */
  error: string;
  /** 开始时间 */
  started_at: string;
  /** 完成时间 */
  finished_at: string;
  /** 校验时间 */
  verified_at: string;
}

/** PageBaseTableBackupRecordRequest 数据库备份记录分页请求。 */
export interface PageBaseTableBackupRecordRequest {
  backup_id: number;
  source_name: string;
  status?: BaseTableBackupRecordStatus | undefined;
  page_num: number;
  page_size: number;
}

/** PageBaseTableBackupRecordResponse 数据库备份记录分页响应。 */
export interface PageBaseTableBackupRecordResponse {
  base_table_backup_records: BaseTableBackupRecord[];
  total: number;
}

/** GetBaseTableBackupRecordRequest 查询数据库备份记录请求。 */
export interface GetBaseTableBackupRecordRequest {
  id: number;
}

/** Admin数据库备份执行记录服务。 */
export interface BaseTableBackupRecordService {
  /** 查询数据库备份记录分页列表。 */
  PageBaseTableBackupRecord(request: PageBaseTableBackupRecordRequest): Promise<PageBaseTableBackupRecordResponse>;
  /** 查询数据库备份记录。 */
  GetBaseTableBackupRecord(request: GetBaseTableBackupRecordRequest): Promise<BaseTableBackupRecord>;
}
