// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_job_log.proto

/* eslint-disable */

/** 定时任务日志状态。 */
export enum BaseJobLogStatus {
  /** BASE_JOB_LOG_STATUS_UNSPECIFIED - 未指定定时任务日志状态。 */
  BASE_JOB_LOG_STATUS_UNSPECIFIED = 0,
  /** BASE_JOB_LOG_STATUS_SUCCESS - 成功。 */
  BASE_JOB_LOG_STATUS_SUCCESS = 1,
  /** BASE_JOB_LOG_STATUS_FAIL - 失败。 */
  BASE_JOB_LOG_STATUS_FAIL = 2,
}

/** 定时任务日志分页查询条件 */
export interface PageBaseJobLogRequest {
  /** 任务ID */
  job_id: number;
  /** 状态 */
  status?:
    | BaseJobLogStatus
    | undefined;
  /** 执行时间 */
  execute_time: string[];
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 定时任务日志分页响应 */
export interface PageBaseJobLogResponse {
  /** 分页数据 */
  base_job_logs: BaseJobLog[];
  /** 总数 */
  total: number;
}

/** 查询定时任务日志请求参数 */
export interface GetBaseJobLogRequest {
  /** 任务日志ID */
  id: number;
}

/** 定时任务日志 */
export interface BaseJobLog {
  /** 任务日志ID */
  id: number;
  /** 任务ID */
  job_id: number;
  /** 执行参数 */
  input: string;
  /** 输出结果 */
  output: string;
  /** 错误信息 */
  error: string;
  /** 状态：1、成功。2、失败。 */
  status: BaseJobLogStatus;
  /** 消耗时间/毫秒 */
  process_time: string;
  /** 执行时间 */
  execute_time: string;
}

/** Admin定时任务日志服务 */
export interface BaseJobLogService {
  /** 查询定时任务日志分页列表 */
  PageBaseJobLog(request: PageBaseJobLogRequest): Promise<PageBaseJobLogResponse>;
  /** 查询定时任务日志 */
  GetBaseJobLog(request: GetBaseJobLogRequest): Promise<BaseJobLog>;
}
