// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_message.proto

/* eslint-disable */
import type {
  MessageActionType,
  MessageAudienceType,
  MessageContentFormat,
  MessageDispatchStatus,
  MessagePriority,
  MessageStatus,
} from "../../../base/v1/notification";
import type { Empty } from "../../../google/protobuf/empty";

/** 消息分页查询条件。 */
export interface PageBaseMessageRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 消息分类ID */
  category_id?:
    | number
    | undefined;
  /** 消息标题 */
  title?:
    | string
    | undefined;
  /** 消息状态 */
  status?:
    | MessageStatus
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 消息分页响应。 */
export interface PageBaseMessageResponse {
  /** 消息列表 */
  base_messages: BaseMessage[];
  /** 总数 */
  total: number;
}

/** 消息详情查询条件。 */
export interface GetBaseMessageRequest {
  /** 消息ID */
  id: number;
}

/** 创建消息请求。 */
export interface CreateBaseMessageRequest {
  /** 消息表单 */
  base_message: BaseMessageForm | undefined;
}

/** 创建消息响应。 */
export interface CreateBaseMessageResponse {
  /** 消息ID */
  id: number;
}

/** 更新消息请求。 */
export interface UpdateBaseMessageRequest {
  /** 消息表单 */
  base_message: BaseMessageForm | undefined;
}

/** 删除消息请求。 */
export interface DeleteBaseMessageRequest {
  /** 消息ID列表 */
  id: string;
}

/** 发布消息请求。 */
export interface PublishBaseMessageRequest {
  /** 消息ID */
  id: number;
}

/** 取消消息定时发布请求。 */
export interface CancelBaseMessageScheduleRequest {
  /** 消息ID */
  id: number;
}

/** 撤回消息请求。 */
export interface RevokeBaseMessageRequest {
  /** 消息ID */
  id: number;
}

/** 重试投递任务请求。 */
export interface RetryBaseMessageDispatchRequest {
  /** 投递任务ID */
  id: number;
}

/** 消息受众表单。 */
export interface BaseMessageAudienceForm {
  /** 受众类型 */
  type: MessageAudienceType;
  /** 受众ID */
  id: number;
  /** 是否包含子部门 */
  include_children: boolean;
}

/** 消息表单。 */
export interface BaseMessageForm {
  /** 消息ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 消息分类ID */
  category_id: number;
  /** 消息标题 */
  title: string;
  /** 消息正文 */
  content: string;
  /** 正文格式 */
  content_format: MessageContentFormat;
  /** 消息优先级 */
  priority: MessagePriority;
  /** 动作类型 */
  action_type: MessageActionType;
  /** 动作目标 */
  action_target: string;
  /** 动作参数JSON */
  action_params: string;
  /** 计划发布时间 */
  scheduled_at: string;
  /** 过期时间 */
  expires_at: string;
  /** 消息受众 */
  audiences: BaseMessageAudienceForm[];
  /** 乐观锁版本 */
  version: number;
}

/** 消息列表项。 */
export interface BaseMessage {
  /** 消息ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 消息分类ID */
  category_id: number;
  /** 消息分类名称 */
  category_name: string;
  /** 消息标题 */
  title: string;
  /** 消息优先级 */
  priority: MessagePriority;
  /** 消息状态 */
  status: MessageStatus;
  /** 发送者名称 */
  sender_name: string;
  /** 目标人数 */
  recipient_total: number;
  /** 已投递人数 */
  delivered_total: number;
  /** 失败人数 */
  failed_total: number;
  /** 计划发布时间 */
  scheduled_at: string;
  /** 发布时间 */
  published_at: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** 消息投递任务。 */
export interface BaseMessageDispatch {
  /** 投递任务ID */
  id: number;
  /** 受众类型 */
  audience_type: MessageAudienceType;
  /** 受众ID */
  audience_id: number;
  /** 是否包含子部门 */
  include_children: boolean;
  /** 投递状态 */
  status: MessageDispatchStatus;
  /** 匹配人数 */
  matched_total: number;
  /** 新增投递人数 */
  inserted_total: number;
  /** 尝试次数 */
  attempt_count: number;
  /** 最近错误 */
  last_error: string;
}

/** 消息详情。 */
export interface BaseMessageDetail {
  /** 消息信息 */
  base_message:
    | BaseMessage
    | undefined;
  /** 消息表单 */
  form:
    | BaseMessageForm
    | undefined;
  /** 投递任务 */
  dispatches: BaseMessageDispatch[];
}

/** Admin站内信管理服务。 */
export interface BaseMessageService {
  /** 分页查询消息。 */
  PageBaseMessage(request: PageBaseMessageRequest): Promise<PageBaseMessageResponse>;
  /** 查询消息详情。 */
  GetBaseMessage(request: GetBaseMessageRequest): Promise<BaseMessageDetail>;
  /** 创建消息草稿。 */
  CreateBaseMessage(request: CreateBaseMessageRequest): Promise<CreateBaseMessageResponse>;
  /** 更新消息草稿。 */
  UpdateBaseMessage(request: UpdateBaseMessageRequest): Promise<Empty>;
  /** 删除消息草稿。 */
  DeleteBaseMessage(request: DeleteBaseMessageRequest): Promise<Empty>;
  /** 发布消息。 */
  PublishBaseMessage(request: PublishBaseMessageRequest): Promise<Empty>;
  /** 取消定时发布。 */
  CancelBaseMessageSchedule(request: CancelBaseMessageScheduleRequest): Promise<Empty>;
  /** 撤回消息。 */
  RevokeBaseMessage(request: RevokeBaseMessageRequest): Promise<Empty>;
  /** 重试消息投递任务。 */
  RetryBaseMessageDispatch(request: RetryBaseMessageDispatchRequest): Promise<Empty>;
}
