// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_oauth_provider.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseI18n } from "./base_i18n";

/** OAuth登录方式分页查询条件。 */
export interface PageBaseOauthProviderRequest {
  /** Provider标识 */
  provider?:
    | string
    | undefined;
  /** 登录方式名称 */
  name?:
    | string
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** OAuth登录方式分页响应。 */
export interface PageBaseOauthProviderResponse {
  /** OAuth登录方式列表 */
  base_oauth_providers: BaseOauthProvider[];
  /** 总数 */
  total: number;
}

/** OAuth登录方式详情查询条件。 */
export interface GetBaseOauthProviderRequest {
  /** OAuth登录方式ID */
  id: number;
}

/** 创建OAuth登录方式请求。 */
export interface CreateBaseOauthProviderRequest {
  /** OAuth登录方式表单 */
  base_oauth_provider: BaseOauthProviderForm | undefined;
}

/** 更新OAuth登录方式请求。 */
export interface UpdateBaseOauthProviderRequest {
  /** OAuth登录方式表单 */
  base_oauth_provider: BaseOauthProviderForm | undefined;
}

/** 删除OAuth登录方式请求。 */
export interface DeleteBaseOauthProviderRequest {
  /** OAuth登录方式ID列表 */
  id: string;
}

/** 设置OAuth登录方式状态请求。 */
export interface SetBaseOauthProviderStatusRequest {
  /** OAuth登录方式ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** OAuth登录方式表单。 */
export interface BaseOauthProviderForm {
  /** OAuth登录方式ID */
  id: number;
  /** Provider稳定标识 */
  provider: string;
  /** 登录方式名称 */
  name: string;
  /** 登录方式提示语 */
  description: string;
  /** 图标键或图片地址 */
  icon: string;
  /** 第三方应用标识 */
  client_id: string;
  /** 第三方应用密钥，更新时留空表示不修改 */
  client_secret: string;
  /** 是否已配置第三方应用密钥 */
  secret_configured: boolean;
  /** OAuth回调地址 */
  redirect_uri: string;
  /** OAuth Scope列表 */
  scopes: string[];
  /** Provider个性化配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 登录方式名称多语言翻译 */
  name_i18ns: BaseI18n[];
  /** 登录方式提示语多语言翻译 */
  description_i18ns: BaseI18n[];
}

/** OAuth登录方式。 */
export interface BaseOauthProvider {
  /** OAuth登录方式ID */
  id: number;
  /** Provider稳定标识 */
  provider: string;
  /** 登录方式名称 */
  name: string;
  /** 登录方式提示语 */
  description: string;
  /** 图标键或图片地址 */
  icon: string;
  /** 第三方应用标识 */
  client_id: string;
  /** OAuth回调地址 */
  redirect_uri: string;
  /** OAuth Scope列表 */
  scopes: string[];
  /** Provider个性化配置JSON对象 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 是否已配置第三方应用密钥 */
  secret_configured: boolean;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin OAuth第三方登录方式管理服务。 */
export interface BaseOauthProviderService {
  /** 分页查询OAuth登录方式。 */
  PageBaseOauthProvider(request: PageBaseOauthProviderRequest): Promise<PageBaseOauthProviderResponse>;
  /** 查询OAuth登录方式详情。 */
  GetBaseOauthProvider(request: GetBaseOauthProviderRequest): Promise<BaseOauthProviderForm>;
  /** 创建OAuth登录方式。 */
  CreateBaseOauthProvider(request: CreateBaseOauthProviderRequest): Promise<Empty>;
  /** 更新OAuth登录方式。 */
  UpdateBaseOauthProvider(request: UpdateBaseOauthProviderRequest): Promise<Empty>;
  /** 删除OAuth登录方式。 */
  DeleteBaseOauthProvider(request: DeleteBaseOauthProviderRequest): Promise<Empty>;
  /** 设置OAuth登录方式状态。 */
  SetBaseOauthProviderStatus(request: SetBaseOauthProviderStatusRequest): Promise<Empty>;
}
