// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_third_account.proto

/* eslint-disable */

/** 用户三方账号标识查询条件 */
export interface GetBaseThirdAccountIdentifierRequest {
  /** 用户ID */
  user_id: number;
  /** 登录方式标识 */
  provider: string;
}

/** 用户三方账号标识响应 */
export interface GetBaseThirdAccountIdentifierResponse {
  /** 三方账号唯一标识 */
  identifier: string;
}

/** Admin用户三方账号服务 */
export interface BaseThirdAccountService {
  /** 查询用户三方账号标识 */
  GetBaseThirdAccountIdentifier(
    request: GetBaseThirdAccountIdentifierRequest,
  ): Promise<GetBaseThirdAccountIdentifierResponse>;
}
