// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_table_backup.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** BaseTableBackupType 表示数据库备份类型。 */
export enum BaseTableBackupType {
  /** BASE_TABLE_BACKUP_TYPE_UNSPECIFIED - 未指定备份类型。 */
  BASE_TABLE_BACKUP_TYPE_UNSPECIFIED = 0,
  /** BASE_TABLE_BACKUP_TYPE_FULL - 全量备份。 */
  BASE_TABLE_BACKUP_TYPE_FULL = 1,
  /** BASE_TABLE_BACKUP_TYPE_INCREMENTAL - 增量备份，预留扩展。 */
  BASE_TABLE_BACKUP_TYPE_INCREMENTAL = 2,
}

/** BaseTableBackupForm 数据库备份配置表单。 */
export interface BaseTableBackupForm {
  /** 备份配置ID */
  id: number;
  /** 数据源名称 */
  source_name: string;
  /** 备份类型 */
  backup_type: BaseTableBackupType;
  /** OSS对象前缀 */
  oss_prefix: string;
  /** 保留数量 */
  retention_count: number;
  /** 状态 */
  status: Status;
}

/** PageBaseTableBackupRequest 数据库备份配置分页请求。 */
export interface PageBaseTableBackupRequest {
  source_name: string;
  status?: Status | undefined;
  page_num: number;
  page_size: number;
}

/** PageBaseTableBackupResponse 数据库备份配置分页响应。 */
export interface PageBaseTableBackupResponse {
  base_table_backups: BaseTableBackupForm[];
  total: number;
}

/** GetBaseTableBackupRequest 查询数据库备份配置请求。 */
export interface GetBaseTableBackupRequest {
  id: number;
}

/** CreateBaseTableBackupRequest 创建数据库备份配置请求。 */
export interface CreateBaseTableBackupRequest {
  base_table_backup: BaseTableBackupForm | undefined;
}

/** UpdateBaseTableBackupRequest 更新数据库备份配置请求。 */
export interface UpdateBaseTableBackupRequest {
  base_table_backup: BaseTableBackupForm | undefined;
}

/** DeleteBaseTableBackupRequest 删除数据库备份配置请求。 */
export interface DeleteBaseTableBackupRequest {
  id: string;
}

/** SetBaseTableBackupStatusRequest 设置数据库备份配置状态请求。 */
export interface SetBaseTableBackupStatusRequest {
  id: number;
  status: number;
}

/** Admin数据库备份配置服务。 */
export interface BaseTableBackupService {
  /** 查询数据库备份配置分页列表。 */
  PageBaseTableBackup(request: PageBaseTableBackupRequest): Promise<PageBaseTableBackupResponse>;
  /** 查询数据库备份配置。 */
  GetBaseTableBackup(request: GetBaseTableBackupRequest): Promise<BaseTableBackupForm>;
  /** 创建数据库备份配置。 */
  CreateBaseTableBackup(request: CreateBaseTableBackupRequest): Promise<Empty>;
  /** 更新数据库备份配置。 */
  UpdateBaseTableBackup(request: UpdateBaseTableBackupRequest): Promise<Empty>;
  /** 删除数据库备份配置。 */
  DeleteBaseTableBackup(request: DeleteBaseTableBackupRequest): Promise<Empty>;
  /** 设置数据库备份配置状态。 */
  SetBaseTableBackupStatus(request: SetBaseTableBackupStatusRequest): Promise<Empty>;
}
