// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_menu.proto

/* eslint-disable */
import type { TreeOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseI18n } from "./base_i18n";
import type { BaseMenuType } from "./common";

/** 菜单选项查询条件 */
export interface OptionBaseMenuRequest {
  /** 父级菜单ID */
  parent_id?:
    | number
    | undefined;
  /** 目标角色ID */
  role_id?:
    | number
    | undefined;
  /** 是否懒加载 */
  lazy?: boolean | undefined;
}

/** 菜单树查询条件 */
export interface TreeBaseMenuRequest {
  /** 父级菜单ID */
  parent_id?:
    | number
    | undefined;
  /** 是否懒加载 */
  lazy?: boolean | undefined;
}

/** 菜单树响应 */
export interface TreeBaseMenuResponse {
  /** 菜单树 */
  base_menus: BaseMenu[];
}

/** 查询菜单请求参数 */
export interface GetBaseMenuRequest {
  /** 菜单ID */
  id: number;
}

/** 菜单表单 */
export interface BaseMenuForm {
  /** 菜单ID */
  id: number;
  /** 父级菜单ID */
  parent_id?:
    | number
    | undefined;
  /** 菜单类型 */
  type: BaseMenuType;
  /** 菜单路径、按钮权限标识或外链内部路径，目录可为空 */
  path: string;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name: string;
  /** 组件路径 */
  component: string;
  /** 目录跳转路由或外链地址 */
  redirect: string;
  /** 路由元信息 */
  meta:
    | BaseMenuMeta
    | undefined;
  /** 分配的API列表 */
  api: string[];
  /** 非主语言翻译 */
  i18ns: BaseI18n[];
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
}

/** 创建菜单请求参数 */
export interface CreateBaseMenuRequest {
  /** 菜单表单 */
  base_menu: BaseMenuForm | undefined;
}

/** 更新菜单请求参数 */
export interface UpdateBaseMenuRequest {
  /** 菜单表单 */
  base_menu: BaseMenuForm | undefined;
}

/** 删除菜单请求参数 */
export interface DeleteBaseMenuRequest {
  /** 菜单ID列表 */
  id: string;
}

/** 设置菜单状态请求参数 */
export interface SetBaseMenuStatusRequest {
  /** 菜单ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 菜单 */
export interface BaseMenu {
  /** 菜单ID */
  id: number;
  /** 父级菜单ID */
  parent_id: number;
  /** 菜单类型 */
  type: BaseMenuType;
  /** 路由地址 */
  path: string;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name: string;
  /** 组件路径 */
  component: string;
  /** 重定向地址 */
  redirect: string;
  /** 路由元信息 */
  meta:
    | BaseMenuMeta
    | undefined;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 子菜单 */
  children: BaseMenu[];
  /** 是否存在子节点 */
  has_children: boolean;
  /** 非主语言翻译 */
  i18ns: BaseI18n[];
}

/** 菜单元信息 */
export interface BaseMenuMeta {
  /** 菜单标题 */
  title: string;
  /** 菜单图标 */
  icon?:
    | string
    | undefined;
  /** 【目录】只有一个子路由是否始终显示 */
  always_show?:
    | boolean
    | undefined;
  /** 是否隐藏(true-是 false-否) */
  hidden?:
    | boolean
    | undefined;
  /** 【菜单】是否开启页面缓存 */
  keep_alive?:
    | boolean
    | undefined;
  /** 【菜单】是否全屏(示例：数据大屏页面) */
  full?:
    | boolean
    | undefined;
  /** 【菜单】是否固定在标签页中(首页通常是固定项) */
  affix?:
    | boolean
    | undefined;
  /** 参数 */
  params: BaseMenuParams[];
  /** 移动端页面配置 */
  app: BaseMenuAppMeta | undefined;
}

/** 移动端页面配置 */
export interface BaseMenuAppMeta {
  /** 已注册的稳定视图键 */
  view_key: string;
  /** 页面访问模式 */
  access: string;
  /** 是否显示在自绘标签栏 */
  in_tab_bar: boolean;
  /** 标签栏选中图标 */
  selected_icon?: string | undefined;
}

/** 菜单参数 */
export interface BaseMenuParams {
  /** 参数key */
  key: string;
  /** 参数value */
  value: string;
}

/** Admin菜单管理服务 */
export interface BaseMenuService {
  /** 查询菜单树形选择 */
  OptionBaseMenu(request: OptionBaseMenuRequest): Promise<TreeOptionResponse>;
  /** 查询菜单树形列表 */
  TreeBaseMenu(request: TreeBaseMenuRequest): Promise<TreeBaseMenuResponse>;
  /** 查询菜单 */
  GetBaseMenu(request: GetBaseMenuRequest): Promise<BaseMenuForm>;
  /** 创建菜单 */
  CreateBaseMenu(request: CreateBaseMenuRequest): Promise<Empty>;
  /** 更新菜单 */
  UpdateBaseMenu(request: UpdateBaseMenuRequest): Promise<Empty>;
  /** 删除菜单 */
  DeleteBaseMenu(request: DeleteBaseMenuRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseMenuStatus(request: SetBaseMenuStatusRequest): Promise<Empty>;
}
