// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_job.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseI18n } from "./base_i18n";

/** 定时任务选项查询条件 */
export interface OptionBaseJobRequest {
}

/** 定时任务分页查询条件 */
export interface PageBaseJobRequest {
  /** 任务名称 */
  name: string;
  /** 调用目标 */
  invoke_target: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 定时任务分页响应 */
export interface PageBaseJobResponse {
  /** 分页数据 */
  base_jobs: BaseJob[];
  /** 总数 */
  total: number;
}

/** 查询定时任务请求参数 */
export interface GetBaseJobRequest {
  /** 任务ID */
  id: number;
}

/** 定时任务表单 */
export interface BaseJobForm {
  /** 任务ID */
  id: number;
  /** 任务名称 */
  name: string;
  /** 调用目标 */
  invoke_target: string;
  /** 目标参数 */
  args: BaseJobArgs[];
  /** cron表达式 */
  cron_expression: string;
  /** 状态 */
  status: Status;
  /** 定时任务名称多语言翻译 */
  i18ns: BaseI18n[];
}

/** 创建定时任务请求参数 */
export interface CreateBaseJobRequest {
  /** 定时任务表单 */
  base_job: BaseJobForm | undefined;
}

/** 更新定时任务请求参数 */
export interface UpdateBaseJobRequest {
  /** 定时任务表单 */
  base_job: BaseJobForm | undefined;
}

/** 删除定时任务请求参数 */
export interface DeleteBaseJobRequest {
  /** 任务ID列表 */
  id: string;
}

/** 设置定时任务状态请求参数 */
export interface SetBaseJobStatusRequest {
  /** 任务ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 启动定时任务请求参数 */
export interface StartBaseJobRequest {
  /** 任务ID */
  id: number;
}

/** 停止定时任务请求参数 */
export interface StopBaseJobRequest {
  /** 任务ID */
  id: number;
}

/** 执行任务请求参数 */
export interface ExecuteBaseJobRequest {
  /** 任务ID */
  id: number;
}

/** 定时任务参数 */
export interface BaseJobArgs {
  /** 参数 */
  key: string;
  /** 值 */
  value: string;
}

/** 定时任务 */
export interface BaseJob {
  /** 任务ID */
  id: number;
  /** 任务名称 */
  name: string;
  /** 调用目标 */
  invoke_target: string;
  /** 目标参数 */
  args: BaseJobArgs[];
  /** cron表达式 */
  cron_expression: string;
  /** job启动时返回的id */
  entry_id: number;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 定时任务名称多语言翻译 */
  i18ns: BaseI18n[];
}

/** Admin定时任务服务 */
export interface BaseJobService {
  /** 查询定时任务下拉选择 */
  OptionBaseJob(request: OptionBaseJobRequest): Promise<SelectOptionResponse>;
  /** 查询定时任务分页列表 */
  PageBaseJob(request: PageBaseJobRequest): Promise<PageBaseJobResponse>;
  /** 查询定时任务 */
  GetBaseJob(request: GetBaseJobRequest): Promise<BaseJobForm>;
  /** 创建定时任务 */
  CreateBaseJob(request: CreateBaseJobRequest): Promise<Empty>;
  /** 更新定时任务 */
  UpdateBaseJob(request: UpdateBaseJobRequest): Promise<Empty>;
  /** 删除定时任务 */
  DeleteBaseJob(request: DeleteBaseJobRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseJobStatus(request: SetBaseJobStatusRequest): Promise<Empty>;
  /** 启动任务 */
  StartBaseJob(request: StartBaseJobRequest): Promise<Empty>;
  /** 停止任务 */
  StopBaseJob(request: StopBaseJobRequest): Promise<Empty>;
  /** 执行任务 */
  ExecuteBaseJob(request: ExecuteBaseJobRequest): Promise<Empty>;
}
