// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_post.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 岗位选项查询条件 */
export interface OptionBasePostRequest {
  /** 租户ID */
  tenant_id?: number | undefined;
}

/** 岗位分页查询条件 */
export interface PageBasePostRequest {
  /** 岗位名称 */
  name: string;
  /** 岗位编号 */
  code: string;
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 岗位分页响应 */
export interface PageBasePostResponse {
  /** 分页数据 */
  base_posts: BasePost[];
  /** 总数 */
  total: number;
}

/** 查询岗位请求参数 */
export interface GetBasePostRequest {
  /** 岗位ID */
  id: number;
}

/** 岗位表单 */
export interface BasePostForm {
  /** 岗位ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 岗位名称 */
  name: string;
  /** 岗位编号 */
  code: string;
  /** 显示顺序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
}

/** 创建岗位请求参数 */
export interface CreateBasePostRequest {
  /** 岗位表单 */
  base_post: BasePostForm | undefined;
}

/** 更新岗位请求参数 */
export interface UpdateBasePostRequest {
  /** 岗位表单 */
  base_post: BasePostForm | undefined;
}

/** 删除岗位请求参数 */
export interface DeleteBasePostRequest {
  /** 岗位ID列表 */
  id: string;
}

/** 设置岗位状态请求参数 */
export interface SetBasePostStatusRequest {
  /** 岗位ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 岗位 */
export interface BasePost {
  /** 岗位ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 岗位名称 */
  name: string;
  /** 岗位编号 */
  code: string;
  /** 显示顺序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin岗位管理服务 */
export interface BasePostService {
  /** 查询岗位下拉选择 */
  OptionBasePost(request: OptionBasePostRequest): Promise<SelectOptionResponse>;
  /** 查询岗位分页列表 */
  PageBasePost(request: PageBasePostRequest): Promise<PageBasePostResponse>;
  /** 查询岗位 */
  GetBasePost(request: GetBasePostRequest): Promise<BasePostForm>;
  /** 创建岗位 */
  CreateBasePost(request: CreateBasePostRequest): Promise<Empty>;
  /** 更新岗位 */
  UpdateBasePost(request: UpdateBasePostRequest): Promise<Empty>;
  /** 删除岗位 */
  DeleteBasePost(request: DeleteBasePostRequest): Promise<Empty>;
  /** 设置岗位状态 */
  SetBasePostStatus(request: SetBasePostStatusRequest): Promise<Empty>;
}
