// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_api_log.proto

/* eslint-disable */
import type { BaseLogResult } from "./base_log";

/** API 访问日志分页查询条件。 */
export interface PageBaseApiLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 结果 */
  result?:
    | BaseLogResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** API 访问日志分页响应。 */
export interface PageBaseApiLogResponse {
  /** API访问日志列表 */
  base_api_logs: BaseApiLog[];
  /** 总数 */
  total: number;
}

/** 查询 API 访问日志详情请求。 */
export interface GetBaseApiLogRequest {
  /** API日志ID */
  id: string;
}

/** API 访问日志。 */
export interface BaseApiLog {
  /** API日志ID */
  id: string;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 用户名称 */
  user_name: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 服务名 */
  service_name: string;
  /** 操作方法 */
  operation: string;
  /** 请求方法 */
  method: string;
  /** 请求路径 */
  path: string;
  /** 状态码 */
  status_code: number;
  /** 结果 */
  result: BaseLogResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 耗时毫秒 */
  latency_ms: number;
  /** 请求大小 */
  request_size: number;
  /** 响应大小 */
  response_size: number;
  /** 客户端IP */
  client_ip: string;
  /** 用户代理 */
  user_agent: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志落库时间 */
  created_at: string;
}

/** Admin API访问日志服务。 */
export interface BaseApiLogService {
  /** 分页查询 API 访问日志。 */
  PageBaseApiLog(request: PageBaseApiLogRequest): Promise<PageBaseApiLogResponse>;
  /** 查询 API 访问日志详情。 */
  GetBaseApiLog(request: GetBaseApiLogRequest): Promise<BaseApiLog>;
}
