// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_file.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** 文件资产分页查询条件。 */
export interface PageBaseFileRequest {
  /** 原始文件名或内容哈希关键字 */
  keyword: string;
  /** 文件扩展名 */
  extension: string;
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 文件资产分页响应。 */
export interface PageBaseFileResponse {
  /** 文件资产列表 */
  base_files: BaseFile[];
  /** 总数 */
  total: number;
}

/** 文件资产详情查询条件。 */
export interface GetBaseFileRequest {
  /** 文件ID */
  id: number;
}

/** 文件资产删除条件。 */
export interface DeleteBaseFileRequest {
  /** 文件ID */
  id: number;
}

/** 文件资产元数据。 */
export interface BaseFile {
  /** 文件ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 存储供应商 */
  provider: number;
  /** 存储桶名称 */
  bucket_name: string;
  /** 文件目录 */
  file_directory: string;
  /** 文件唯一标识 */
  file_guid: string;
  /** 实际存储文件名 */
  save_file_name: string;
  /** 原始文件名 */
  file_name: string;
  /** 文件扩展名 */
  extension: string;
  /** 文件MIME类型 */
  mime_type: string;
  /** 文件大小，单位字节 */
  size: number;
  /** 文件访问地址 */
  link_url: string;
  /** 文件内容SHA-256哈希 */
  content_hash: string;
  /** 创建者ID */
  created_by: number;
  /** 创建时间 */
  created_at: string;
}

/** Admin文件资产管理服务。 */
export interface BaseFileService {
  /** 分页查询文件资产。 */
  PageBaseFile(request: PageBaseFileRequest): Promise<PageBaseFileResponse>;
  /** 查询文件资产详情。 */
  GetBaseFile(request: GetBaseFileRequest): Promise<BaseFile>;
  /** 删除文件资产及其对象。 */
  DeleteBaseFile(request: DeleteBaseFileRequest): Promise<Empty>;
}
