// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_tenant_project_grant.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** BaseTenantProjectGrantSubjectType 项目授权主体类型。 */
export enum BaseTenantProjectGrantSubjectType {
  /** BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_UNSPECIFIED - 未指定 */
  BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_UNSPECIFIED = 0,
  /** BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_POST - 岗位 */
  BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_POST = 1,
  /** BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_ROLE - 角色 */
  BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_ROLE = 2,
  /** BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_DEPT - 部门 */
  BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_DEPT = 3,
  /** BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_USER - 用户 */
  BASE_TENANT_PROJECT_GRANT_SUBJECT_TYPE_USER = 4,
}

/** 项目授权主体和目标租户查询条件。 */
export interface BaseTenantProjectGrantKey {
  /** 授权目标租户ID */
  tenant_id: number;
  /** 授权主体类型 */
  subject_type: BaseTenantProjectGrantSubjectType;
  /** 授权主体ID */
  subject_id: number;
}

/** 项目授权记录，project_id 为 [0] 时表示目标租户全部项目，空数组表示无权限。 */
export interface BaseTenantProjectGrant {
  /** 授权目标租户ID */
  tenant_id: number;
  /** 授权主体类型 */
  subject_type: BaseTenantProjectGrantSubjectType;
  /** 授权主体ID */
  subject_id: number;
  /** 项目主键ID数字数组，[0]全部，[]无权限 */
  project_id: number[];
  /** 租户名称 */
  tenant_name: string;
  /** 授权主体名称 */
  subject_name: string;
  /** 授权主体编码 */
  subject_code: string;
  /** 授权项目名称列表 */
  project_names: string[];
  /** 项目授权联合主键展示值 */
  grant_key: string;
}

/** 项目授权分页查询条件。 */
export interface PageBaseTenantProjectGrantRequest {
  /** 授权目标租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 授权主体类型 */
  subject_type?:
    | BaseTenantProjectGrantSubjectType
    | undefined;
  /** 授权主体ID */
  subject_id?:
    | number
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 项目授权分页响应。 */
export interface PageBaseTenantProjectGrantResponse {
  /** 项目授权列表 */
  grants: BaseTenantProjectGrant[];
  /** 总数 */
  total: number;
}

/** 查询项目授权请求参数。 */
export interface GetBaseTenantProjectGrantRequest {
  /** 授权目标租户ID */
  tenant_id: number;
  /** 授权主体类型 */
  subject_type: BaseTenantProjectGrantSubjectType;
  /** 授权主体ID */
  subject_id: number;
}

/** 创建项目授权请求参数。 */
export interface CreateBaseTenantProjectGrantRequest {
  /** 项目授权表单 */
  base_tenant_project_grant: BaseTenantProjectGrant | undefined;
}

/** 更新项目授权请求参数。 */
export interface UpdateBaseTenantProjectGrantRequest {
  /** 项目授权表单 */
  base_tenant_project_grant: BaseTenantProjectGrant | undefined;
}

/** 删除项目授权请求参数。 */
export interface DeleteBaseTenantProjectGrantRequest {
  /** 授权目标租户ID */
  tenant_id: number;
  /** 授权主体类型 */
  subject_type: BaseTenantProjectGrantSubjectType;
  /** 授权主体ID */
  subject_id: number;
}

/** BaseTenantProjectGrantService 管理岗位、角色、部门和用户在目标租户下的项目授权。 */
export interface BaseTenantProjectGrantService {
  /** 查询项目授权分页列表。 */
  PageBaseTenantProjectGrant(request: PageBaseTenantProjectGrantRequest): Promise<PageBaseTenantProjectGrantResponse>;
  /** 查询项目授权详情。 */
  GetBaseTenantProjectGrant(request: GetBaseTenantProjectGrantRequest): Promise<BaseTenantProjectGrant>;
  /** 新增项目授权。 */
  CreateBaseTenantProjectGrant(request: CreateBaseTenantProjectGrantRequest): Promise<Empty>;
  /** 更新项目授权，只修改项目范围，授权主体联合键不可变更。 */
  UpdateBaseTenantProjectGrant(request: UpdateBaseTenantProjectGrantRequest): Promise<Empty>;
  /** 删除项目授权。 */
  DeleteBaseTenantProjectGrant(request: DeleteBaseTenantProjectGrantRequest): Promise<Empty>;
}
