// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_table_archive_restore.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** BaseTableArchiveRestoreMode 表示归档数据恢复模式。 */
export enum BaseTableArchiveRestoreMode {
  /** BASE_TABLE_ARCHIVE_RESTORE_MODE_UNSPECIFIED - 未指定归档恢复模式。 */
  BASE_TABLE_ARCHIVE_RESTORE_MODE_UNSPECIFIED = 0,
  /** BASE_TABLE_ARCHIVE_RESTORE_MODE_ALL - 恢复全部归档数据。 */
  BASE_TABLE_ARCHIVE_RESTORE_MODE_ALL = 1,
  /** BASE_TABLE_ARCHIVE_RESTORE_MODE_SELECTED - 按范围选择性恢复。 */
  BASE_TABLE_ARCHIVE_RESTORE_MODE_SELECTED = 2,
}

/** BaseTableArchiveRestoreStatus 表示归档恢复状态。 */
export enum BaseTableArchiveRestoreStatus {
  /** BASE_TABLE_ARCHIVE_RESTORE_STATUS_UNSPECIFIED - 未指定归档恢复状态。 */
  BASE_TABLE_ARCHIVE_RESTORE_STATUS_UNSPECIFIED = 0,
  /** BASE_TABLE_ARCHIVE_RESTORE_STATUS_PENDING - 等待人工确认。 */
  BASE_TABLE_ARCHIVE_RESTORE_STATUS_PENDING = 1,
  /** BASE_TABLE_ARCHIVE_RESTORE_STATUS_RUNNING - 执行中。 */
  BASE_TABLE_ARCHIVE_RESTORE_STATUS_RUNNING = 2,
  /** BASE_TABLE_ARCHIVE_RESTORE_STATUS_SUCCESS - 执行成功。 */
  BASE_TABLE_ARCHIVE_RESTORE_STATUS_SUCCESS = 3,
  /** BASE_TABLE_ARCHIVE_RESTORE_STATUS_FAILED - 执行失败。 */
  BASE_TABLE_ARCHIVE_RESTORE_STATUS_FAILED = 4,
}

/** BaseTableArchiveRestore 归档恢复记录。 */
export interface BaseTableArchiveRestore {
  /** 恢复记录ID */
  id: number;
  /** 归档记录ID */
  archive_record_id: number;
  /** 数据表名称 */
  table_name: string;
  /** 恢复模式 */
  restore_mode: BaseTableArchiveRestoreMode;
  /** 恢复范围 */
  restore_range: string;
  /** 恢复条数 */
  restored_rows: number;
  /** 操作人ID */
  operator_id: number;
  /** 恢复状态 */
  status: BaseTableArchiveRestoreStatus;
  /** 错误信息 */
  error: string;
  /** 开始时间 */
  started_at: string;
  /** 完成时间 */
  finished_at: string;
}

/** PageBaseTableArchiveRestoreRequest 归档恢复记录分页请求。 */
export interface PageBaseTableArchiveRestoreRequest {
  status?: BaseTableArchiveRestoreStatus | undefined;
  page_num: number;
  page_size: number;
}

/** PageBaseTableArchiveRestoreResponse 归档恢复记录分页响应。 */
export interface PageBaseTableArchiveRestoreResponse {
  base_table_archive_restores: BaseTableArchiveRestore[];
  total: number;
}

/** GetBaseTableArchiveRestoreRequest 查询归档恢复记录请求。 */
export interface GetBaseTableArchiveRestoreRequest {
  id: number;
}

/** ExecuteBaseTableArchiveRestoreRequest 执行归档恢复请求。 */
export interface ExecuteBaseTableArchiveRestoreRequest {
  base_table_archive_restore: BaseTableArchiveRestore | undefined;
}

/** Admin归档数据恢复服务。 */
export interface BaseTableArchiveRestoreService {
  /** 查询归档恢复记录分页列表。 */
  PageBaseTableArchiveRestore(
    request: PageBaseTableArchiveRestoreRequest,
  ): Promise<PageBaseTableArchiveRestoreResponse>;
  /** 查询归档恢复记录。 */
  GetBaseTableArchiveRestore(request: GetBaseTableArchiveRestoreRequest): Promise<BaseTableArchiveRestore>;
  /** 手工执行归档恢复。 */
  ExecuteBaseTableArchiveRestore(request: ExecuteBaseTableArchiveRestoreRequest): Promise<Empty>;
}
