// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_config.proto

/* eslint-disable */
import type { BaseConfigSite } from "../../../base/v1/config";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseI18n } from "./base_i18n";

/** 系统配置类型。 */
export enum BaseConfigType {
  /** BASE_CONFIG_TYPE_UNSPECIFIED - 未指定系统配置类型。 */
  BASE_CONFIG_TYPE_UNSPECIFIED = 0,
  /** BASE_CONFIG_TYPE_TEXT - 文本。 */
  BASE_CONFIG_TYPE_TEXT = 1,
  /** BASE_CONFIG_TYPE_IMAGE - 图片。 */
  BASE_CONFIG_TYPE_IMAGE = 2,
  /** BASE_CONFIG_TYPE_RICH_TEXT - 富文本。 */
  BASE_CONFIG_TYPE_RICH_TEXT = 3,
  /** BASE_CONFIG_TYPE_DICT - 字典。 */
  BASE_CONFIG_TYPE_DICT = 4,
  /** BASE_CONFIG_TYPE_BOOLEAN - 布尔。 */
  BASE_CONFIG_TYPE_BOOLEAN = 5,
}

/** 系统配置隐藏状态。 */
export enum BaseConfigHiddenStatus {
  /** BASE_CONFIG_HIDDEN_STATUS_UNSPECIFIED - 未指定隐藏状态。 */
  BASE_CONFIG_HIDDEN_STATUS_UNSPECIFIED = 0,
  /** BASE_CONFIG_HIDDEN_STATUS_VISIBLE - 普通配置，可在通用配置页面展示。 */
  BASE_CONFIG_HIDDEN_STATUS_VISIBLE = 1,
  /** BASE_CONFIG_HIDDEN_STATUS_HIDDEN - 隐藏配置，仅允许通过专用配置表单访问。 */
  BASE_CONFIG_HIDDEN_STATUS_HIDDEN = 2,
}

/** 系统配置分页查询条件 */
export interface PageBaseConfigRequest {
  /** 位置：枚举【BaseConfigSite】 */
  site?:
    | BaseConfigSite
    | undefined;
  /** 配置名称 */
  name?:
    | string
    | undefined;
  /** 配置类型：枚举【BaseConfigType】 */
  type?:
    | BaseConfigType
    | undefined;
  /** 配置key */
  key?:
    | string
    | undefined;
  /** 状态：枚举【Status】 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 系统配置分页响应 */
export interface PageBaseConfigResponse {
  /** 分页数据 */
  base_configs: BaseConfig[];
  /** 总数 */
  total: number;
}

/** 查询系统配置请求参数 */
export interface GetBaseConfigRequest {
  /** 配置ID */
  id: number;
}

/** 系统配置表单 */
export interface BaseConfigForm {
  /** 配置ID */
  id: number;
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
  /** 配置名称 */
  name: string;
  /** 配置类型：1、文本，2、图片，3、富文本，4、字典，5、布尔 */
  type: BaseConfigType;
  /** 配置key */
  key: string;
  /** 配置value */
  value: string;
  /** 隐藏状态 */
  hidden_status: BaseConfigHiddenStatus;
  /** 配置名称多语言翻 */
  name_i18ns: BaseI18n[];
  /** 配置value文本/富文本配置值的多语言翻译 */
  value_i18ns: BaseI18n[];
  /** 状态 */
  status: Status;
}

/** 创建系统配置请求参数 */
export interface CreateBaseConfigRequest {
  /** 系统配置表单 */
  base_config: BaseConfigForm | undefined;
}

/** 更新系统配置请求参数 */
export interface UpdateBaseConfigRequest {
  /** 系统配置表单 */
  base_config: BaseConfigForm | undefined;
}

/** 删除系统配置请求参数 */
export interface DeleteBaseConfigRequest {
  /** 配置ID列表 */
  id: string;
}

/** 设置系统配置状态请求参数 */
export interface SetBaseConfigStatusRequest {
  /** 配置ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 刷新系统配置缓存请求参数 */
export interface RefreshBaseConfigCacheRequest {
}

/** 系统配置 */
export interface BaseConfig {
  /** 配置ID */
  id: number;
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
  /** 配置名称 */
  name: string;
  /** 配置类型：枚举【BaseConfigType】 */
  type: BaseConfigType;
  /** 配置key */
  key: string;
  /** 配置value */
  value: string;
  /** 隐藏状态 */
  hidden_status: BaseConfigHiddenStatus;
  /** 状态：枚举【Status】 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 配置名称及文本/富文本配置值的多语言翻译 */
  i18ns: BaseI18n[];
}

/** 按配置键查询系统配置请求参数。 */
export interface GetBaseConfigByKeyRequest {
  /** 配置key */
  key: string;
}

/** 按配置键返回系统配置值。 */
export interface BaseConfigValue {
  /** 配置key */
  key: string;
  /** JSON格式配置值 */
  value_json: string;
  /** 更新时间 */
  updated_at: string;
}

/** 按配置键更新系统配置请求参数。 */
export interface UpdateBaseConfigByKeyRequest {
  /** 配置key */
  key: string;
  /** JSON格式配置值 */
  value_json: string;
}

/** Admin系统配置服务 */
export interface BaseConfigService {
  /** 刷新缓存 */
  RefreshBaseConfigCache(request: RefreshBaseConfigCacheRequest): Promise<Empty>;
  /** 查询系统配置分页列表 */
  PageBaseConfig(request: PageBaseConfigRequest): Promise<PageBaseConfigResponse>;
  /** 查询系统配置 */
  GetBaseConfig(request: GetBaseConfigRequest): Promise<BaseConfigForm>;
  /** 按配置键查询隐藏系统配置。 */
  GetBaseConfigByKey(request: GetBaseConfigByKeyRequest): Promise<BaseConfigValue>;
  /** 创建系统配置 */
  CreateBaseConfig(request: CreateBaseConfigRequest): Promise<Empty>;
  /** 更新系统配置 */
  UpdateBaseConfig(request: UpdateBaseConfigRequest): Promise<Empty>;
  /** 按配置键更新隐藏系统配置。 */
  UpdateBaseConfigByKey(request: UpdateBaseConfigByKeyRequest): Promise<Empty>;
  /** 删除系统配置 */
  DeleteBaseConfig(request: DeleteBaseConfigRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseConfigStatus(request: SetBaseConfigStatusRequest): Promise<Empty>;
}
