// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_redact_common.proto

/* eslint-disable */

/** 脱敏策略方向。 */
export enum BaseRedactDirection {
  /** BASE_REDACT_DIRECTION_UNSPECIFIED - 未指定方向。 */
  BASE_REDACT_DIRECTION_UNSPECIFIED = 0,
  /** BASE_REDACT_DIRECTION_REQUEST - 请求参数方向。 */
  BASE_REDACT_DIRECTION_REQUEST = 1,
  /** BASE_REDACT_DIRECTION_RESPONSE - 响应数据方向。 */
  BASE_REDACT_DIRECTION_RESPONSE = 2,
}
