// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_login_log.proto

/* eslint-disable */
import type { BaseLogResult } from "./base_log";

/**
 * BaseLoginLogType 定义认证链路产生的登录事件类型。
 * 类型用于区分密码、OAuth、MFA、令牌刷新和退出操作的审计统计。
 */
export enum BaseLoginLogType {
  /** BASE_LOGIN_LOG_TYPE_UNSPECIFIED - 未指定登录日志类型。 */
  BASE_LOGIN_LOG_TYPE_UNSPECIFIED = 0,
  /** BASE_LOGIN_LOG_TYPE_PASSWORD - 密码登录。 */
  BASE_LOGIN_LOG_TYPE_PASSWORD = 1,
  /** BASE_LOGIN_LOG_TYPE_OAUTH - OAuth 登录。 */
  BASE_LOGIN_LOG_TYPE_OAUTH = 2,
  /** BASE_LOGIN_LOG_TYPE_MFA - 多因素认证。 */
  BASE_LOGIN_LOG_TYPE_MFA = 3,
  /** BASE_LOGIN_LOG_TYPE_TOKEN_REFRESH - 刷新访问令牌。 */
  BASE_LOGIN_LOG_TYPE_TOKEN_REFRESH = 4,
  /** BASE_LOGIN_LOG_TYPE_LOGOUT - 退出登录。 */
  BASE_LOGIN_LOG_TYPE_LOGOUT = 5,
}

/** 本人登录记录分页条件，用户和租户由服务端认证身份确定。 */
export interface PageCurrentUserLoginLogRequest {
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 登录日志分页查询条件。 */
export interface PageBaseLoginLogRequest {
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 用户ID */
  user_id?:
    | number
    | undefined;
  /** 登录类型 */
  login_type?:
    | BaseLoginLogType
    | undefined;
  /** 结果 */
  result?:
    | BaseLogResult
    | undefined;
  /** 事件时间 */
  occurred_at: string[];
  /** 关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 登录日志分页响应。 */
export interface PageBaseLoginLogResponse {
  /** 登录日志列表 */
  base_login_logs: BaseLoginLog[];
  /** 总数 */
  total: number;
}

/** 查询登录日志详情请求。 */
export interface GetBaseLoginLogRequest {
  /** 登录日志ID */
  id: string;
}

/** 登录日志。 */
export interface BaseLoginLog {
  /** 登录日志ID */
  id: string;
  /** 租户ID */
  tenant_id: number;
  /** 租户编码 */
  tenant_code: string;
  /** 用户ID */
  user_id: number;
  /** 账号名 */
  user_name: string;
  /** 登录类型 */
  login_type: BaseLoginLogType;
  /** 结果 */
  result: BaseLogResult;
  /** 原因编码 */
  reason_code: string;
  /** 原因说明 */
  reason: string;
  /** 客户端IP */
  client_ip: string;
  /** 用户代理 */
  user_agent: string;
  /** 设备标识 */
  device_id: string;
  /** 请求ID */
  request_id: string;
  /** 链路追踪ID */
  trace_id: string;
  /** 事件发生时间 */
  occurred_at: string;
  /** 日志落库时间 */
  created_at: string;
}

/** Admin登录日志服务。 */
export interface BaseLoginLogService {
  /** 分页查询当前登录用户本人的登录记录。 */
  PageCurrentUserLoginLog(request: PageCurrentUserLoginLogRequest): Promise<PageBaseLoginLogResponse>;
  /** 分页查询登录日志。 */
  PageBaseLoginLog(request: PageBaseLoginLogRequest): Promise<PageBaseLoginLogResponse>;
  /** 查询登录日志详情。 */
  GetBaseLoginLog(request: GetBaseLoginLogRequest): Promise<BaseLoginLog>;
}
