// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/cache.proto

/* eslint-disable */

/** 缓存分页查询条件。 */
export interface PageCacheRequest {
  /** 缓存键关键字 */
  keyword: string;
  /** 当前页码 */
  page_num: number;
  /** 每页行数 */
  page_size: number;
}

/** 缓存分页响应。 */
export interface PageCacheResponse {
  /** 缓存条目列表 */
  cache_entries: CacheEntry[];
  /** 匹配条目总数 */
  total: number;
}

/** 缓存查询结果。 */
export interface CacheEntry {
  /** 缓存键 */
  key: string;
  /** 缓存类型：string或hash */
  type: string;
  /** 字符串缓存值 */
  value: string;
  /** Hash缓存字段 */
  fields: CacheField[];
  /** 剩余有效期，-1表示永不过期 */
  ttl_seconds: number;
  /** 过期时间，RFC3339格式；永不过期时为空 */
  expires_at: string;
  /** 首次写入或首次观测时间，RFC3339格式 */
  created_at: string;
  /** 最近写入或过期时间变更时间，RFC3339格式 */
  updated_at: string;
}

/** Hash缓存字段。 */
export interface CacheField {
  /** 字段名 */
  key: string;
  /** 字段值 */
  value: string;
}

/** Admin运行时缓存查询服务。 */
export interface CacheService {
  /** 分页查询当前进程已观测到的缓存条目。 */
  PageCache(request: PageCacheRequest): Promise<PageCacheResponse>;
}
