// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/code_gen_column.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";
import type { CodeGenLocaleConfig } from "./base_i18n";

/** 代码生成字段配置查询条件 */
export interface ListCodeGenColumnRequest {
  /** 代码生成表配置ID */
  table_id: number;
}

/** 代码生成字段配置查询响应 */
export interface ListCodeGenColumnResponse {
  /** 代码生成字段配置列表 */
  code_gen_columns: CodeGenColumn[];
}

/** 数据库表字段列表查询条件 */
export interface ListCodeGenDatabaseColumnRequest {
  /** 数据库表名 */
  table_name: string;
  /** 数据源名称 */
  source_name: string;
}

/** 数据库表字段列表响应 */
export interface ListCodeGenDatabaseColumnResponse {
  /** 数据库字段列表 */
  columns: CodeGenDatabaseColumn[];
}

/** 代码生成字段配置保存条件 */
export interface SaveCodeGenColumnRequest {
  /** 代码生成表配置ID */
  table_id: number;
  /** 代码生成字段配置列表 */
  code_gen_columns: CodeGenColumn[];
}

/** 数据库字段元数据 */
export interface CodeGenDatabaseColumn {
  /** 数据库字段名 */
  name: string;
  /** 数据库字段注释 */
  comment: string;
  /** 数据库字段类型 */
  db_type: string;
  /** 数据库完整字段类型 */
  column_type: string;
  /** 是否主键 */
  is_primary: boolean;
  /** 是否允许为空 */
  is_nullable: boolean;
}

/** 代码生成字段配置 */
export interface CodeGenColumn {
  /** 主键ID */
  id: number;
  /** 代码生成表配置ID */
  table_id: number;
  /** 数据库字段名 */
  name: string;
  /** 数据库字段注释 */
  comment: string;
  /** 数据库字段类型 */
  db_type: string;
  /** 数据库字段长度 */
  db_length: number;
  /** 数据库字段小数位 */
  db_scale: number;
  /** 是否主键 */
  is_primary: boolean;
  /** 是否自增 */
  is_auto_increment: boolean;
  /** 是否允许为空 */
  is_nullable: boolean;
  /** Go字段类型 */
  go_type: string;
  /** Proto字段类型 */
  proto_type: string;
  /** TypeScript字段类型 */
  ts_type: string;
  /** 查询条件配置 */
  query_config:
    | CodeGenColumnQueryConfig
    | undefined;
  /** 列表展示配置 */
  list_config:
    | CodeGenColumnListConfig
    | undefined;
  /** 表单录入配置 */
  form_config:
    | CodeGenColumnFormConfig
    | undefined;
  /** 排序 */
  sort: number;
  /** 按语言区域索引的字段国际化配置 */
  i18n_config: Map<string, CodeGenLocaleConfig>;
}

export interface CodeGenColumn_I18nConfigEntry {
  key: string;
  value: CodeGenLocaleConfig | undefined;
}

/** 代码生成字段查询条件配置 */
export interface CodeGenColumnQueryConfig {
  /** 是否启用查询 */
  enabled: boolean;
  /** 查询操作符 */
  operator: string;
  /** 查询组件 */
  component: string;
  /** 查询选项配置 */
  option: CodeGenColumnOptionConfig | undefined;
}

/** 代码生成字段列表展示配置 */
export interface CodeGenColumnListConfig {
  /** 是否在列表展示 */
  enabled: boolean;
  /** 列表展示组件 */
  component: string;
  /** 列表选项配置 */
  option: CodeGenColumnOptionConfig | undefined;
}

/** 代码生成字段表单录入配置 */
export interface CodeGenColumnFormConfig {
  /** 是否在表单展示 */
  enabled: boolean;
  /** 表单录入组件 */
  component: string;
  /** 是否必填 */
  required: boolean;
  /** 表单选项配置 */
  option:
    | CodeGenColumnOptionConfig
    | undefined;
  /** 树形选择是否多选 */
  multiple: boolean;
}

/** 代码生成字段选项配置 */
export interface CodeGenColumnOptionConfig {
  /** 选项展示类型 */
  kind: string;
  /** 选项数据源类型 */
  source_type: string;
  /** 选项数据源值 */
  source_value: string;
  /** 选项显示字段 */
  label_field: string;
  /** 选项取值字段 */
  value_field: string;
  /** 树形选项父级字段 */
  parent_field: string;
  /** 开关开启值 */
  active_value: string;
  /** 开关关闭值 */
  inactive_value: string;
  /** 树形选项是否懒加载 */
  lazy: boolean;
}

/** Admin代码生成字段服务 */
export interface CodeGenColumnService {
  /** 查询代码生成字段配置 */
  ListCodeGenColumn(request: ListCodeGenColumnRequest): Promise<ListCodeGenColumnResponse>;
  /** 查询数据库表字段列表 */
  ListCodeGenDatabaseColumn(request: ListCodeGenDatabaseColumnRequest): Promise<ListCodeGenDatabaseColumnResponse>;
  /** 保存代码生成字段配置 */
  SaveCodeGenColumn(request: SaveCodeGenColumnRequest): Promise<Empty>;
}
