// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/code_gen_proto.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** 代码生成Proto接口配置查询条件 */
export interface ListCodeGenProtoRequest {
  /** 代码生成表配置ID */
  table_id: number;
}

/** 代码生成Proto接口配置查询响应 */
export interface ListCodeGenProtoResponse {
  /** 代码生成Proto接口检查列表 */
  code_gen_protos: CodeGenProtoCheck[];
}

/** 代码生成Proto接口配置保存条件 */
export interface SaveCodeGenProtoRequest {
  /** 代码生成表配置ID */
  table_id: number;
  /** 代码生成Proto接口配置列表 */
  code_gen_protos: CodeGenProto[];
}

/** 代码生成Proto接口配置 */
export interface CodeGenProto {
  /** 主键ID */
  id: number;
  /** 代码生成表配置ID */
  table_id: number;
  /** 触发来源 */
  trigger_type: string;
  /** 接口类型 */
  api_kind: string;
  /** 缺失时是否生成 */
  generate_when_missing: boolean;
  /** 接口类型配置 */
  config:
    | CodeGenProtoConfig
    | undefined;
  /** 排序 */
  sort: number;
}

/** 代码生成Proto接口检查项 */
export interface CodeGenProtoCheck {
  /** 代码生成表配置ID */
  table_id: number;
  /** 触发来源 */
  trigger_type: string;
  /** 接口类型 */
  api_kind: string;
  /** 目标实体名 */
  target_entity_name: string;
  /** 方法名 */
  method_name: string;
  /** Proto文件路径 */
  proto_file_path: string;
  /** 接口是否已存在 */
  exists: boolean;
  /** 缺失时是否生成 */
  generate_when_missing: boolean;
  /** 接口类型配置 */
  config:
    | CodeGenProtoConfig
    | undefined;
  /** 检查说明 */
  message: string;
  /** 排序 */
  sort: number;
  /** 方法中文描述 */
  method_comment: string;
  /** 服务名 */
  service_name: string;
  /** 服务描述 */
  service_comment: string;
}

/** 代码生成Proto接口类型配置 */
export interface CodeGenProtoConfig {
  /** 树接口父节点字段 */
  parent_column: string;
  /** 选项显示字段 */
  label_column: string;
  /** 选项值字段 */
  value_column: string;
  /** 状态字段 */
  status_column: string;
  /** 树形Option接口是否懒加载 */
  lazy: boolean;
}

/** Admin代码生成Proto接口配置服务 */
export interface CodeGenProtoService {
  /** 查询代码生成Proto接口配置 */
  ListCodeGenProto(request: ListCodeGenProtoRequest): Promise<ListCodeGenProtoResponse>;
  /** 保存代码生成Proto接口配置 */
  SaveCodeGenProto(request: SaveCodeGenProtoRequest): Promise<Empty>;
}
