// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/code_gen.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** 代码生成任务状态 */
export enum CodeGenTaskStatus {
  /** CODE_GEN_TASK_STATUS_UNSPECIFIED - 未指定代码生成任务状态。 */
  CODE_GEN_TASK_STATUS_UNSPECIFIED = 0,
  /** CODE_GEN_TASK_STATUS_PENDING - 等待执行。 */
  CODE_GEN_TASK_STATUS_PENDING = 1,
  /** CODE_GEN_TASK_STATUS_RUNNING - 正在执行。 */
  CODE_GEN_TASK_STATUS_RUNNING = 2,
  /** CODE_GEN_TASK_STATUS_SUCCEEDED - 执行成功。 */
  CODE_GEN_TASK_STATUS_SUCCEEDED = 3,
  /** CODE_GEN_TASK_STATUS_FAILED - 执行失败。 */
  CODE_GEN_TASK_STATUS_FAILED = 4,
}

/** 代码生成步骤状态 */
export enum CodeGenTaskStepStatus {
  /** CODE_GEN_TASK_STEP_STATUS_UNSPECIFIED - 未指定代码生成步骤状态。 */
  CODE_GEN_TASK_STEP_STATUS_UNSPECIFIED = 0,
  /** CODE_GEN_TASK_STEP_STATUS_PENDING - 等待执行。 */
  CODE_GEN_TASK_STEP_STATUS_PENDING = 1,
  /** CODE_GEN_TASK_STEP_STATUS_RUNNING - 正在执行。 */
  CODE_GEN_TASK_STEP_STATUS_RUNNING = 2,
  /** CODE_GEN_TASK_STEP_STATUS_SUCCEEDED - 执行成功。 */
  CODE_GEN_TASK_STEP_STATUS_SUCCEEDED = 3,
  /** CODE_GEN_TASK_STEP_STATUS_FAILED - 执行失败。 */
  CODE_GEN_TASK_STEP_STATUS_FAILED = 4,
  /** CODE_GEN_TASK_STEP_STATUS_SKIPPED - 无需处理。 */
  CODE_GEN_TASK_STEP_STATUS_SKIPPED = 5,
}

/** 查询代码生成任务条件 */
export interface GetCodeGenTaskRequest {
  /** 生成任务ID */
  task_id: string;
}

/** 代码生成任务进度 */
export interface CodeGenTask {
  /** 生成任务ID */
  task_id: string;
  /** 任务状态 */
  status: CodeGenTaskStatus;
  /** 步骤总数 */
  total_steps: number;
  /** 已完成步骤数 */
  completed_steps: number;
  /** 当前生成表名 */
  current_table_name: string;
  /** 任务结果说明 */
  message: string;
  /** 生成对象进度列表 */
  tables: CodeGenTaskTable[];
  /** 任务创建时间 */
  created_at: string;
  /** 任务完成时间 */
  finished_at: string;
}

/** 预览代码生成条件 */
export interface PreviewCodeGenRequest {
  /** 代码生成表配置ID */
  table_id: number;
  /** 本次生成输出路径 */
  output_paths: CodeGenOutputPaths | undefined;
}

/** 预览代码生成响应 */
export interface PreviewCodeGenResponse {
  /** 预览文件列表 */
  files: CodeGenPreviewFile[];
  /** 本次生效输出路径 */
  output_paths:
    | CodeGenOutputPaths
    | undefined;
  /** 正式生成前必须补齐的翻译配置 */
  missing_i18ns: string[];
}

/** 启动代码生成任务条件 */
export interface StartCodeGenTaskRequest {
  /** 代码生成表配置ID列表 */
  table_ids: number[];
}

/** 启动代码生成任务响应 */
export interface StartCodeGenTaskResponse {
  /** 生成任务ID */
  task_id: string;
}

/** 还原代码生成结果条件 */
export interface RestoreCodeGenRequest {
  /** 代码生成表配置ID列表 */
  table_ids: number[];
}

/** 代码生成任务步骤 */
export interface CodeGenTaskStep {
  /** 步骤ID */
  id: string;
  /** 步骤名称 */
  label: string;
  /** 步骤类型 */
  kind: string;
  /** 文件路径 */
  path: string;
  /** 步骤状态 */
  status: CodeGenTaskStepStatus;
  /** 步骤结果说明 */
  message: string;
  /** 命令输出 */
  output: string;
}

/** 单个生成对象任务进度 */
export interface CodeGenTaskTable {
  /** 代码生成表配置ID */
  table_id: number;
  /** 业务表名 */
  table_name: string;
  /** 生成对象任务状态 */
  status: CodeGenTaskStatus;
  /** 步骤总数 */
  total_steps: number;
  /** 已完成步骤数 */
  completed_steps: number;
  /** 生成对象结果说明 */
  message: string;
  /** 生成步骤列表 */
  steps: CodeGenTaskStep[];
}

/** 代码生成预览文件 */
export interface CodeGenPreviewFile {
  /** 文件路径 */
  path: string;
  /** 处理动作 */
  action: string;
  /** 文件内容 */
  content: string;
  /** 文件是否已存在 */
  exists: boolean;
  /** 处理说明 */
  message: string;
}

/** 代码生成临时输出路径 */
export interface CodeGenOutputPaths {
  /** Proto文件路径 */
  proto_file_path: string;
  /** 后端Biz文件路径 */
  backend_biz_file_path: string;
  /** 后端Service文件路径 */
  backend_service_file_path: string;
  /** 前端API文件路径 */
  frontend_api_file_path: string;
  /** 前端页面文件路径 */
  frontend_page_file_path: string;
}

/** Admin代码生成服务 */
export interface CodeGenService {
  /** 查询代码生成任务进度 */
  GetCodeGenTask(request: GetCodeGenTaskRequest): Promise<CodeGenTask>;
  /** 预览代码生成文件 */
  PreviewCodeGen(request: PreviewCodeGenRequest): Promise<PreviewCodeGenResponse>;
  /** 启动代码生成任务 */
  StartCodeGenTask(request: StartCodeGenTaskRequest): Promise<StartCodeGenTaskResponse>;
  /** 还原代码生成结果 */
  RestoreCodeGen(request: RestoreCodeGenRequest): Promise<Empty>;
}
