// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/code_gen_table.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";
import type { CodeGenLocaleConfig } from "./base_i18n";

/** 代码生成表状态。 */
export enum CodeGenTableStatus {
  /** CODE_GEN_TABLE_STATUS_UNSPECIFIED - 未指定代码生成表状态。 */
  CODE_GEN_TABLE_STATUS_UNSPECIFIED = 0,
  /** CODE_GEN_TABLE_STATUS_DRAFT - 草稿。 */
  CODE_GEN_TABLE_STATUS_DRAFT = 1,
  /** CODE_GEN_TABLE_STATUS_GENERATED - 已生成。 */
  CODE_GEN_TABLE_STATUS_GENERATED = 2,
  /** CODE_GEN_TABLE_STATUS_DISABLED - 停用。 */
  CODE_GEN_TABLE_STATUS_DISABLED = 3,
}

/** 代码生成表配置分页查询条件 */
export interface PageCodeGenTableRequest {
  /** 业务表名 */
  name?:
    | string
    | undefined;
  /** 业务模块 */
  business_module?:
    | string
    | undefined;
  /** 页面类型 */
  page_type?:
    | string
    | undefined;
  /** 状态：枚举【CodeGenTableStatus】，1草稿 2已生成 3停用 */
  status?:
    | CodeGenTableStatus
    | undefined;
  /** 数据源名称 */
  source_name: string;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 代码生成表配置分页响应 */
export interface PageCodeGenTableResponse {
  /** 代码生成表配置列表 */
  code_gen_tables: CodeGenTable[];
  /** 总数 */
  total: number;
}

/** 数据库表列表查询条件 */
export interface ListCodeGenDatabaseTableRequest {
  /** 数据源名称 */
  source_name: string;
}

/** 数据库表列表响应 */
export interface ListCodeGenDatabaseTableResponse {
  /** 数据库表列表 */
  tables: CodeGenDatabaseTable[];
}

/** 代码生成表配置详情查询条件 */
export interface GetCodeGenTableRequest {
  /** 主键ID */
  id: number;
}

/** 代码生成表配置表单 */
export interface CodeGenTableForm {
  /** 主键ID */
  id: number;
  /** 业务表名 */
  name: string;
  /** 业务表描述 */
  comment: string;
  /** 业务模块 */
  business_module: string;
  /** 父级菜单ID */
  parent_menu_id: number;
  /** 页面类型：normal普通表格 tree树形表格 tree_lazy树形懒加载表格 left_tree左树右表 */
  page_type: string;
  /** 树形表格父节点字段 */
  parent_column: string;
  /** 树节点显示字段 */
  tree_label_column: string;
  /** 左树配置 */
  left_tree_config:
    | CodeGenLeftTreeConfig
    | undefined;
  /** 是否生成后端 */
  gen_backend: boolean;
  /** 是否生成前端 */
  gen_frontend: boolean;
  /** 是否同步菜单和接口权限 */
  gen_sql: boolean;
  /** 状态：枚举【CodeGenTableStatus】，1草稿 2已生成 3停用 */
  status: CodeGenTableStatus;
  /** 备注 */
  remark: string;
  /** 按语言区域索引的表级国际化配置 */
  i18n_config: Map<string, CodeGenLocaleConfig>;
  /** 数据源名称 */
  source_name: string;
}

export interface CodeGenTableForm_I18nConfigEntry {
  key: string;
  value: CodeGenLocaleConfig | undefined;
}

/** 代码生成表配置创建条件 */
export interface CreateCodeGenTableRequest {
  /** 代码生成表配置表单 */
  code_gen_table: CodeGenTableForm | undefined;
}

/** 代码生成表配置更新条件 */
export interface UpdateCodeGenTableRequest {
  /** 主键ID */
  id: number;
  /** 代码生成表配置表单 */
  code_gen_table: CodeGenTableForm | undefined;
}

/** 代码生成表配置删除条件 */
export interface DeleteCodeGenTableRequest {
  /** 代码生成表配置ID列表，多个用逗号分隔 */
  ids: string;
}

/** 数据库表元数据 */
export interface CodeGenDatabaseTable {
  /** 数据库表名 */
  name: string;
  /** 业务表描述 */
  comment: string;
  /** 是否已被选择 */
  disabled: boolean;
}

/** 代码生成表配置 */
export interface CodeGenTable {
  /** 主键ID */
  id: number;
  /** 业务表名 */
  name: string;
  /** 业务表描述 */
  comment: string;
  /** 业务模块 */
  business_module: string;
  /** 页面类型 */
  page_type: string;
  /** 状态：枚举【CodeGenTableStatus】，1草稿 2已生成 3停用 */
  status: CodeGenTableStatus;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 是否可以还原生成结果 */
  restore_available: boolean;
  /** 按语言区域索引的表级国际化配置 */
  i18n_config: Map<string, CodeGenLocaleConfig>;
  /** 数据源名称 */
  source_name: string;
}

export interface CodeGenTable_I18nConfigEntry {
  key: string;
  value: CodeGenLocaleConfig | undefined;
}

/** 左树右表页面配置 */
export interface CodeGenLeftTreeConfig {
  /** 左树数据表名 */
  table_name: string;
  /** 左树筛选当前表字段 */
  filter_column: string;
  /** 左树父节点字段 */
  parent_column: string;
  /** 左树显示字段 */
  label_column: string;
  /** 左树值字段 */
  value_column: string;
  /** 左树描述 */
  comment: string;
  /** 左树是否懒加载 */
  lazy: boolean;
}

/** Admin代码生成表配置服务 */
export interface CodeGenTableService {
  /** 分页查询代码生成表配置 */
  PageCodeGenTable(request: PageCodeGenTableRequest): Promise<PageCodeGenTableResponse>;
  /** 查询数据库表列表 */
  ListCodeGenDatabaseTable(request: ListCodeGenDatabaseTableRequest): Promise<ListCodeGenDatabaseTableResponse>;
  /** 查询代码生成表配置 */
  GetCodeGenTable(request: GetCodeGenTableRequest): Promise<CodeGenTableForm>;
  /** 创建代码生成表配置 */
  CreateCodeGenTable(request: CreateCodeGenTableRequest): Promise<Empty>;
  /** 更新代码生成表配置 */
  UpdateCodeGenTable(request: UpdateCodeGenTableRequest): Promise<Empty>;
  /** 删除代码生成表配置 */
  DeleteCodeGenTable(request: DeleteCodeGenTableRequest): Promise<Empty>;
}
