// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/oauth_client.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseApi } from "./base_api";

/**
 * OauthClientCryptoType 定义开放授权客户端请求和响应使用的加密算法。
 * 生产环境仅允许具备完整性保护的 AES-GCM 或 SM4-GCM，历史 3DES 值已禁用。
 */
export enum OauthClientCryptoType {
  OAUTH_CLIENT_CRYPTO_TYPE_UNSPECIFIED = 0,
  OAUTH_CLIENT_CRYPTO_TYPE_SM4 = 1,
  OAUTH_CLIENT_CRYPTO_TYPE_AES = 2,
}

/** 可授权 API 选项查询条件。 */
export interface OptionOauthClientApiRequest {
}

/** 可授权 API 选项响应。 */
export interface OptionOauthClientApiResponse {
  /** 可授权的开发接口列表 */
  base_apis: BaseApi[];
}

/** 开放授权客户端分页查询条件。 */
export interface PageOauthClientRequest {
  /** 客户端名称 */
  client_name?:
    | string
    | undefined;
  /** 客户端状态 */
  status?:
    | Status
    | undefined;
  /** 绑定租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 开放授权客户端分页响应。 */
export interface PageOauthClientResponse {
  /** 客户端列表 */
  oauth_clients: OauthClient[];
  /** 总数 */
  total: number;
}

/** 开放授权客户端查询条件。 */
export interface GetOauthClientRequest {
  /** 客户端ID */
  id: number;
}

/** 开放授权客户端凭据查询条件。 */
export interface GetOauthClientCredentialsRequest {
  /** 客户端ID */
  id: number;
}

/** 开放授权客户端凭据轮换条件。 */
export interface RotateOauthClientCredentialsRequest {
  /** 客户端ID */
  id: number;
}

/** 创建开放授权客户端请求。 */
export interface CreateOauthClientRequest {
  /** 客户端表单 */
  oauth_client: OauthClientForm | undefined;
}

/** 更新开放授权客户端请求。 */
export interface UpdateOauthClientRequest {
  /** 客户端表单 */
  oauth_client: OauthClientForm | undefined;
}

/** 删除开放授权客户端请求。 */
export interface DeleteOauthClientRequest {
  /** 客户端ID列表 */
  id: string;
}

/** 设置开放授权客户端状态请求。 */
export interface SetOauthClientStatusRequest {
  /** 客户端ID */
  id: number;
  /** 状态 */
  status: Status;
}

/** 开放授权客户端表单。 */
export interface OauthClientForm {
  /** 客户端ID */
  id: number;
  /** 绑定租户ID */
  tenant_id: number;
  /** 客户端名称 */
  client_name: string;
  /** 协议加密类型 */
  crypto_type: OauthClientCryptoType;
  /** IP白名单 */
  ip_whitelist: string;
  /** 允许访问的 API operation 列表 */
  api: string[];
  /** 状态 */
  status: Status;
}

/** 开放授权客户端非敏感信息。 */
export interface OauthClient {
  /** 客户端ID */
  id: number;
  /** 客户端标识 */
  client_id: string;
  /** 客户端名称 */
  client_name: string;
  /** 绑定租户ID */
  tenant_id: number;
  /** 协议加密类型 */
  crypto_type: OauthClientCryptoType;
  /** IP白名单 */
  ip_whitelist: string;
  /** 允许访问的 API operation 列表 */
  api: string[];
  /** 状态 */
  status: Status;
}

/** 开放授权客户端凭据元数据；敏感密钥字段始终为空，仅保留协议类型和客户端标识。 */
export interface OauthClientCredentials {
  /** 客户端标识 */
  client_id: string;
  /** 客户端密钥 */
  client_secret: string;
  /** 协议加密类型 */
  crypto_type: OauthClientCryptoType;
  /** 协议加密密钥 */
  crypto_key: string;
}

/** Admin开放授权客户端管理服务。 */
export interface OauthClientService {
  /** 查询可授权的开发接口选项。 */
  OptionOauthClientApi(request: OptionOauthClientApiRequest): Promise<OptionOauthClientApiResponse>;
  /** 分页查询开放授权客户端。 */
  PageOauthClient(request: PageOauthClientRequest): Promise<PageOauthClientResponse>;
  /** 查询开放授权客户端详情。 */
  GetOauthClient(request: GetOauthClientRequest): Promise<OauthClientForm>;
  /** 查询客户端凭据元数据；客户端密钥和协议密钥不会通过接口回传。 */
  GetOauthClientCredentials(request: GetOauthClientCredentialsRequest): Promise<OauthClientCredentials>;
  /** 轮换客户端密钥并一次性返回新凭据。 */
  RotateOauthClientCredentials(request: RotateOauthClientCredentialsRequest): Promise<OauthClientCredentials>;
  /** 创建开放授权客户端。 */
  CreateOauthClient(request: CreateOauthClientRequest): Promise<Empty>;
  /** 更新开放授权客户端。 */
  UpdateOauthClient(request: UpdateOauthClientRequest): Promise<Empty>;
  /** 删除开放授权客户端。 */
  DeleteOauthClient(request: DeleteOauthClientRequest): Promise<Empty>;
  /** 设置开放授权客户端状态。 */
  SetOauthClientStatus(request: SetOauthClientStatusRequest): Promise<Empty>;
}
