// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/ops_monitoring.proto

/* eslint-disable */

/** 运行信息查询条件。 */
export interface GetOpsRuntimeRequest {
}

/** 流量查询条件。 */
export interface GetOpsTrafficRequest {
  /** 统计窗口，单位分钟 */
  window_minutes: number;
}

/** 服务状态查询条件。 */
export interface GetOpsServicesRequest {
}

/** 存储状态查询条件。 */
export interface GetOpsStorageRequest {
}

/** 接口查询条件。 */
export interface GetOpsEndpointsRequest {
  /** 统计窗口，单位分钟 */
  window_minutes: number;
}

/** 实例查询条件。 */
export interface GetOpsNodesRequest {
}

/** 告警查询条件。 */
export interface GetOpsAlertsRequest {
  /** 统计窗口，单位分钟 */
  window_minutes: number;
}

/** 流量响应。 */
export interface OpsTrafficResponse {
  /** 采集时间，RFC3339格式 */
  collected_at: string;
  /** 统计窗口，单位分钟 */
  window_minutes: number;
  /** 请求流量摘要 */
  traffic:
    | OpsTraffic
    | undefined;
  /** 请求流量趋势 */
  points: OpsTrafficPoint[];
}

/** 服务状态响应。 */
export interface OpsServicesResponse {
  /** 采集时间，RFC3339格式 */
  collected_at: string;
  /** 服务依赖状态 */
  services: OpsServiceStatus[];
}

/** 存储状态响应。 */
export interface OpsStorageResponse {
  /** 采集时间，RFC3339格式 */
  collected_at: string;
  /** 数据存储状态 */
  storage: OpsStorage[];
}

/** 接口摘要响应。 */
export interface OpsEndpointsResponse {
  /** 采集时间，RFC3339格式 */
  collected_at: string;
  /** 统计窗口，单位分钟 */
  window_minutes: number;
  /** 接口请求摘要 */
  endpoints: OpsEndpoint[];
}

/** 实例状态响应。 */
export interface OpsNodesResponse {
  /** 采集时间，RFC3339格式 */
  collected_at: string;
  /** 实例资源状态 */
  nodes: OpsNode[];
}

/** 告警响应。 */
export interface OpsAlertsResponse {
  /** 采集时间，RFC3339格式 */
  collected_at: string;
  /** 统计窗口，单位分钟 */
  window_minutes: number;
  /** 近期告警事件 */
  alerts: OpsAlert[];
}

/** 当前进程运行信息。 */
export interface OpsRuntime {
  /** 服务名称 */
  service_name: string;
  /** 服务版本 */
  version: string;
  /** 主机名 */
  hostname: string;
  /** 运行环境 */
  environment: string;
  /** Go运行时版本 */
  go_version: string;
  /** 操作系统 */
  os: string;
  /** 系统架构 */
  arch: string;
  /** 启动时间，RFC3339格式 */
  start_time: string;
  /** 运行时长，单位秒 */
  uptime_seconds: number;
  /** 当前协程数量 */
  goroutines: number;
  /** 当前堆内存，单位字节 */
  memory_alloc_bytes: number;
  /** 进程向系统申请的内存，单位字节 */
  memory_sys_bytes: number;
}

/** 请求流量摘要。 */
export interface OpsTraffic {
  /** 每秒请求数 */
  qps: number;
  /** P95响应延迟，单位毫秒 */
  p95_latency_ms: number;
  /** 错误率，百分比 */
  error_rate: number;
  /** 可用性，百分比 */
  availability: number;
  /** 窗口内请求数 */
  request_count: number;
}

/** 请求流量趋势点。 */
export interface OpsTrafficPoint {
  /** 时间点，RFC3339格式 */
  at: string;
  /** 时间点每秒请求数 */
  qps: number;
  /** 时间点P95延迟，单位毫秒 */
  p95_latency_ms: number;
  /** QPS柱状图比例 */
  qps_percent: number;
  /** 延迟柱状图比例 */
  latency_percent: number;
}

/** 服务或外部依赖状态。 */
export interface OpsServiceStatus {
  /** 服务名称 */
  name: string;
  /** 服务地址 */
  address: string;
  /** 状态：正常、未配置或异常 */
  status: string;
  /** 状态说明 */
  message: string;
  /** 探测耗时，单位毫秒 */
  latency_ms: number;
}

/** 数据存储状态。 */
export interface OpsStorage {
  /** 存储名称 */
  name: string;
  /** 存储简称 */
  short_name: string;
  /** 存储地址 */
  address: string;
  /** 状态：正常、未配置或异常 */
  status: string;
  /** 存储指标 */
  metrics: OpsMetric[];
  /** 容量指标名称 */
  capacity_label: string;
  /** 容量使用百分比 */
  capacity: number;
}

/** 存储或实例指标。 */
export interface OpsMetric {
  /** 指标名称 */
  label: string;
  /** 指标值 */
  value: string;
}

/** 接口请求摘要。 */
export interface OpsEndpoint {
  /** 接口路径 */
  route: string;
  /** 每秒请求数 */
  qps: number;
  /** P95响应延迟，单位毫秒 */
  p95_latency_ms: number;
  /** 错误率，百分比 */
  error_rate: number;
  /** 接口状态 */
  status: string;
}

/** 实例资源状态。 */
export interface OpsNode {
  /** 实例名称 */
  name: string;
  /** 实例资源指标 */
  metrics: OpsNodeMetric[];
}

/** 实例资源指标。 */
export interface OpsNodeMetric {
  /** 指标名称 */
  label: string;
  /** 指标使用百分比 */
  value: number;
  /** 当前已用容量，单位字节 */
  used_bytes: number;
  /** 总容量，单位字节 */
  total_bytes: number;
}

/** 告警事件。 */
export interface OpsAlert {
  /** 告警标题 */
  title: string;
  /** 告警详情 */
  detail: string;
  /** 告警时间，RFC3339格式 */
  at: string;
  /** 告警状态 */
  status: string;
}

/** Admin运维监控服务。 */
export interface OpsMonitoringService {
  /** 查询当前进程运行信息。 */
  GetOpsRuntime(request: GetOpsRuntimeRequest): Promise<OpsRuntime>;
  /** 查询请求流量与延迟趋势。 */
  GetOpsTraffic(request: GetOpsTrafficRequest): Promise<OpsTrafficResponse>;
  /** 查询服务和外部依赖状态。 */
  GetOpsServices(request: GetOpsServicesRequest): Promise<OpsServicesResponse>;
  /** 查询数据库和缓存状态。 */
  GetOpsStorage(request: GetOpsStorageRequest): Promise<OpsStorageResponse>;
  /** 查询接口请求摘要。 */
  GetOpsEndpoints(request: GetOpsEndpointsRequest): Promise<OpsEndpointsResponse>;
  /** 查询实例资源状态。 */
  GetOpsNodes(request: GetOpsNodesRequest): Promise<OpsNodesResponse>;
  /** 查询窗口内告警事件。 */
  GetOpsAlerts(request: GetOpsAlertsRequest): Promise<OpsAlertsResponse>;
}
