// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/runtime_log.proto

/* eslint-disable */

/** 历史日志文件列表查询条件。 */
export interface ListRuntimeLogFilesRequest {
}

/** 历史日志文件列表响应。 */
export interface ListRuntimeLogFilesResponse {
  /** 历史日志文件列表 */
  files: RuntimeLogFile[];
}

/** 历史日志文件信息。 */
export interface RuntimeLogFile {
  /** 服务端签发的日志文件标识 */
  file_id: string;
  /** 日志文件名称 */
  name: string;
  /** 日志文件大小，单位字节 */
  size_bytes: number;
  /** 最后修改时间，RFC3339格式 */
  modified_at: string;
  /** 是否为Gzip压缩文件 */
  is_compressed: boolean;
  /** 是否为当前活动日志文件 */
  is_active: boolean;
}

/** 历史日志文件读取条件。 */
export interface ReadRuntimeLogFileRequest {
  /** 服务端签发的日志文件标识 */
  file_id: string;
  /** 向更早日志翻页的不透明游标，留空时从文件尾部读取 */
  cursor: string;
  /** 单次读取条数，0使用默认值，最大500 */
  limit: number;
  /** 日志内容搜索关键字 */
  keyword: string;
  /** 日志级别筛选列表 */
  levels: string[];
}

/** 历史日志文件读取响应。 */
export interface ReadRuntimeLogFileResponse {
  /** 按时间正序排列的日志条目 */
  entries: RuntimeLogEntry[];
  /** 继续读取更早日志的不透明游标 */
  next_cursor: string;
  /** 是否还有更早日志 */
  has_more: boolean;
  /** 读取期间日志文件是否已滚动或截断 */
  file_changed: boolean;
}

/** 实时或历史日志条目。 */
export interface RuntimeLogEntry {
  /** 当前进程内的日志序号，历史文件日志为空 */
  sequence: string;
  /** 日志时间 */
  timestamp: string;
  /** 日志级别 */
  level: string;
  /** 日志来源 */
  source: string;
  /** 日志消息 */
  message: string;
  /** 可直接展示的纯文本日志行 */
  line: string;
  /** 日志行是否因长度限制被截断 */
  is_truncated: boolean;
}

/** 实时控制台开启条件。 */
export interface OpenRuntimeConsoleRequest {
  /** 首次返回的最近日志条数，0使用默认值，最大500 */
  backlog_limit: number;
}

/** 实时控制台开启响应。 */
export interface OpenRuntimeConsoleResponse {
  /** SSE业务流标识 */
  stream: string;
  /** 当前用户专属SSE频道标识 */
  channel_id: string;
  /** 频道过期时间，RFC3339格式 */
  expires_at: string;
  /** 当前服务实例标识 */
  instance_id: string;
  /** 当前进程最新日志序号 */
  latest_sequence: string;
  /** 当前进程最近日志 */
  entries: RuntimeLogEntry[];
}

/** 实时控制台丢失消息提示。 */
export interface RuntimeLogGap {
  /** 本次丢弃的日志条数 */
  dropped_count: number;
  /** 发生丢弃时的最新日志序号 */
  latest_sequence: string;
}

/** 历史日志文件下载条件。 */
export interface DownloadRuntimeLogFileRequest {
  /** 服务端签发的日志文件标识 */
  file_id: string;
}
