// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/auth.proto

/* eslint-disable */
import type { PasswordCrypto, StringValues } from "../../../common/v1/types";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseUserIDType } from "../../common/v1/common";
import type { BaseMenuType } from "./common";

/** 登录用户菜单树查询参数 */
export interface TreeUserMenuRequest {
}

/** Route树响应 */
export interface TreeRouteResponse {
  /** 路由列表 */
  routes: RouteItem[];
}

/** 登录用户按钮列表查询参数 */
export interface ListUserButtonRequest {
}

/** 获取登录用户信息请求参数 */
export interface GetUserInfoRequest {
}

/** 用户信息表单 */
export interface UserInfoForm {
  /** 用户账号 */
  user_name: string;
  /** 用户昵称 */
  nick_name: string;
  /** 手机号 */
  phone: string;
  /** 邮箱 */
  email: string;
  /** 证件类型：枚举【BaseUserIDType】 */
  id_type: BaseUserIDType;
  /** 证件号 */
  id_code: string;
  /** 头像 */
  avatar: string;
  /** 角色编号 */
  role_code: string;
  /** 角色名称 */
  role_name: string;
  /** 部门名称 */
  dept_name: string;
  /** 租户编码 */
  tenant_code: string;
  /** 租户名称 */
  tenant_name: string;
}

/** 获取个人中心用户信息请求参数 */
export interface GetUserProfileRequest {
}

/** 用户资料表单 */
export interface UserProfileForm {
  /** 用户名 */
  user_name: string;
  /** 昵称 */
  nick_name: string;
  /** 头像URL */
  avatar: string;
  /** 性别 */
  gender: number;
  /** 手机号 */
  phone: string;
  /** 邮箱 */
  email: string;
  /** 证件类型：枚举【BaseUserIDType】 */
  id_type: BaseUserIDType;
  /** 证件号 */
  id_code: string;
  /** 角色名 */
  role_name: string;
  /** 部门名 */
  dept_name: string;
  /** 创建时间 */
  created_at: string;
}

/** 更新个人中心密码请求参数 */
export interface UpdateUserPasswordRequest {
  /** 个人中心密码 */
  user_password: UserPasswordForm | undefined;
}

/** 更新个人中心手机号请求参数 */
export interface UpdateUserPhoneRequest {
  /** 个人中心手机号 */
  user_phone: UserPhoneForm | undefined;
}

/** 更新个人中心用户信息请求参数 */
export interface UpdateUserProfileRequest {
  /** 个人中心用户信息 */
  user_profile: UserProfileForm | undefined;
}

/** 发送手机号验证码请求参数 */
export interface SendPhoneCodeRequest {
  /** 手机号 */
  phone: string;
}

/** Route项 */
export interface RouteItem {
  /** 路由路径 */
  path?:
    | string
    | undefined;
  /** 重定向地址 */
  redirect?:
    | string
    | undefined;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name?:
    | string
    | undefined;
  /** 指向的组件 */
  component?:
    | string
    | undefined;
  /** 路由元信息 */
  meta?:
    | RouteMeta
    | undefined;
  /** 菜单类型 */
  type: BaseMenuType;
  /** 子节点树 */
  children: RouteItem[];
}

/** Route元信息 */
export interface RouteMeta {
  /** 菜单标题 */
  title?:
    | string
    | undefined;
  /** 菜单图标 */
  icon?:
    | string
    | undefined;
  /** 【目录】只有一个子路由是否始终显示 */
  always_show?:
    | boolean
    | undefined;
  /** 是否隐藏(true-是 false-否) */
  hidden?:
    | boolean
    | undefined;
  /** 【菜单】是否开启页面缓存 */
  keep_alive?:
    | boolean
    | undefined;
  /** 【菜单】是否全屏(示例：数据大屏页面) */
  full?:
    | boolean
    | undefined;
  /** 【菜单】是否固定在标签页中(首页通常是固定项) */
  affix?:
    | boolean
    | undefined;
  /** 参数 */
  params: RouteParams[];
}

/** Route参数 */
export interface RouteParams {
  /** key */
  key?:
    | string
    | undefined;
  /** value */
  value?: string | undefined;
}

/** 用户密码表单 */
export interface UserPasswordForm {
  /** 原密码 */
  old_pwd:
    | PasswordCrypto
    | undefined;
  /** 新密码 */
  new_pwd: PasswordCrypto | undefined;
}

/** 用户手机号表单 */
export interface UserPhoneForm {
  /** 手机号 */
  phone: string;
  /** 验证码 */
  code: string;
}

/** Admin用户登录认证服务 */
export interface AuthService {
  /** 查询已经登录的用户菜单树 */
  TreeUserMenu(request: TreeUserMenuRequest): Promise<TreeRouteResponse>;
  /** 查询已经登录的用户按钮列表 */
  ListUserButton(request: ListUserButtonRequest): Promise<StringValues>;
  /** 获取已经登录的用户的数据 */
  GetUserInfo(request: GetUserInfoRequest): Promise<UserInfoForm>;
  /** 获取个人中心用户信息 */
  GetUserProfile(request: GetUserProfileRequest): Promise<UserProfileForm>;
  /** 修改个人中心密码 */
  UpdateUserPassword(request: UpdateUserPasswordRequest): Promise<Empty>;
  /** 修改个人中心手机号 */
  UpdateUserPhone(request: UpdateUserPhoneRequest): Promise<Empty>;
  /** 修改个人中心用户信息 */
  UpdateUserProfile(request: UpdateUserProfileRequest): Promise<Empty>;
  /** 发送手机号验证码 */
  SendPhoneCode(request: SendPhoneCodeRequest): Promise<Empty>;
}
