// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_i18n.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";

/** 统一翻译表目标类型，和 base_i18n.target_type 的值一一对应。 */
export enum I18nTargetType {
  /** I18N_TARGET_TYPE_UNSPECIFIED - 未指定统一翻译表目标类型。 */
  I18N_TARGET_TYPE_UNSPECIFIED = 0,
  /** I18N_TARGET_TYPE_BASE_CONFIG_VALUE - 系统配置值。 */
  I18N_TARGET_TYPE_BASE_CONFIG_VALUE = 1,
  /** I18N_TARGET_TYPE_BASE_CONFIG_NAME - 系统配置名称。 */
  I18N_TARGET_TYPE_BASE_CONFIG_NAME = 2,
  /** I18N_TARGET_TYPE_BASE_DICT_NAME - 字典名称。 */
  I18N_TARGET_TYPE_BASE_DICT_NAME = 3,
  /** I18N_TARGET_TYPE_BASE_DICT_ITEM_LABEL - 字典项标签。 */
  I18N_TARGET_TYPE_BASE_DICT_ITEM_LABEL = 4,
  /** I18N_TARGET_TYPE_BASE_MENU_META_TITLE - 菜单标题。 */
  I18N_TARGET_TYPE_BASE_MENU_META_TITLE = 5,
  /** I18N_TARGET_TYPE_BASE_JOB_NAME - 定时任务名称。 */
  I18N_TARGET_TYPE_BASE_JOB_NAME = 6,
  /** I18N_TARGET_TYPE_BASE_MIGRATION_DESCRIPTION - 数据库迁移说明。 */
  I18N_TARGET_TYPE_BASE_MIGRATION_DESCRIPTION = 7,
}

/** 翻译单个文本请求。 */
export interface DraftBaseI18nRequest {
  /** 待翻译文本 */
  source: string;
  /** 目标语言区域，不传时翻译所有启用的非主语言 */
  locale?: string | undefined;
}

/** 翻译单个文本响应。 */
export interface DraftBaseI18nResponse {
  /** 翻译结果 */
  i18ns: DraftBaseI18nItem[];
}

/** 翻译单个文本响应。 */
export interface DraftBaseI18nItem {
  /** 目标语言区域 */
  locale: string;
  /** 翻译文本 */
  i18n: string;
}

/** 修改单个翻译信息请求。 */
export interface UpdateBaseI18nRequest {
  /** 翻译记录ID，大于零时优先按ID更新；ID不存在时根据目标信息更新或新增 */
  id: number;
  /** 翻译目标类型，ID为零时用于查询或新增 */
  target_type: I18nTargetType;
  /** 目标资源ID，ID为零时用于查询或新增 */
  target_id: number;
  /** 目标语言区域，ID为零时用于查询或新增 */
  locale: string;
  /** 翻译文本 */
  name: string;
}

/** 国际化翻译信息 */
export interface BaseI18n {
  /** 翻译记录ID */
  id: number;
  /** 翻译目标类型 */
  target_type: I18nTargetType;
  /** 目标资源ID */
  target_id: number;
  /** 语言区域 */
  locale: string;
  /** 翻译文本 */
  name: string;
}

/** 代码生成单语言国际化配置 */
export interface CodeGenLocaleConfig {
  /** 业务或字段描述 */
  comment: string;
  /** 左树描述 */
  left_tree_comment: string;
}

/** Admin国际化翻译信息服务。 */
export interface BaseI18nService {
  /** 翻译单个文本。 */
  DraftBaseI18n(request: DraftBaseI18nRequest): Promise<DraftBaseI18nResponse>;
  /** 修改国际化翻译信息 */
  UpdateBaseI18n(request: UpdateBaseI18nRequest): Promise<Empty>;
}
