// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_tenant.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../../common/v1/common";
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";

/** 租户选项查询条件 */
export interface OptionBaseTenantRequest {
  /** 关键字 */
  keyword: string;
}

/** 租户分页查询条件 */
export interface PageBaseTenantRequest {
  /** 租户编号 */
  code: string;
  /** 租户名称 */
  name: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 租户分页响应 */
export interface PageBaseTenantResponse {
  /** 分页数据 */
  base_tenants: BaseTenant[];
  /** 总数 */
  total: number;
}

/** 查询租户请求参数 */
export interface GetBaseTenantRequest {
  /** 租户ID */
  id: number;
}

/** 创建租户请求参数 */
export interface CreateBaseTenantRequest {
  /** 租户表单 */
  base_tenant: BaseTenantForm | undefined;
}

/** 更新租户请求参数 */
export interface UpdateBaseTenantRequest {
  /** 租户表单 */
  base_tenant: BaseTenantForm | undefined;
}

/** 删除租户请求参数 */
export interface DeleteBaseTenantRequest {
  /** 租户ID列表 */
  id: string;
}

/** 设置租户状态请求参数 */
export interface SetBaseTenantStatusRequest {
  /** 租户ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 租户 */
export interface BaseTenant {
  /** 租户ID */
  id: number;
  /** 租户编号 */
  code: string;
  /** 租户名称 */
  name: string;
  /** 联系人 */
  contact_name: string;
  /** 联系电话 */
  contact_phone: string;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 是否禁止通过租户管理操作 */
  is_protected: boolean;
}

/** 租户表单 */
export interface BaseTenantForm {
  /** 租户ID */
  id: number;
  /** 租户编号 */
  code: string;
  /** 租户名称 */
  name: string;
  /** 联系人 */
  contact_name: string;
  /** 联系电话 */
  contact_phone: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 备注 */
  remark: string;
}

/** Admin租户管理服务 */
export interface BaseTenantService {
  /** 查询租户下拉选择 */
  OptionBaseTenant(request: OptionBaseTenantRequest): Promise<SelectOptionResponse>;
  /** 查询租户分页列表 */
  PageBaseTenant(request: PageBaseTenantRequest): Promise<PageBaseTenantResponse>;
  /** 查询租户 */
  GetBaseTenant(request: GetBaseTenantRequest): Promise<BaseTenantForm>;
  /** 创建租户 */
  CreateBaseTenant(request: CreateBaseTenantRequest): Promise<Empty>;
  /** 更新租户 */
  UpdateBaseTenant(request: UpdateBaseTenantRequest): Promise<Empty>;
  /** 删除租户 */
  DeleteBaseTenant(request: DeleteBaseTenantRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseTenantStatus(request: SetBaseTenantStatusRequest): Promise<Empty>;
}
