// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/base_dict.proto

/* eslint-disable */
import type { Status } from "../../../common/v1/enum";
import type { Empty } from "../../../google/protobuf/empty";
import type { BaseI18n } from "./base_i18n";

/** 字典选项查询条件 */
export interface OptionBaseDictRequest {
}

/** 字典选项响应 */
export interface OptionBaseDictResponse {
  /** 字典列表 */
  base_dicts: OptionBaseDictResponse_BaseDict[];
}

/** 字典项 */
export interface OptionBaseDictResponse_BaseDictItem {
  /** 字典项值 */
  value: string;
  /** 字典项标签 */
  label: string;
  /** 标签类型，用于前端样式展示（如success、warning等） */
  tag_type: string;
}

/** 字典 */
export interface OptionBaseDictResponse_BaseDict {
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 字典属性 */
  items: OptionBaseDictResponse_BaseDictItem[];
}

/** 字典分页查询条件 */
export interface PageBaseDictRequest {
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 字典分页响应 */
export interface PageBaseDictResponse {
  /** 分页数据 */
  base_dicts: BaseDict[];
  /** 总数 */
  total: number;
}

/** 查询字典请求参数 */
export interface GetBaseDictRequest {
  /** 字典ID */
  id: number;
}

/** 字典表单 */
export interface BaseDictForm {
  /** 字典ID */
  id: number;
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 非主语言翻译 */
  i18ns: BaseI18n[];
  /** 状态 */
  status: Status;
}

/** 创建字典请求参数 */
export interface CreateBaseDictRequest {
  /** 字典表单 */
  base_dict: BaseDictForm | undefined;
}

/** 更新字典请求参数 */
export interface UpdateBaseDictRequest {
  /** 字典表单 */
  base_dict: BaseDictForm | undefined;
}

/** 删除字典请求参数 */
export interface DeleteBaseDictRequest {
  /** 字典ID列表 */
  id: string;
}

/** 设置字典状态请求参数 */
export interface SetBaseDictStatusRequest {
  /** 字典ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 字典 */
export interface BaseDict {
  /** 字典ID */
  id: number;
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 状态 */
  status: Status;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 非主语言翻译 */
  i18ns: BaseI18n[];
}

/** Admin字典服务 */
export interface BaseDictService {
  /** 查询字典列表 */
  OptionBaseDict(request: OptionBaseDictRequest): Promise<OptionBaseDictResponse>;
  /** 查询字典分页列表 */
  PageBaseDict(request: PageBaseDictRequest): Promise<PageBaseDictResponse>;
  /** 查询字典 */
  GetBaseDict(request: GetBaseDictRequest): Promise<BaseDictForm>;
  /** 创建字典 */
  CreateBaseDict(request: CreateBaseDictRequest): Promise<Empty>;
  /** 更新字典 */
  UpdateBaseDict(request: UpdateBaseDictRequest): Promise<Empty>;
  /** 删除字典 */
  DeleteBaseDict(request: DeleteBaseDictRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseDictStatus(request: SetBaseDictStatusRequest): Promise<Empty>;
}
