// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/admin/v1/common.proto

/* eslint-disable */

/** 菜单类型。 */
export enum BaseMenuType {
  /** BASE_MENU_TYPE_UNSPECIFIED - 未指定菜单类型。 */
  BASE_MENU_TYPE_UNSPECIFIED = 0,
  /** BASE_MENU_TYPE_FOLDER - 目录。 */
  BASE_MENU_TYPE_FOLDER = 1,
  /** BASE_MENU_TYPE_MENU - 菜单。 */
  BASE_MENU_TYPE_MENU = 2,
  /** BASE_MENU_TYPE_BUTTON - 按钮。 */
  BASE_MENU_TYPE_BUTTON = 3,
  /** BASE_MENU_TYPE_EXT_LINK - 外部链接。 */
  BASE_MENU_TYPE_EXT_LINK = 4,
}
