// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package module

import (
	"github.com/liujitcn/kratos-admin/backend/adapter/kit"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/agent/model"
	biz2 "github.com/liujitcn/kratos-admin/backend/internal/biz/base"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/base/ai"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/base/oauthsecret"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/base/sessionregistry"
	biz3 "github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin/codegen"
	"github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin/logstream"
	sse2 "github.com/liujitcn/kratos-admin/backend/internal/biz/system/admin/sse"
	biz4 "github.com/liujitcn/kratos-admin/backend/internal/biz/system/app"
	"github.com/liujitcn/kratos-admin/backend/internal/config"
	data3 "github.com/liujitcn/kratos-admin/backend/internal/data"
	data2 "github.com/liujitcn/kratos-admin/backend/internal/data/gen/data"
	base2 "github.com/liujitcn/kratos-admin/backend/internal/server/base/v1"
	logmiddleware "github.com/liujitcn/kratos-admin/backend/internal/server/middleware/log"
	admin2 "github.com/liujitcn/kratos-admin/backend/internal/server/system/admin/v1"
	app2 "github.com/liujitcn/kratos-admin/backend/internal/server/system/app/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/service/base/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/service/system/admin/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/service/system/app/v1"
	"github.com/liujitcn/kratos-admin/backend/internal/task"
	admin3 "github.com/liujitcn/kratos-admin/backend/internal/task/system/admin"
	"github.com/liujitcn/kratos-core/biz"
	"github.com/liujitcn/kratos-core/job"
	"github.com/liujitcn/kratos-core/module"
	"github.com/liujitcn/kratos-core/queue"
	"github.com/liujitcn/kratos-core/resource/i18n"
	"github.com/liujitcn/kratos-core/resource/migration"
	"github.com/liujitcn/kratos-core/resource/openapi"
	"github.com/liujitcn/kratos-core/sse"
	configv1 "github.com/liujitcn/kratos-kit/api/gen/go/config/v1"
	engine2 "github.com/liujitcn/kratos-kit/auth/authn/engine"
	"github.com/liujitcn/kratos-kit/auth/authz/engine"
	"github.com/liujitcn/kratos-kit/auth/data"
	"github.com/liujitcn/kratos-kit/database/gorm"
)

// Injectors from wire.go:

// BuildModules 使用宿主共享的任务管理器装配 Admin 协议服务。
func BuildModules(migrations *migration.Migration, config2 *configv1.Bootstrap, databases map[string]*gorm.Client, baseCase *biz.BaseCase, authorizer engine.Engine, authenticator engine2.Authenticator, userToken *data.UserToken, jobRuntime *job.Job, sseRuntime *sse.SSE, catalog *i18n.I18n, openAPIRuntime *openapi.OpenAPI, redactResolver *kit.RedactPolicyResolver, progressManager *codegen.Manager) (module.Modules, func(), error) {
	dataData, err := data2.NewData(databases)
	if err != nil {
		return nil, nil, err
	}
	transaction := data2.NewTransaction(dataData)
	aiSessionRepository := data2.NewAiSessionRepository(dataData)
	aiMessageRepository := data2.NewAiMessageRepository(dataData)
	aiSessionCase := biz2.NewAiSessionCase(baseCase, transaction, aiSessionRepository, aiMessageRepository)
	baseUserRepository := data2.NewBaseUserRepository(dataData)
	baseUserCase := biz2.NewBaseUserCase(baseCase, baseUserRepository)
	ai_Model, err := config.ParseAIModel(config2)
	if err != nil {
		return nil, nil, err
	}
	responsesClient := model.NewResponsesClient(ai_Model)
	baseAPIRepository := data2.NewBaseAPIRepository(dataData)
	mcpCase, err := biz2.NewMcpCase(baseCase, baseAPIRepository, authorizer)
	if err != nil {
		return nil, nil, err
	}
	baseDeptRepository := data2.NewBaseDeptRepository(dataData)
	basePostRepository := data2.NewBasePostRepository(dataData)
	baseRoleRepository := data2.NewBaseRoleRepository(dataData)
	baseTenantRepository := data2.NewBaseTenantRepository(dataData)
	casbinRuleRepository := data2.NewCasbinRuleRepository(dataData)
	baseMenuRepository := data2.NewBaseMenuRepository(dataData)
	baseAPII18NRepository := data2.NewBaseAPII18NRepository(dataData)
	baseAPICase := biz3.NewBaseAPICase(baseCase, openAPIRuntime, catalog, baseAPIRepository, baseAPII18NRepository)
	casbinRuleCase, err := biz3.NewCasbinRuleCase(casbinRuleRepository, baseMenuRepository, baseRoleRepository, baseTenantRepository, baseAPICase, authorizer)
	if err != nil {
		return nil, nil, err
	}
	baseRoleCase := biz3.NewBaseRoleCase(baseCase, transaction, baseRoleRepository, baseTenantRepository, casbinRuleCase)
	baseDeptCase := biz3.NewBaseDeptCase(baseCase, baseDeptRepository)
	baseI18NRepository := data2.NewBaseI18NRepository(dataData)
	baseLanguageRepository := data2.NewBaseLanguageRepository(dataData)
	baseLanguageCase := biz3.NewBaseLanguageCase(baseCase, transaction, baseLanguageRepository)
	baseI18nCase := biz3.NewBaseI18nCase(baseCase, transaction, baseI18NRepository, baseLanguageCase)
	baseMenuCase := biz3.NewBaseMenuCase(baseCase, transaction, baseMenuRepository, baseRoleRepository, casbinRuleCase, baseI18nCase)
	bizBaseRoleCase := biz2.NewBaseRoleCase(baseCase, baseRoleRepository)
	bizBaseUserCase := biz3.NewBaseUserCase(baseCase, transaction, baseUserRepository, baseDeptRepository, basePostRepository, baseRoleCase, baseDeptCase, baseMenuCase, bizBaseRoleCase, userToken)
	baseMessageRepository := data2.NewBaseMessageRepository(dataData)
	baseMessageDispatchRepository := data2.NewBaseMessageDispatchRepository(dataData)
	baseMessageDeliveryRepository := data2.NewBaseMessageDeliveryRepository(dataData)
	oauthClientRepository := data2.NewOauthClientRepository(dataData)
	baseFileRepository := data2.NewBaseFileRepository(dataData)
	baseThirdAccountRepository := data2.NewBaseThirdAccountRepository(dataData)
	baseUserMFARepository := data2.NewBaseUserMFARepository(dataData)
	baseUserMFATotpRepository := data2.NewBaseUserMFATotpRepository(dataData)
	baseUserMFARecoveryRepository := data2.NewBaseUserMFARecoveryRepository(dataData)
	baseUserMFAWebauthnRepository := data2.NewBaseUserMFAWebauthnRepository(dataData)
	baseTenantCase := biz3.NewBaseTenantCase(baseCase, transaction, baseTenantRepository, baseDeptRepository, baseRoleRepository, baseUserRepository, baseMessageRepository, baseMessageDispatchRepository, baseMessageDeliveryRepository, oauthClientRepository, baseFileRepository, baseThirdAccountRepository, baseUserMFARepository, baseUserMFATotpRepository, baseUserMFARecoveryRepository, baseUserMFAWebauthnRepository, userToken, casbinRuleRepository, casbinRuleCase)
	fileCase := biz2.NewFileCase(baseCase, baseFileRepository)
	authCase := biz3.NewAuthCase(baseCase, bizBaseUserCase, baseRoleCase, baseDeptCase, baseTenantCase, baseMenuCase, fileCase)
	authService := admin.NewAuthService(authCase)
	baseApiService := admin.NewBaseApiService(baseAPICase)
	protector, err := oauthsecret.NewProtector(config2)
	if err != nil {
		return nil, nil, err
	}
	oauthClientCase := biz3.NewOauthClientCase(baseCase, transaction, oauthClientRepository, baseAPICase, baseTenantRepository, casbinRuleCase, userToken, protector)
	oauthClientService := admin.NewOauthClientService(oauthClientCase, authenticator)
	middleware, cleanup := logmiddleware.NewMiddleware(baseCase)
	baseAreaRepository := data2.NewBaseAreaRepository(dataData)
	baseAreaCase := biz3.NewBaseAreaCase(baseCase, baseAreaRepository)
	baseAreaService := admin.NewBaseAreaService(baseAreaCase)
	baseConfigRepository := data2.NewBaseConfigRepository(dataData)
	baseConfigCase := biz3.NewBaseConfigCase(baseCase, transaction, baseConfigRepository, baseI18nCase)
	baseConfigService := admin.NewBaseConfigService(baseConfigCase)
	baseDeptService := admin.NewBaseDeptService(baseDeptCase)
	baseDictRepository := data2.NewBaseDictRepository(dataData)
	baseDictItemRepository := data2.NewBaseDictItemRepository(dataData)
	baseDictItemCase := biz3.NewBaseDictItemCase(baseCase, transaction, baseDictRepository, baseDictItemRepository, baseI18nCase)
	baseDictCase := biz3.NewBaseDictCase(baseCase, transaction, baseDictRepository, baseDictItemCase, baseI18nCase)
	baseDictService := admin.NewBaseDictService(baseDictCase)
	baseDictItemService := admin.NewBaseDictItemService(baseDictItemCase)
	baseJobRepository := data2.NewBaseJobRepository(dataData)
	baseJobLogRepository := data2.NewBaseJobLogRepository(dataData)
	baseJobLogCase := biz3.NewBaseJobLogCase(baseCase, baseJobLogRepository)
	baseJobCase := biz3.NewBaseJobCase(baseCase, jobRuntime, baseJobRepository, baseJobLogCase, baseI18nCase)
	baseJobService := admin.NewBaseJobService(baseJobCase)
	baseJobLogService := admin.NewBaseJobLogService(baseJobLogCase)
	baseLanguageService := admin.NewBaseLanguageService(baseLanguageCase)
	baseLoginLogRepository := data2.NewBaseLoginLogRepository(dataData)
	baseLoginLogCase := biz3.NewBaseLoginLogCase(baseCase, baseLoginLogRepository)
	baseAPILogRepository := data2.NewBaseAPILogRepository(dataData)
	baseAPILogCase := biz3.NewBaseAPILogCase(baseCase, baseAPILogRepository)
	baseOperationLogRepository := data2.NewBaseOperationLogRepository(dataData)
	baseOperationLogCase := biz3.NewBaseOperationLogCase(baseCase, baseOperationLogRepository)
	baseDataAccessLogRepository := data2.NewBaseDataAccessLogRepository(dataData)
	baseDataAccessLogCase := biz3.NewBaseDataAccessLogCase(baseCase, baseDataAccessLogRepository)
	basePermissionLogRepository := data2.NewBasePermissionLogRepository(dataData)
	basePermissionLogCase := biz3.NewBasePermissionLogCase(baseCase, basePermissionLogRepository)
	basePolicyEvaluationLogRepository := data2.NewBasePolicyEvaluationLogRepository(dataData)
	basePolicyEvaluationLogCase := biz3.NewBasePolicyEvaluationLogCase(baseCase, basePolicyEvaluationLogRepository)
	baseLogCase := biz3.NewBaseLogCase(baseCase, baseLoginLogCase, baseAPILogCase, baseOperationLogCase, baseDataAccessLogCase, basePermissionLogCase, basePolicyEvaluationLogCase)
	baseLogService := admin.NewBaseLogService(baseLogCase)
	baseLoginLogService := admin.NewBaseLoginLogService(baseLoginLogCase)
	baseApiLogService := admin.NewBaseApiLogService(baseAPILogCase)
	baseOperationLogService := admin.NewBaseOperationLogService(baseOperationLogCase)
	baseDataAccessLogService := admin.NewBaseDataAccessLogService(baseDataAccessLogCase)
	basePermissionLogService := admin.NewBasePermissionLogService(basePermissionLogCase)
	basePolicyEvaluationLogService := admin.NewBasePolicyEvaluationLogService(basePolicyEvaluationLogCase)
	baseDashboardCase := biz3.NewBaseDashboardCase(baseCase, baseUserRepository, baseRoleRepository, baseLoginLogRepository, baseOperationLogRepository)
	baseDashboardService := admin.NewBaseDashboardService(baseDashboardCase)
	baseFileCase := biz3.NewBaseFileCase(baseCase, baseFileRepository)
	baseFileService := admin.NewBaseFileService(baseFileCase)
	baseMenuService := admin.NewBaseMenuService(baseMenuCase)
	messageDeliveryWriter := data3.NewMessageDeliveryWriter(dataData)
	baseMessageCategoryRepository := data2.NewBaseMessageCategoryRepository(dataData)
	baseMessageCategoryCase := biz3.NewBaseMessageCategoryCase(baseCase, transaction, baseMessageCategoryRepository, baseMessageRepository)
	baseMessageCase := biz3.NewBaseMessageCase(baseCase, transaction, baseMessageRepository, baseMessageDispatchRepository, baseMessageDeliveryRepository, messageDeliveryWriter, baseMessageCategoryCase, baseUserRepository, baseRoleRepository, baseDeptRepository, basePostRepository, baseMenuRepository, sseRuntime)
	baseMessageService := admin.NewBaseMessageService(baseMessageCase)
	baseMessageCategoryService := admin.NewBaseMessageCategoryService(baseMessageCategoryCase)
	basePostCase := biz3.NewBasePostCase(baseCase, transaction, basePostRepository, baseUserRepository)
	basePostService := admin.NewBasePostService(basePostCase)
	baseRoleService := admin.NewBaseRoleService(baseRoleCase)
	baseTenantService := admin.NewBaseTenantService(baseTenantCase)
	baseThirdAccountCase := biz2.NewBaseThirdAccountCase(baseCase, baseThirdAccountRepository)
	baseThirdAccountService := admin.NewBaseThirdAccountService(baseThirdAccountCase)
	baseI18nService := admin.NewBaseI18nService(baseI18nCase)
	baseUserService := admin.NewBaseUserService(bizBaseUserCase)
	codeGenTableRepository := data2.NewCodeGenTableRepository(dataData)
	codeGenColumnRepository := data2.NewCodeGenColumnRepository(dataData)
	codeGenColumnCase := biz3.NewCodeGenColumnCase(baseCase, codeGenColumnRepository, transaction, baseDictRepository, codeGenTableRepository)
	codeGenProtoRepository := data2.NewCodeGenProtoRepository(dataData)
	codeGenProtoCase := biz3.NewCodeGenProtoCase(baseCase, codeGenProtoRepository, transaction, baseAPIRepository, codeGenTableRepository, codeGenColumnCase)
	codeGenTableCase := biz3.NewCodeGenTableCase(baseCase, codeGenTableRepository, transaction, baseDictRepository, baseDictItemRepository, baseMenuCase, codeGenColumnCase, codeGenProtoCase)
	baseMigrationRepository := data2.NewBaseMigrationRepository(dataData)
	baseMigrationCase := biz3.NewBaseMigrationCase(baseCase, baseMigrationRepository, baseI18nCase, migrations)
	codeGenCase := biz3.NewCodeGenCase(baseCase, transaction, baseAPICase, codeGenTableCase, codeGenColumnCase, codeGenProtoCase, baseMenuCase, baseMigrationCase, baseLanguageCase, catalog, progressManager)
	codeGenService := admin.NewCodeGenService(codeGenCase)
	codeGenColumnService := admin.NewCodeGenColumnService(codeGenColumnCase)
	codeGenProtoService := admin.NewCodeGenProtoService(codeGenProtoCase)
	codeGenTableService := admin.NewCodeGenTableService(codeGenTableCase)
	baseMigrationService := admin.NewBaseMigrationService(baseMigrationCase)
	opsMonitoringCase := biz3.NewOpsMonitoringCase(baseCase, baseAPILogRepository, baseMessageDispatchRepository, catalog)
	opsMonitoringService := admin.NewOpsMonitoringService(opsMonitoringCase)
	cacheCase := biz3.NewCacheCase(baseCase)
	cacheService := admin.NewCacheService(cacheCase)
	hub := logstream.DefaultHub()
	runtimeLogCase, err := biz3.NewRuntimeLogCase(baseCase, hub, sseRuntime)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	runtimeLogService := admin.NewRuntimeLogService(runtimeLogCase)
	baseSessionCase := biz3.NewBaseSessionCase(baseCase, userToken)
	baseSessionService := admin.NewBaseSessionService(baseSessionCase)
	baseLoginPolicyRepository := data2.NewBaseLoginPolicyRepository(dataData)
	baseLoginPolicyRuleRepository := data2.NewBaseLoginPolicyRuleRepository(dataData)
	baseLoginPolicyCase := biz3.NewBaseLoginPolicyCase(baseCase, transaction, baseLoginPolicyRepository, baseLoginPolicyRuleRepository, baseTenantRepository, baseUserRepository)
	baseLoginPolicyService := admin.NewBaseLoginPolicyService(baseLoginPolicyCase)
	baseTableArchiveRepository := data2.NewBaseTableArchiveRepository(dataData)
	baseTableArchiveCase := biz3.NewBaseTableArchiveCase(baseCase, baseTableArchiveRepository)
	baseTableArchiveService := admin.NewBaseTableArchiveService(baseTableArchiveCase)
	baseTableArchiveRecordRepository := data2.NewBaseTableArchiveRecordRepository(dataData)
	baseTableArchiveRecordCase := biz3.NewBaseTableArchiveRecordCase(baseCase, baseTableArchiveRecordRepository)
	baseTableArchiveRecordService := admin.NewBaseTableArchiveRecordService(baseTableArchiveRecordCase)
	baseTableArchiveRestoreRepository := data2.NewBaseTableArchiveRestoreRepository(dataData)
	baseTableArchiveRestoreCase := biz3.NewBaseTableArchiveRestoreCase(baseCase, baseTableArchiveRestoreRepository, baseTableArchiveRecordRepository)
	baseTableArchiveRestoreService := admin.NewBaseTableArchiveRestoreService(baseTableArchiveRestoreCase)
	baseTableBackupRepository := data2.NewBaseTableBackupRepository(dataData)
	baseTableBackupCase := biz3.NewBaseTableBackupCase(baseCase, baseTableBackupRepository)
	baseTableBackupService := admin.NewBaseTableBackupService(baseTableBackupCase)
	baseTableBackupRecordRepository := data2.NewBaseTableBackupRecordRepository(dataData)
	baseTableBackupRecordCase := biz3.NewBaseTableBackupRecordCase(baseCase, baseTableBackupRecordRepository)
	baseTableBackupRecordService := admin.NewBaseTableBackupRecordService(baseTableBackupRecordCase)
	baseTableBackupRestoreRepository := data2.NewBaseTableBackupRestoreRepository(dataData)
	baseTableBackupRestoreCase := biz3.NewBaseTableBackupRestoreCase(baseCase, baseTableBackupRestoreRepository, baseTableBackupRecordRepository)
	baseTableBackupRestoreService := admin.NewBaseTableBackupRestoreService(baseTableBackupRestoreCase)
	baseTableSourceCase := biz3.NewBaseTableSourceCase(baseCase)
	baseTableSourceService := admin.NewBaseTableSourceService(baseTableSourceCase)
	baseRedactOutputPolicyRepository := data2.NewBaseRedactOutputPolicyRepository(dataData)
	baseRedactRuleRepository := data2.NewBaseRedactRuleRepository(dataData)
	baseRedactOutputPolicyCase := biz3.NewBaseRedactOutputPolicyCase(baseCase, transaction, baseRedactOutputPolicyRepository, baseAPIRepository, baseRedactRuleRepository, redactResolver)
	baseRedactOutputPolicyService := admin.NewBaseRedactOutputPolicyService(baseRedactOutputPolicyCase)
	baseRedactStoragePolicyRepository := data2.NewBaseRedactStoragePolicyRepository(dataData)
	baseRedactRuleCase := biz3.NewBaseRedactRuleCase(baseCase, baseRedactRuleRepository, baseRedactStoragePolicyRepository, baseRedactOutputPolicyRepository, redactResolver)
	baseRedactRuleService := admin.NewBaseRedactRuleService(baseRedactRuleCase)
	baseRedactStorageValueRepository := data2.NewBaseRedactStorageValueRepository(dataData)
	baseRedactStoragePolicyCase := biz3.NewBaseRedactStoragePolicyCase(baseCase, transaction, baseRedactStoragePolicyRepository, baseRedactStorageValueRepository, baseRedactRuleRepository, redactResolver)
	baseRedactStoragePolicyService := admin.NewBaseRedactStoragePolicyService(baseRedactStoragePolicyCase)
	services := admin2.Services{
		Auth:                     authService,
		BaseAPI:                  baseApiService,
		OauthClient:              oauthClientService,
		BaseAPICase:              baseAPICase,
		BaseUserRepository:       baseUserRepository,
		OauthClientRepository:    oauthClientRepository,
		Authenticator:            authenticator,
		OauthCredentialProtector: protector,
		LogMiddleware:            middleware,
		BaseCase:                 baseCase,
		UserToken:                userToken,
		BaseArea:                 baseAreaService,
		BaseConfig:               baseConfigService,
		BaseDept:                 baseDeptService,
		BaseDict:                 baseDictService,
		BaseDictItem:             baseDictItemService,
		BaseJob:                  baseJobService,
		BaseJobLog:               baseJobLogService,
		BaseLanguage:             baseLanguageService,
		BaseLog:                  baseLogService,
		BaseLoginLog:             baseLoginLogService,
		BaseApiLog:               baseApiLogService,
		BaseOperationLog:         baseOperationLogService,
		BaseDataAccessLog:        baseDataAccessLogService,
		BasePermissionLog:        basePermissionLogService,
		BasePolicyEvaluationLog:  basePolicyEvaluationLogService,
		BaseDashboard:            baseDashboardService,
		BaseFile:                 baseFileService,
		BaseMenu:                 baseMenuService,
		BaseMessage:              baseMessageService,
		BaseMessageCategory:      baseMessageCategoryService,
		BasePost:                 basePostService,
		BaseRole:                 baseRoleService,
		BaseTenant:               baseTenantService,
		BaseThirdAccount:         baseThirdAccountService,
		BaseI18n:                 baseI18nService,
		BaseUser:                 baseUserService,
		CodeGen:                  codeGenService,
		CodeGenColumn:            codeGenColumnService,
		CodeGenProto:             codeGenProtoService,
		CodeGenTable:             codeGenTableService,
		BaseMigration:            baseMigrationService,
		OpsMonitoring:            opsMonitoringService,
		Cache:                    cacheService,
		RuntimeLog:               runtimeLogService,
		BaseSession:              baseSessionService,
		BaseLoginPolicy:          baseLoginPolicyService,
		BaseTableArchive:         baseTableArchiveService,
		BaseTableArchiveRecord:   baseTableArchiveRecordService,
		BaseTableArchiveRestore:  baseTableArchiveRestoreService,
		BaseTableBackup:          baseTableBackupService,
		BaseTableBackupRecord:    baseTableBackupRecordService,
		BaseTableBackupRestore:   baseTableBackupRestoreService,
		BaseTableSource:          baseTableSourceService,
		BaseRedactOutputPolicy:   baseRedactOutputPolicyService,
		BaseRedactRule:           baseRedactRuleService,
		BaseRedactStoragePolicy:  baseRedactStoragePolicyService,
	}
	adminTools, err := ParseAdminAgentTools(services)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseUserCase2 := biz4.NewBaseUserCase(baseCase, baseUserRepository)
	manager, err := config.ParseOAuthManager(config2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bizAuthCase := biz4.NewAuthCase(baseCase, baseUserCase2, manager)
	appAuthService := app.NewAuthService(bizAuthCase)
	bizBaseAreaCase := biz4.NewBaseAreaCase(baseCase, baseAreaRepository)
	appBaseAreaService := app.NewBaseAreaService(bizBaseAreaCase)
	bizBaseDictItemCase := biz4.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	bizBaseDictCase := biz4.NewBaseDictCase(baseCase, baseDictRepository, bizBaseDictItemCase)
	appBaseDictService := app.NewBaseDictService(bizBaseDictCase)
	bizBaseMenuCase := biz4.NewBaseMenuCase(baseCase, baseMenuRepository)
	appBaseMenuService := app.NewBaseMenuService(bizBaseMenuCase)
	appServices := app2.Services{
		Auth:     appAuthService,
		BaseArea: appBaseAreaService,
		BaseDict: appBaseDictService,
		BaseMenu: appBaseMenuService,
	}
	appTools, err := ParseAppAgentTools(appServices)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	runtime := ai.NewRuntime(responsesClient, mcpCase, adminTools, appTools)
	aiMessageCase := biz2.NewAiMessageCase(baseCase, transaction, aiMessageRepository, aiSessionCase, baseUserCase, runtime)
	aiSessionService := base.NewAiSessionService(aiSessionCase, aiMessageCase)
	aiToolCase := biz2.NewAiToolCase(baseCase, runtime)
	aiToolService := base.NewAiToolService(aiToolCase)
	aiMessageService := base.NewAiMessageService(aiMessageCase)
	configCase := biz2.NewConfigCase(baseCase, baseConfigRepository, baseI18NRepository, baseLanguageRepository)
	configService := base.NewConfigService(configCase)
	languageCase := biz2.NewLanguageCase(baseCase, baseLanguageRepository)
	languageService := base.NewLanguageService(languageCase)
	fileService := base.NewFileService(fileCase)
	bizBaseDeptCase := biz2.NewBaseDeptCase(baseCase, baseDeptRepository)
	mfa := config.ParseMfaConfig(config2)
	mfaCase := biz2.NewMfaCase(baseCase, transaction, baseUserMFARepository, baseUserMFARecoveryRepository, baseUserMFATotpRepository, baseUserMFAWebauthnRepository, baseUserCase, configCase, userToken, mfa)
	loginLocker, cleanup2, err := sessionregistry.NewLoginLocker(config2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loginCase := biz2.NewLoginCase(baseCase, bizBaseDeptCase, bizBaseRoleCase, baseUserCase, baseTenantRepository, baseDictRepository, baseDictItemRepository, mfaCase, userToken, loginLocker)
	loginService := base.NewLoginService(loginCase)
	mfaService := base.NewMfaService(loginCase, mfaCase)
	oauthCase := biz2.NewOauthCase(baseCase, transaction, baseThirdAccountCase, baseUserCase, bizBaseRoleCase, bizBaseDeptCase, loginCase, configCase, manager)
	oauthService := base.NewOauthService(oauthCase)
	oauthClientTokenCase := biz2.NewOauthClientTokenCase(baseCase, oauthClientRepository, baseTenantRepository, userToken, protector)
	baseOauthClientService := base.NewOauthClientService(oauthClientTokenCase)
	mcpService := base.NewMcpService(mcpCase)
	notificationCase := biz2.NewNotificationCase(baseCase, baseMessageDeliveryRepository, messageDeliveryWriter, baseMessageRepository, baseMessageCategoryRepository, sseRuntime)
	notificationService := base.NewNotificationService(notificationCase)
	sseCase := biz2.NewSseCase(baseCase, sseRuntime)
	sseService := base.NewSseService(sseCase)
	baseServices := &base2.Services{
		AiSession:    aiSessionService,
		AiTool:       aiToolService,
		AiMessage:    aiMessageService,
		Config:       configService,
		Language:     languageService,
		File:         fileService,
		Login:        loginService,
		Mfa:          mfaService,
		Oauth:        oauthService,
		OauthClient:  baseOauthClientService,
		Mcp:          mcpService,
		Notification: notificationService,
		Sse:          sseService,
	}
	adminServices := &admin2.Services{
		Auth:                     authService,
		BaseAPI:                  baseApiService,
		OauthClient:              oauthClientService,
		BaseAPICase:              baseAPICase,
		BaseUserRepository:       baseUserRepository,
		OauthClientRepository:    oauthClientRepository,
		Authenticator:            authenticator,
		OauthCredentialProtector: protector,
		LogMiddleware:            middleware,
		BaseCase:                 baseCase,
		UserToken:                userToken,
		BaseArea:                 baseAreaService,
		BaseConfig:               baseConfigService,
		BaseDept:                 baseDeptService,
		BaseDict:                 baseDictService,
		BaseDictItem:             baseDictItemService,
		BaseJob:                  baseJobService,
		BaseJobLog:               baseJobLogService,
		BaseLanguage:             baseLanguageService,
		BaseLog:                  baseLogService,
		BaseLoginLog:             baseLoginLogService,
		BaseApiLog:               baseApiLogService,
		BaseOperationLog:         baseOperationLogService,
		BaseDataAccessLog:        baseDataAccessLogService,
		BasePermissionLog:        basePermissionLogService,
		BasePolicyEvaluationLog:  basePolicyEvaluationLogService,
		BaseDashboard:            baseDashboardService,
		BaseFile:                 baseFileService,
		BaseMenu:                 baseMenuService,
		BaseMessage:              baseMessageService,
		BaseMessageCategory:      baseMessageCategoryService,
		BasePost:                 basePostService,
		BaseRole:                 baseRoleService,
		BaseTenant:               baseTenantService,
		BaseThirdAccount:         baseThirdAccountService,
		BaseI18n:                 baseI18nService,
		BaseUser:                 baseUserService,
		CodeGen:                  codeGenService,
		CodeGenColumn:            codeGenColumnService,
		CodeGenProto:             codeGenProtoService,
		CodeGenTable:             codeGenTableService,
		BaseMigration:            baseMigrationService,
		OpsMonitoring:            opsMonitoringService,
		Cache:                    cacheService,
		RuntimeLog:               runtimeLogService,
		BaseSession:              baseSessionService,
		BaseLoginPolicy:          baseLoginPolicyService,
		BaseTableArchive:         baseTableArchiveService,
		BaseTableArchiveRecord:   baseTableArchiveRecordService,
		BaseTableArchiveRestore:  baseTableArchiveRestoreService,
		BaseTableBackup:          baseTableBackupService,
		BaseTableBackupRecord:    baseTableBackupRecordService,
		BaseTableBackupRestore:   baseTableBackupRestoreService,
		BaseTableSource:          baseTableSourceService,
		BaseRedactOutputPolicy:   baseRedactOutputPolicyService,
		BaseRedactRule:           baseRedactRuleService,
		BaseRedactStoragePolicy:  baseRedactStoragePolicyService,
	}
	services2 := &app2.Services{
		Auth:     appAuthService,
		BaseArea: appBaseAreaService,
		BaseDict: appBaseDictService,
		BaseMenu: appBaseMenuService,
	}
	modules, err := NewModules(baseServices, adminServices, services2, baseConfigCase, baseLoginPolicyCase, redactResolver)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return modules, func() {
		cleanup2()
		cleanup()
	}, nil
}

// BuildTasks 通过最小依赖集合装配 Admin 定时任务。
func BuildTasks(databases map[string]*gorm.Client, baseCase *biz.BaseCase, sseRuntime *sse.SSE) (job.Tasks, func(), error) {
	dataData, err := data2.NewData(databases)
	if err != nil {
		return nil, nil, err
	}
	transaction := data2.NewTransaction(dataData)
	baseI18NRepository := data2.NewBaseI18NRepository(dataData)
	baseLanguageRepository := data2.NewBaseLanguageRepository(dataData)
	baseLanguageCase := biz3.NewBaseLanguageCase(baseCase, transaction, baseLanguageRepository)
	baseI18nCase := biz3.NewBaseI18nCase(baseCase, transaction, baseI18NRepository, baseLanguageCase)
	baseMenuRepository := data2.NewBaseMenuRepository(dataData)
	baseDictRepository := data2.NewBaseDictRepository(dataData)
	baseDictItemRepository := data2.NewBaseDictItemRepository(dataData)
	baseConfigRepository := data2.NewBaseConfigRepository(dataData)
	baseJobRepository := data2.NewBaseJobRepository(dataData)
	baseI18nTask := admin3.NewBaseI18nTask(baseI18nCase, baseMenuRepository, baseDictRepository, baseDictItemRepository, baseConfigRepository, baseJobRepository)
	baseMessageRepository := data2.NewBaseMessageRepository(dataData)
	baseMessageDispatchRepository := data2.NewBaseMessageDispatchRepository(dataData)
	baseMessageDeliveryRepository := data2.NewBaseMessageDeliveryRepository(dataData)
	messageDeliveryWriter := data3.NewMessageDeliveryWriter(dataData)
	baseMessageCategoryRepository := data2.NewBaseMessageCategoryRepository(dataData)
	baseMessageCategoryCase := biz3.NewBaseMessageCategoryCase(baseCase, transaction, baseMessageCategoryRepository, baseMessageRepository)
	baseUserRepository := data2.NewBaseUserRepository(dataData)
	baseRoleRepository := data2.NewBaseRoleRepository(dataData)
	baseDeptRepository := data2.NewBaseDeptRepository(dataData)
	basePostRepository := data2.NewBasePostRepository(dataData)
	baseMessageCase := biz3.NewBaseMessageCase(baseCase, transaction, baseMessageRepository, baseMessageDispatchRepository, baseMessageDeliveryRepository, messageDeliveryWriter, baseMessageCategoryCase, baseUserRepository, baseRoleRepository, baseDeptRepository, basePostRepository, baseMenuRepository, sseRuntime)
	messageDispatchTask := admin3.NewMessageDispatchTask(baseMessageCase)
	baseTableArchiveRepository := data2.NewBaseTableArchiveRepository(dataData)
	baseTableArchiveRecordRepository := data2.NewBaseTableArchiveRecordRepository(dataData)
	tableArchiveTask := admin3.NewTableArchiveTask(baseCase, baseTableArchiveRepository, baseTableArchiveRecordRepository)
	baseLoginLogRepository := data2.NewBaseLoginLogRepository(dataData)
	baseOperationLogRepository := data2.NewBaseOperationLogRepository(dataData)
	baseDataAccessLogRepository := data2.NewBaseDataAccessLogRepository(dataData)
	basePermissionLogRepository := data2.NewBasePermissionLogRepository(dataData)
	baseLogFallbackTask := admin3.NewBaseLogFallbackTask(baseCase, baseLoginLogRepository, baseOperationLogRepository, baseDataAccessLogRepository, basePermissionLogRepository)
	baseTableBackupRepository := data2.NewBaseTableBackupRepository(dataData)
	baseTableBackupRecordRepository := data2.NewBaseTableBackupRecordRepository(dataData)
	tableBackupTask := admin3.NewTableBackupTask(baseCase, baseTableBackupRepository, baseTableBackupRecordRepository)
	tasks := task.NewTask(baseI18nTask, messageDispatchTask, tableArchiveTask, baseLogFallbackTask, tableBackupTask)
	return tasks, func() {
	}, nil
}

// BuildStreams 使用与协议服务相同的任务管理器装配 Admin SSE 流。
func BuildStreams(progressManager *codegen.Manager, databases map[string]*gorm.Client, baseCase *biz.BaseCase, catalog *i18n.I18n) (sse.Streams, func(), error) {
	sseCodegen := sse2.NewCodegen(progressManager)
	notification := sse2.NewNotification()
	dataData, err := data2.NewData(databases)
	if err != nil {
		return nil, nil, err
	}
	baseAPILogRepository := data2.NewBaseAPILogRepository(dataData)
	baseMessageDispatchRepository := data2.NewBaseMessageDispatchRepository(dataData)
	opsMonitoringCase := biz3.NewOpsMonitoringCase(baseCase, baseAPILogRepository, baseMessageDispatchRepository, catalog)
	opsMonitoring := sse2.NewOpsMonitoring(opsMonitoringCase)
	hub := logstream.DefaultHub()
	runtimeConsole := sse2.NewRuntimeConsole(hub)
	streams, cleanup := sse2.NewStreams(sseCodegen, notification, opsMonitoring, runtimeConsole)
	return streams, func() {
		cleanup()
	}, nil
}

// BuildQueueConsumers 装配 Admin 队列消费者集合。
func BuildQueueConsumers(databases map[string]*gorm.Client, baseCase *biz.BaseCase, sseRuntime *sse.SSE) (queue.Consumers, func(), error) {
	dataData, err := data2.NewData(databases)
	if err != nil {
		return nil, nil, err
	}
	transaction := data2.NewTransaction(dataData)
	baseMessageRepository := data2.NewBaseMessageRepository(dataData)
	baseMessageDispatchRepository := data2.NewBaseMessageDispatchRepository(dataData)
	baseMessageDeliveryRepository := data2.NewBaseMessageDeliveryRepository(dataData)
	messageDeliveryWriter := data3.NewMessageDeliveryWriter(dataData)
	baseMessageCategoryRepository := data2.NewBaseMessageCategoryRepository(dataData)
	baseMessageCategoryCase := biz3.NewBaseMessageCategoryCase(baseCase, transaction, baseMessageCategoryRepository, baseMessageRepository)
	baseUserRepository := data2.NewBaseUserRepository(dataData)
	baseRoleRepository := data2.NewBaseRoleRepository(dataData)
	baseDeptRepository := data2.NewBaseDeptRepository(dataData)
	basePostRepository := data2.NewBasePostRepository(dataData)
	baseMenuRepository := data2.NewBaseMenuRepository(dataData)
	baseMessageCase := biz3.NewBaseMessageCase(baseCase, transaction, baseMessageRepository, baseMessageDispatchRepository, baseMessageDeliveryRepository, messageDeliveryWriter, baseMessageCategoryCase, baseUserRepository, baseRoleRepository, baseDeptRepository, basePostRepository, baseMenuRepository, sseRuntime)
	baseLoginLogRepository := data2.NewBaseLoginLogRepository(dataData)
	baseOperationLogRepository := data2.NewBaseOperationLogRepository(dataData)
	baseDataAccessLogRepository := data2.NewBaseDataAccessLogRepository(dataData)
	basePermissionLogRepository := data2.NewBasePermissionLogRepository(dataData)
	consumerFunc := logmiddleware.NewConsumer(baseLoginLogRepository, baseOperationLogRepository, baseDataAccessLogRepository, basePermissionLogRepository)
	consumers := NewQueueConsumers(baseMessageCase, consumerFunc)
	return consumers, func() {
	}, nil
}
