// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/ai_search.proto

/* eslint-disable */

/** AI 助手联网搜索请求 */
export interface SearchAiWebRequest {
  /** 搜索关键词 */
  query: string;
  /** 返回结果数量：0 表示默认5条，最大10条 */
  limit: number;
}

/** AI 助手联网搜索响应 */
export interface SearchAiWebResponse {
  /** 搜索结果列表 */
  items: SearchAiWebItem[];
}

/** AI 助手联网搜索结果 */
export interface SearchAiWebItem {
  /** 结果标题 */
  title: string;
  /** 结果链接 */
  url: string;
  /** 结果摘要 */
  snippet: string;
}

/** Base AI 助手联网搜索服务 */
export interface AiSearchService {
  /** 联网搜索公开信息并返回结果摘要 */
  SearchAiWeb(request: SearchAiWebRequest): Promise<SearchAiWebResponse>;
}
