syntax = "proto3";

package system.admin.v1;

import "common/v1/common.proto";
import "buf/validate/validate.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

// Admin应用信息服务
service BaseApplicationService {
  // 查询应用信息下拉选择
  rpc OptionBaseApplication(OptionBaseApplicationRequest) returns (.common.v1.SelectOptionResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/application/option"
    };
  }

  // 查询应用信息分页列表
  rpc PageBaseApplication(PageBaseApplicationRequest) returns (PageBaseApplicationResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/application"
    };
  }

  // 查询应用信息详情
  rpc GetBaseApplication(GetBaseApplicationRequest) returns (BaseApplicationForm) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/application/{id}"
    };
  }

  // 创建应用信息
  rpc CreateBaseApplication(CreateBaseApplicationRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/v1/admin/base/application"
      body: "base_application"
    };
  }

  // 更新应用信息
  rpc UpdateBaseApplication(UpdateBaseApplicationRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/application/{id}"
      body: "base_application"
    };
  }

  // 删除应用信息
  rpc DeleteBaseApplication(DeleteBaseApplicationRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/admin/base/application/{ids}"
    };
  }

  // 设置状态
  rpc SetBaseApplicationStatus(SetBaseApplicationStatusRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/application/{id}/status"
      body: "*"
    };
  }
  // 分页查询应用授权用户
  rpc PageApplicationUser(PageApplicationUserRequest) returns (PageApplicationUserResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/application/{application_id}/user"
    };
  }

  // 授权用户（绑定）
  rpc SetApplicationUser(SetApplicationUserRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/v1/admin/base/application/{application_id}/user"
      body: "*"
    };
  }

  // 移除授权用户
  rpc DeleteApplicationUser(DeleteApplicationUserRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/admin/base/application/{application_id}/user/{user_id}"
    };
  }
}

// 应用信息下拉选择查询条件
message OptionBaseApplicationRequest {}

// 应用信息分页查询条件
message PageBaseApplicationRequest {
  optional int64 tenant_id = 1 [(gnostic.openapi.v3.property) = {description: "租户"}]; // 租户

  optional string name = 2 [(gnostic.openapi.v3.property) = {description: "应用名称"}]; // 应用名称

  optional string code = 3 [(gnostic.openapi.v3.property) = {description: "应用编码"}]; // 应用编码

  optional int32 status = 4 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  int64 page_num = 101 [(gnostic.openapi.v3.property) = {description: "当前页码"}]; // 当前页码

  int64 page_size = 102 [(gnostic.openapi.v3.property) = {description: "每一页的行数"}]; // 每一页的行数
}

// 应用信息分页响应
message PageBaseApplicationResponse {
  repeated BaseApplication base_applications = 1 [(gnostic.openapi.v3.property) = {description: "应用信息列表"}]; // 应用信息列表

  int32 total = 2 [(gnostic.openapi.v3.property) = {description: "总数"}]; // 总数
}

// 应用信息
message BaseApplication {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "应用ID"}]; // 应用ID

  int64 tenant_id = 2 [(gnostic.openapi.v3.property) = {description: "租户"}]; // 租户

  string name = 3 [(gnostic.openapi.v3.property) = {description: "应用名称"}]; // 应用名称

  string code = 4 [(gnostic.openapi.v3.property) = {description: "应用编码"}]; // 应用编码

  int32 sort = 5 [(gnostic.openapi.v3.property) = {description: "显示顺序"}]; // 显示顺序

  string remark = 6 [(gnostic.openapi.v3.property) = {description: "应用备注"}]; // 应用备注

  int32 status = 7 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  string created_at = 8 [(gnostic.openapi.v3.property) = {description: "创建时间"}]; // 创建时间

  string updated_at = 9 [(gnostic.openapi.v3.property) = {description: "更新时间"}]; // 更新时间

  string url = 10 [(gnostic.openapi.v3.property) = {description: "应用链接地址"}]; // 应用链接地址

  string ico = 11 [(gnostic.openapi.v3.property) = {description: "应用图标"}]; // 应用图标

}

// 应用信息详情查询条件
message GetBaseApplicationRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "应用信息ID"}]; // 应用信息ID
}

// 应用信息表单
message BaseApplicationForm {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "应用ID"}]; // 应用ID

  int64 tenant_id = 2 [(gnostic.openapi.v3.property) = {description: "租户"}]; // 租户

  string name = 3 [(gnostic.openapi.v3.property) = {description: "应用名称"}, (buf.validate.field).cel = {id: "system.admin.code.gen.table.field.name.length" message: "应用名称不能为空且不超过 50 个字符" expression: "this.size() > 0 && this.size() <= 50"}]; // 应用名称

  string code = 4 [(gnostic.openapi.v3.property) = {description: "应用编码"}, (buf.validate.field).cel = {id: "system.admin.code.gen.table.field.code.length" message: "应用编码不能为空且不超过 100 个字符" expression: "this.size() > 0 && this.size() <= 100"}]; // 应用编码

  int32 sort = 5 [(gnostic.openapi.v3.property) = {description: "显示顺序"}]; // 显示顺序

  optional string remark = 6 [(gnostic.openapi.v3.property) = {description: "应用备注"}, (buf.validate.field).cel = {id: "system.admin.code.gen.table.field.remark.length" message: "应用备注不能超过 500 个字符" expression: "this.size() <= 500"}]; // 应用备注

  int32 status = 7 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  optional string url = 8 [(gnostic.openapi.v3.property) = {description: "应用链接地址"}, (buf.validate.field).cel = {id: "system.admin.code.gen.table.field.url.length" message: "应用链接地址不能超过 2000 个字符" expression: "this.size() <= 2000"}]; // 应用链接地址

  optional string ico = 9 [(gnostic.openapi.v3.property) = {description: "应用图标"}, (buf.validate.field).cel = {id: "system.admin.code.gen.table.field.ico.length" message: "应用图标不能超过 255 个字符" expression: "this.size() <= 255"}]; // 应用图标

}

// 应用信息创建条件
message CreateBaseApplicationRequest {
  BaseApplicationForm base_application = 1 [(gnostic.openapi.v3.property) = {description: "应用信息表单"}, (buf.validate.field).required = true]; // 应用信息表单
}

// 应用信息更新条件
message UpdateBaseApplicationRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "应用信息ID"}]; // 应用信息ID

  BaseApplicationForm base_application = 2 [(gnostic.openapi.v3.property) = {description: "应用信息表单"}, (buf.validate.field).required = true]; // 应用信息表单
}

// 应用信息删除条件
message DeleteBaseApplicationRequest {
  string ids = 1 [(gnostic.openapi.v3.property) = {description: "应用信息ID列表，多个用逗号分隔"}]; // 应用信息ID列表，多个用逗号分隔
}

// 应用信息状态设置条件
message SetBaseApplicationStatusRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "应用信息ID"}]; // 应用信息ID

  int32 status = 2 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态
}

// 应用授权用户分页查询条件
message PageApplicationUserRequest {
  int64 application_id = 1 [(gnostic.openapi.v3.property) = {description: "应用ID"}]; // 应用ID

  int32 page_num = 2 [(gnostic.openapi.v3.property) = {description: "页码"}]; // 页码

  int32 page_size = 3 [(gnostic.openapi.v3.property) = {description: "页大小"}]; // 页大小
}

// 应用授权用户
message BaseApplicationUser {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "主键ID"}]; // 主键ID

  int64 user_id = 2 [(gnostic.openapi.v3.property) = {description: "授权用户ID"}]; // 授权用户ID

  string created_at = 3 [(gnostic.openapi.v3.property) = {description: "授权时间"}]; // 授权时间
}

// 应用授权用户分页结果
message PageApplicationUserResponse {
  repeated BaseApplicationUser base_application_users = 1 [(gnostic.openapi.v3.property) = {description: "授权用户列表"}]; // 授权用户列表

  int32 total = 2 [(gnostic.openapi.v3.property) = {description: "总数"}]; // 总数
}

// 授权用户请求
message SetApplicationUserRequest {
  int64 application_id = 1 [(gnostic.openapi.v3.property) = {description: "应用ID"}]; // 应用ID

  int64 user_id = 2 [(gnostic.openapi.v3.property) = {description: "授权用户ID"}]; // 授权用户ID
}

// 移除授权用户请求
message DeleteApplicationUserRequest {
  int64 application_id = 1 [(gnostic.openapi.v3.property) = {description: "应用ID"}]; // 应用ID

  int64 user_id = 2 [(gnostic.openapi.v3.property) = {description: "授权用户ID"}]; // 授权用户ID
}
