syntax = "proto3";

package system.admin.v1;

import "buf/validate/validate.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

// Admin定时任务日志服务
service BaseJobLogService {
  // 查询定时任务日志分页列表
  rpc PageBaseJobLog(PageBaseJobLogRequest) returns (PageBaseJobLogResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/job-log"
    };
  }

  // 查询定时任务日志
  rpc GetBaseJobLog(GetBaseJobLogRequest) returns (BaseJobLog) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/job-log/{id}"
    };
  }
}

// 定时任务日志状态。
enum BaseJobLogStatus {
  // 未指定定时任务日志状态。
  BASE_JOB_LOG_STATUS_UNSPECIFIED = 0;
  // 成功。
  BASE_JOB_LOG_STATUS_SUCCESS = 1;
  // 失败。
  BASE_JOB_LOG_STATUS_FAIL = 2;
}

// 定时任务日志分页查询条件
message PageBaseJobLogRequest {
  int64 job_id = 2 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID

  optional BaseJobLogStatus status = 6 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  repeated string execute_time = 8 [(gnostic.openapi.v3.property) = {description: "执行时间"}]; // 执行时间

  int64 page_num = 101 [(gnostic.openapi.v3.property) = {
    description: "当前页码"
    default: {number: 1}
  },
    (buf.validate.field).int64 = {gte: 1, lte: 1000000}]; // 当前页码

  int64 page_size = 102 [(gnostic.openapi.v3.property) = {
    description: "每一页的行数"
    default: {number: 10}
  },
    (buf.validate.field).int64 = {gte: 1, lte: 100}]; // 每一页的行数
}

// 定时任务日志分页响应
message PageBaseJobLogResponse {
  repeated BaseJobLog base_job_logs = 1 [(gnostic.openapi.v3.property) = {description: "分页数据"}]; // 分页数据

  int32 total = 2 [(gnostic.openapi.v3.property) = {description: "总数"}]; // 总数
}

// 查询定时任务日志请求参数
message GetBaseJobLogRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务日志ID"}]; // 任务日志ID
}

// 定时任务日志
message BaseJobLog {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务日志ID"}]; // 任务日志ID

  int64 job_id = 2 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID

  string input = 3 [(gnostic.openapi.v3.property) = {
    description: "执行参数"
    max_length: 255
  }]; // 执行参数

  string output = 4 [(gnostic.openapi.v3.property) = {description: "输出结果"}]; // 输出结果

  string error = 5 [(gnostic.openapi.v3.property) = {description: "错误信息"}]; // 错误信息

  BaseJobLogStatus status = 6 [(gnostic.openapi.v3.property) = {description: "状态：1、成功。2、失败。"}]; // 状态：1、成功。2、失败。

  string process_time = 7 [(gnostic.openapi.v3.property) = {description: "消耗时间/毫秒"}]; // 消耗时间/毫秒

  string execute_time = 8 [(gnostic.openapi.v3.property) = {description: "执行时间"}]; // 执行时间
}
