syntax = "proto3";

package system.admin.v1;

import "buf/validate/validate.proto";
import "common/v1/types.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

// Admin数据源元数据服务，提供数据备份、数据归档和代码生成共用的数据源信息。
service BaseTableSourceService {
  // 查询已初始化的数据源名称。
  rpc OptionBaseTableSource(OptionBaseTableSourceRequest) returns (.common.v1.StringValues) {
    option (google.api.http) = {get: "/api/v1/admin/base/table-source/option"};
  }

  // 查询指定数据源中的数据库表选项。
  rpc OptionBaseTable(OptionBaseTableRequest) returns (OptionBaseTableResponse) {
    option (google.api.http) = {get: "/api/v1/admin/base/table-source/table/option"};
  }
}

// OptionBaseTableSourceRequest 查询数据源名称请求。
message OptionBaseTableSourceRequest {}

// OptionBaseTableRequest 查询指定数据源的数据库表名称请求。
message OptionBaseTableRequest {
  string source_name = 1 [
    (gnostic.openapi.v3.property) = {description: "数据源名称"},
    (buf.validate.field).cel = {
      id: "system.admin.base.table.source.option.table.source_name.required"
      message: "数据源名称不能为空"
      expression: "this.size() > 0"
    }
  ]; // 数据源名称
}

// 数据库表选项。
message BaseTableOption {
  string name = 1 [(gnostic.openapi.v3.property) = {description: "数据库表名"}]; // 数据库表名
  string comment = 2 [(gnostic.openapi.v3.property) = {description: "数据表注释"}]; // 数据表注释
}

// 数据库表选项响应。
message OptionBaseTableResponse {
  repeated BaseTableOption tables = 1 [(gnostic.openapi.v3.property) = {description: "数据库表选项列表"}]; // 数据库表选项列表
}
