syntax = "proto3";

package system.admin.v1;

import "common/v1/common.proto";
import "common/v1/enum.proto";
import "buf/validate/validate.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

// Admin岗位管理服务
service BasePostService {
  // 查询岗位下拉选择
  rpc OptionBasePost(OptionBasePostRequest) returns (.common.v1.SelectOptionResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/post/option"
    };
  }

  // 查询岗位分页列表
  rpc PageBasePost(PageBasePostRequest) returns (PageBasePostResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/post"
    };
  }

  // 查询岗位
  rpc GetBasePost(GetBasePostRequest) returns (BasePostForm) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/post/{id}"
    };
  }

  // 创建岗位
  rpc CreateBasePost(CreateBasePostRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/v1/admin/base/post"
      body: "base_post"
    };
  }

  // 更新岗位
  rpc UpdateBasePost(UpdateBasePostRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/post/{base_post.id}"
      body: "base_post"
    };
  }

  // 删除岗位
  rpc DeleteBasePost(DeleteBasePostRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/admin/base/post/{id}"
    };
  }

  // 设置岗位状态
  rpc SetBasePostStatus(SetBasePostStatusRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/post/{id}/status"
      body: "*"
    };
  }
}

// 岗位选项查询条件
message OptionBasePostRequest {
  optional int64 tenant_id = 1 [(gnostic.openapi.v3.property) = {description: "租户ID"}]; // 租户ID
}

// 岗位分页查询条件
message PageBasePostRequest {
  string name = 2 [(gnostic.openapi.v3.property) = {description: "岗位名称"}]; // 岗位名称

  string code = 3 [(gnostic.openapi.v3.property) = {description: "岗位编号"}]; // 岗位编号

  optional int64 tenant_id = 4 [(gnostic.openapi.v3.property) = {description: "租户ID"}]; // 租户ID

  optional .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  int64 page_num = 101 [(gnostic.openapi.v3.property) = {
    description: "当前页码"
    default: {number: 1}
  },
    (buf.validate.field).int64 = {gte: 1, lte: 1000000}]; // 当前页码

  int64 page_size = 102 [(gnostic.openapi.v3.property) = {
    description: "每一页的行数"
    default: {number: 10}
  },
    (buf.validate.field).int64 = {gte: 1, lte: 100}]; // 每一页的行数
}

// 岗位分页响应
message PageBasePostResponse {
  repeated BasePost base_posts = 1 [(gnostic.openapi.v3.property) = {description: "分页数据"}]; // 分页数据

  int32 total = 2 [(gnostic.openapi.v3.property) = {description: "总数"}]; // 总数
}

// 查询岗位请求参数
message GetBasePostRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "岗位ID"}, (buf.validate.field).cel = {id: "system.admin.base.post.get.id.required" message: "岗位ID不能为空" expression: "this > 0"}]; // 岗位ID
}

// 岗位表单
message BasePostForm {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "岗位ID"}]; // 岗位ID

  int64 tenant_id = 2 [(gnostic.openapi.v3.property) = {description: "租户ID"}, (buf.validate.field).cel = {id: "system.admin.base.post.entity.tenant_id.required" message: "请选择所属租户" expression: "this > 0"}]; // 租户ID

  string name = 3 [(gnostic.openapi.v3.property) = {description: "岗位名称"}, (buf.validate.field).cel = {id: "system.admin.base.post.entity.name.required" message: "请输入岗位名称" expression: "this.size() > 0"}, (buf.validate.field).cel = {id: "system.admin.base.post.entity.name.max_length" message: "岗位名称不能超过 30 个字符" expression: "this.size() <= 30"}]; // 岗位名称

  string code = 4 [(gnostic.openapi.v3.property) = {description: "岗位编号"}, (buf.validate.field).cel = {id: "system.admin.base.post.entity.code.required" message: "请输入岗位编号" expression: "this.size() > 0"}, (buf.validate.field).cel = {id: "system.admin.base.post.entity.code.max_length" message: "岗位编号不能超过 20 个字符" expression: "this.size() <= 20"}]; // 岗位编号

  int32 sort = 5 [(gnostic.openapi.v3.property) = {description: "显示顺序"}, (buf.validate.field).cel = {id: "system.admin.base.post.entity.sort.required" message: "排序必须大于 0" expression: "this > 0"}]; // 显示顺序

  .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态"}, (buf.validate.field).enum = {defined_only: true}]; // 状态

  string remark = 101 [(gnostic.openapi.v3.property) = {description: "备注"}, (buf.validate.field).cel = {id: "system.admin.base.post.entity.remark.max_length" message: "备注不能超过 500 个字符" expression: "this.size() <= 500"}]; // 备注
}

// 创建岗位请求参数
message CreateBasePostRequest {
  BasePostForm base_post = 1 [(gnostic.openapi.v3.property) = {description: "岗位表单"}, (buf.validate.field).required = true]; // 岗位表单
}

// 更新岗位请求参数
message UpdateBasePostRequest {
  option (buf.validate.message).cel = {id: "system.admin.base.post.update.id.required" message: "岗位ID不能为空" expression: "this.base_post.id > 0"};

  BasePostForm base_post = 1 [(gnostic.openapi.v3.property) = {description: "岗位表单"}, (buf.validate.field).required = true]; // 岗位表单
}

// 删除岗位请求参数
message DeleteBasePostRequest {
  string id = 1 [(gnostic.openapi.v3.property) = {description: "岗位ID列表"}, (buf.validate.field).cel = {id: "system.admin.base.post.delete.id.required" message: "岗位ID列表不能为空" expression: "this.size() > 0"}]; // 岗位ID列表
}

// 设置岗位状态请求参数
message SetBasePostStatusRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "岗位ID"}, (buf.validate.field).cel = {id: "system.admin.base.post.set_status.id.required" message: "岗位ID不能为空" expression: "this > 0"}]; // 岗位ID

  int32 status = 2 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态
}

// 岗位
message BasePost {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "岗位ID"}]; // 岗位ID

  int64 tenant_id = 2 [(gnostic.openapi.v3.property) = {description: "租户ID"}]; // 租户ID

  string name = 3 [(gnostic.openapi.v3.property) = {description: "岗位名称"}]; // 岗位名称

  string code = 4 [(gnostic.openapi.v3.property) = {description: "岗位编号"}]; // 岗位编号

  int32 sort = 5 [(gnostic.openapi.v3.property) = {description: "显示顺序"}]; // 显示顺序

  .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  string remark = 101 [(gnostic.openapi.v3.property) = {description: "备注"}]; // 备注

  string created_at = 200 [(gnostic.openapi.v3.property) = {description: "创建时间"}]; // 创建时间

  string updated_at = 201 [(gnostic.openapi.v3.property) = {description: "更新时间"}]; // 更新时间
}
