syntax = "proto3";

package system.admin.v1;

import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

// Admin数据库迁移服务。
service BaseMigrationService {
  // 分页查询数据库升级历史
  rpc PageBaseMigration(PageBaseMigrationRequest) returns (PageBaseMigrationResponse) {
    option (google.api.http) = {get: "/api/v1/admin/base-migration"};
  }

  // 查询数据库迁移记录详情
  rpc GetBaseMigration(GetBaseMigrationRequest) returns (BaseMigration) {
    option (google.api.http) = {get: "/api/v1/admin/base-migration/{id}"};
  }
}

// 数据库迁移记录分页查询条件
message PageBaseMigrationRequest {
  string data_source = 1 [(gnostic.openapi.v3.property) = {description: "数据源"}]; // 数据源

  optional string module = 2 [(gnostic.openapi.v3.property) = {description: "迁移模块"}]; // 迁移模块

  optional string version = 3 [(gnostic.openapi.v3.property) = {description: "迁移版本"}]; // 迁移版本


  int64 page_num = 101 [(gnostic.openapi.v3.property) = {
    description: "当前页码"
    default: {number: 1}
  }]; // 当前页码

  int64 page_size = 102 [(gnostic.openapi.v3.property) = {
    description: "每一页的行数"
    default: {number: 10}
  }]; // 每一页的行数
}

// 数据库迁移记录列表项
message BaseMigrationListItem {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "主键"}]; // 主键

  string module = 2 [(gnostic.openapi.v3.property) = {description: "迁移模块"}]; // 迁移模块

  string data_source = 3 [(gnostic.openapi.v3.property) = {description: "数据源"}]; // 数据源

  string version = 4 [(gnostic.openapi.v3.property) = {description: "迁移版本"}]; // 迁移版本

  string created_at = 5 [(gnostic.openapi.v3.property) = {description: "创建时间"}]; // 创建时间

}

// 数据库迁移记录分页响应
message PageBaseMigrationResponse {
  repeated BaseMigrationListItem base_migrations = 1 [(gnostic.openapi.v3.property) = {description: "迁移记录列表"}]; // 迁移记录列表

  int32 total = 2 [(gnostic.openapi.v3.property) = {description: "总数"}]; // 总数
}

// 查询数据库迁移记录详情请求参数
message GetBaseMigrationRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "主键"}]; // 主键
}

// 数据库迁移记录详情
message BaseMigration {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "主键"}]; // 主键

  string module = 2 [(gnostic.openapi.v3.property) = {description: "迁移模块"}]; // 迁移模块

  string data_source = 3 [(gnostic.openapi.v3.property) = {description: "数据源"}]; // 数据源

  string version = 4 [(gnostic.openapi.v3.property) = {description: "迁移版本"}]; // 迁移版本

  repeated BaseMigrationFile files = 5 [(gnostic.openapi.v3.property) = {description: "迁移文件列表"}]; // 迁移文件列表

  string created_at = 6 [(gnostic.openapi.v3.property) = {description: "创建时间"}]; // 创建时间
}

// 数据库迁移文件内容
message BaseMigrationFile {
  string path = 1 [(gnostic.openapi.v3.property) = {description: "文件相对路径"}]; // 文件相对路径

  string content = 2 [(gnostic.openapi.v3.property) = {description: "文件内容"}]; // 文件内容
}
