syntax = "proto3";

package system.admin.v1;

import "common/v1/enum.proto";
import "base/v1/config.proto";
import "buf/validate/validate.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "system/admin/v1/base_i18n.proto";

// Admin系统配置服务
service BaseConfigService {
  // 刷新缓存
  rpc RefreshBaseConfigCache(RefreshBaseConfigCacheRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/config/cache"
      body: "*"
    };
  }

  // 查询系统配置分页列表
  rpc PageBaseConfig(PageBaseConfigRequest) returns (PageBaseConfigResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/config"
    };
  }

  // 查询系统配置
  rpc GetBaseConfig(GetBaseConfigRequest) returns (BaseConfigForm) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/config/{id}"
    };
  }

  // 创建系统配置
  rpc CreateBaseConfig(CreateBaseConfigRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/v1/admin/base/config"
      body: "base_config"
    };
  }

  // 更新系统配置
  rpc UpdateBaseConfig(UpdateBaseConfigRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/config/{base_config.id}"
      body: "base_config"
    };
  }

  // 删除系统配置
  rpc DeleteBaseConfig(DeleteBaseConfigRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/admin/base/config/{id}"
    };
  }

  // 设置状态
  rpc SetBaseConfigStatus(SetBaseConfigStatusRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/config/{id}/status"
      body: "*"
    };
  }

}

// 系统配置类型。
enum BaseConfigType {
  // 未指定系统配置类型。
  BASE_CONFIG_TYPE_UNSPECIFIED = 0;
  // 文本。
  BASE_CONFIG_TYPE_TEXT = 1;
  // 图片。
  BASE_CONFIG_TYPE_IMAGE = 2;
  // 富文本。
  BASE_CONFIG_TYPE_RICH_TEXT = 3;
  // 字典。
  BASE_CONFIG_TYPE_DICT = 4;
  // 布尔。
  BASE_CONFIG_TYPE_BOOLEAN = 5;
  // 表单。
  BASE_CONFIG_TYPE_FORM = 6;
}

// 系统配置分页查询条件
message PageBaseConfigRequest {
  optional .base.v1.BaseConfigSite site = 2 [(gnostic.openapi.v3.property) = {description: "位置：枚举【BaseConfigSite】"}]; // 位置：枚举【BaseConfigSite】

  optional string name = 3 [(gnostic.openapi.v3.property) = {description: "配置名称"}]; // 配置名称

  optional BaseConfigType type = 4 [(gnostic.openapi.v3.property) = {description: "配置类型：枚举【BaseConfigType】"}]; // 配置类型：枚举【BaseConfigType】

  optional string key = 5 [(gnostic.openapi.v3.property) = {description: "配置key"}]; // 配置key

  optional .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态：枚举【Status】"}]; // 状态：枚举【Status】

  int64 page_num = 101 [(gnostic.openapi.v3.property) = {
    description: "当前页码"
    default: {number: 1}
  }]; // 当前页码

  int64 page_size = 102 [(gnostic.openapi.v3.property) = {
    description: "每一页的行数"
    default: {number: 10}
  }]; // 每一页的行数
}

// 系统配置分页响应
message PageBaseConfigResponse {
  repeated BaseConfig base_configs = 1 [(gnostic.openapi.v3.property) = {description: "分页数据"}]; // 分页数据

  int32 total = 2 [(gnostic.openapi.v3.property) = {description: "总数"}]; // 总数
}

// 查询系统配置请求参数
message GetBaseConfigRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "配置ID"}, (buf.validate.field).cel = {id: "system.admin.base.config.get.id.required" message: "配置ID不能为空" expression: "this > 0"}]; // 配置ID
}

// 系统配置表单
message BaseConfigForm {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "配置ID"}]; // 配置ID

  .base.v1.BaseConfigSite site = 2 [(gnostic.openapi.v3.property) = {description: "位置：枚举【BaseConfigSite】"}, (buf.validate.field).enum = {defined_only: true}, (buf.validate.field).cel = {id: "system.admin.base.config.entity.site.required" message: "请选择系统配置位置" expression: "this != 0"}]; // 位置：枚举【BaseConfigSite】

  string name = 3 [(gnostic.openapi.v3.property) = {description: "配置名称"}, (buf.validate.field).cel = {id: "system.admin.base.config.entity.name.required" message: "请输入系统配置名称" expression: "this.size() > 0"}, (buf.validate.field).cel = {id: "system.admin.base.config.entity.name.max_length" message: "配置名称不能超过 50 个字符" expression: "this.size() <= 50"}]; // 配置名称

  BaseConfigType type = 4 [(gnostic.openapi.v3.property) = {description: "配置类型：1、文本，2、图片，3、富文本，4、字典，5、布尔，6、表单"}, (buf.validate.field).enum = {defined_only: true}, (buf.validate.field).cel = {id: "system.admin.base.config.entity.type.required" message: "请选择系统配置类型" expression: "this != 0"}]; // 配置类型：1、文本，2、图片，3、富文本，4、字典，5、布尔，6、表单

  string key = 5 [(gnostic.openapi.v3.property) = {description: "配置key"}, (buf.validate.field).cel = {id: "system.admin.base.config.entity.key.required" message: "请输入系统配置编码" expression: "this.size() > 0"}, (buf.validate.field).cel = {id: "system.admin.base.config.entity.key.max_length" message: "配置key不能超过 50 个字符" expression: "this.size() <= 50"}]; // 配置key

  string value = 6 [(gnostic.openapi.v3.property) = {description: "配置value"}, (buf.validate.field).cel = {id: "system.admin.base.config.entity.value.required" message: "配置值不能为空" expression: "this.size() > 0"}]; // 配置value

  repeated BaseI18n name_i18ns = 7 [(gnostic.openapi.v3.property) = {description: "配置名称多语言翻"}]; // 配置名称多语言翻

  repeated BaseI18n value_i18ns = 8 [(gnostic.openapi.v3.property) = {description: "配置value文本/富文本配置值的多语言翻译"}]; // 配置value文本/富文本配置值的多语言翻译

  .common.v1.Status status = 51 [(gnostic.openapi.v3.property) = {description: "状态"}, (buf.validate.field).enum = {defined_only: true}]; // 状态
}

// 创建系统配置请求参数
message CreateBaseConfigRequest {
  BaseConfigForm base_config = 1 [(gnostic.openapi.v3.property) = {description: "系统配置表单"}, (buf.validate.field).required = true]; // 系统配置表单
}

// 更新系统配置请求参数
message UpdateBaseConfigRequest {
  option (buf.validate.message).cel = {id: "system.admin.base.config.update.id.required" message: "配置ID不能为空" expression: "this.base_config.id > 0"};

  BaseConfigForm base_config = 1 [(gnostic.openapi.v3.property) = {description: "系统配置表单"}, (buf.validate.field).required = true]; // 系统配置表单
}

// 删除系统配置请求参数
message DeleteBaseConfigRequest {
  string id = 1 [(gnostic.openapi.v3.property) = {description: "配置ID列表"}, (buf.validate.field).cel = {id: "system.admin.base.config.delete.id.required" message: "配置ID列表不能为空" expression: "this.size() > 0"}]; // 配置ID列表
}

// 设置系统配置状态请求参数
message SetBaseConfigStatusRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "配置ID"}, (buf.validate.field).cel = {id: "system.admin.base.config.set_status.id.required" message: "配置ID不能为空" expression: "this > 0"}]; // 配置ID

  int32 status = 2 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态
}

// 刷新系统配置缓存请求参数
message RefreshBaseConfigCacheRequest {}

// 系统配置
message BaseConfig {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "配置ID"}]; // 配置ID

  .base.v1.BaseConfigSite site = 2 [(gnostic.openapi.v3.property) = {description: "位置：枚举【BaseConfigSite】"}]; // 位置：枚举【BaseConfigSite】

  string name = 3 [(gnostic.openapi.v3.property) = {description: "配置名称"}]; // 配置名称

  BaseConfigType type = 4 [(gnostic.openapi.v3.property) = {description: "配置类型：枚举【BaseConfigType】"}]; // 配置类型：枚举【BaseConfigType】

  string key = 5 [(gnostic.openapi.v3.property) = {description: "配置key"}]; // 配置key

  string value = 6 [(gnostic.openapi.v3.property) = {description: "配置value"}]; // 配置value

  .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态：枚举【Status】"}]; // 状态：枚举【Status】

  string created_at = 200 [(gnostic.openapi.v3.property) = {description: "创建时间"}]; // 创建时间

  string updated_at = 201 [(gnostic.openapi.v3.property) = {description: "更新时间"}]; // 更新时间

  repeated BaseI18n i18ns = 202 [(gnostic.openapi.v3.property) = {description: "配置名称及文本/富文本配置值的多语言翻译"}]; // 配置名称及文本/富文本配置值的多语言翻译
}
