syntax = "proto3";

package system.admin.v1;

import "common/v1/common.proto";
import "common/v1/enum.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "buf/validate/validate.proto";
import "system/admin/v1/base_i18n.proto";

// Admin定时任务服务
service BaseJobService {
  // 查询定时任务下拉选择
  rpc OptionBaseJob(OptionBaseJobRequest) returns (.common.v1.SelectOptionResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/job/option"
    };
  }

  // 查询定时任务分页列表
  rpc PageBaseJob(PageBaseJobRequest) returns (PageBaseJobResponse) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/job"
    };
  }

  // 查询定时任务
  rpc GetBaseJob(GetBaseJobRequest) returns (BaseJobForm) {
    option (google.api.http) = {
      get: "/api/v1/admin/base/job/{id}"
    };
  }

  // 创建定时任务
  rpc CreateBaseJob(CreateBaseJobRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/v1/admin/base/job"
      body: "base_job"
    };
  }

  // 更新定时任务
  rpc UpdateBaseJob(UpdateBaseJobRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/job/{base_job.id}"
      body: "base_job"
    };
  }

  // 删除定时任务
  rpc DeleteBaseJob(DeleteBaseJobRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/admin/base/job/{id}"
    };
  }

  // 设置状态
  rpc SetBaseJobStatus(SetBaseJobStatusRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/job/{id}/status"
      body: "*"
    };
  }

  // 启动任务
  rpc StartBaseJob(StartBaseJobRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/admin/base/job/{id}/running"
      body: "*"
    };
  }

  // 停止任务
  rpc StopBaseJob(StopBaseJobRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/api/v1/admin/base/job/{id}/running"
    };
  }

  // 执行任务
  rpc ExecuteBaseJob(ExecuteBaseJobRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/api/v1/admin/base/job/{id}/execution"
      body: "*"
    };
  }
}

// 定时任务选项查询条件
message OptionBaseJobRequest {
}

// 定时任务分页查询条件
message PageBaseJobRequest {
  string name = 2 [(gnostic.openapi.v3.property) = {description: "任务名称"}]; // 任务名称

  string invoke_target = 3 [(gnostic.openapi.v3.property) = {description: "调用目标"}]; // 调用目标

  optional .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  int64 page_num = 101 [(gnostic.openapi.v3.property) = {
    description: "当前页码"
    default: {number: 1}
  },
    (buf.validate.field).int64 = {gte: 1, lte: 1000000}]; // 当前页码

  int64 page_size = 102 [(gnostic.openapi.v3.property) = {
    description: "每一页的行数"
    default: {number: 10}
  },
    (buf.validate.field).int64 = {gte: 1, lte: 100}]; // 每一页的行数
}

// 定时任务分页响应
message PageBaseJobResponse {
  repeated BaseJob base_jobs = 1 [(gnostic.openapi.v3.property) = {description: "分页数据"}]; // 分页数据

  int32 total = 2 [(gnostic.openapi.v3.property) = {description: "总数"}]; // 总数
}

// 查询定时任务请求参数
message GetBaseJobRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID
}

// 定时任务表单
message BaseJobForm {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID

  string name = 2 [(gnostic.openapi.v3.property) = {description: "任务名称"}, (buf.validate.field).cel = {id: "system.admin.base.job.entity.name.length" message: "任务名称不能为空且不超过 50 个字符" expression: "this.size() > 0 && this.size() <= 50"}]; // 任务名称

  string invoke_target = 3 [(gnostic.openapi.v3.property) = {description: "调用目标"}, (buf.validate.field).cel = {id: "system.admin.base.job.entity.invoke_target.length" message: "调用目标不能为空且不超过 100 个字符" expression: "this.size() > 0 && this.size() <= 100"}]; // 调用目标

  repeated BaseJobArgs args = 4 [(gnostic.openapi.v3.property) = {description: "目标参数"}]; // 目标参数

  string cron_expression = 5 [(gnostic.openapi.v3.property) = {description: "cron表达式"}, (buf.validate.field).cel = {id: "system.admin.base.job.entity.cron_expression.length" message: "cron表达式不能为空且不超过 50 个字符" expression: "this.size() > 0 && this.size() <= 50"}]; // cron表达式

  .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态"}, (buf.validate.field).enum = {defined_only: true}]; // 状态

  repeated BaseI18n i18ns = 7 [(gnostic.openapi.v3.property) = {description: "定时任务名称多语言翻译"}]; // 定时任务名称多语言翻译
}

// 创建定时任务请求参数
message CreateBaseJobRequest {
  BaseJobForm base_job = 1 [(gnostic.openapi.v3.property) = {description: "定时任务表单"}, (buf.validate.field).required = true]; // 定时任务表单
}

// 更新定时任务请求参数
message UpdateBaseJobRequest {
  BaseJobForm base_job = 1 [(gnostic.openapi.v3.property) = {description: "定时任务表单"}, (buf.validate.field).required = true]; // 定时任务表单
}

// 删除定时任务请求参数
message DeleteBaseJobRequest {
  string id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID列表"}]; // 任务ID列表
}

// 设置定时任务状态请求参数
message SetBaseJobStatusRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID

  int32 status = 2 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态
}

// 启动定时任务请求参数
message StartBaseJobRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID
}

// 停止定时任务请求参数
message StopBaseJobRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID
}

// 执行任务请求参数
message ExecuteBaseJobRequest {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID
}

// 定时任务参数
message BaseJobArgs {
  string key = 1 [(gnostic.openapi.v3.property) = {description: "参数"}, (buf.validate.field).cel = {id: "system.admin.base.job.entity.args.key.required" message: "所有参数必须填写key" expression: "this.size() > 0"}]; // 参数

  string value = 2 [(gnostic.openapi.v3.property) = {description: "值"}]; // 值
}

// 定时任务
message BaseJob {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "任务ID"}]; // 任务ID

  string name = 2 [(gnostic.openapi.v3.property) = {description: "任务名称"}]; // 任务名称

  string invoke_target = 3 [(gnostic.openapi.v3.property) = {description: "调用目标"}]; // 调用目标

  repeated BaseJobArgs args = 4 [(gnostic.openapi.v3.property) = {description: "目标参数"}]; // 目标参数

  string cron_expression = 5 [(gnostic.openapi.v3.property) = {description: "cron表达式"}]; // cron表达式

  int32 entry_id = 6 [(gnostic.openapi.v3.property) = {description: "job启动时返回的id"}]; // job启动时返回的id

  .common.v1.Status status = 100 [(gnostic.openapi.v3.property) = {description: "状态"}]; // 状态

  string created_at = 200 [(gnostic.openapi.v3.property) = {description: "创建时间"}]; // 创建时间

  string updated_at = 201 [(gnostic.openapi.v3.property) = {description: "更新时间"}]; // 更新时间

  repeated BaseI18n i18ns = 202 [(gnostic.openapi.v3.property) = {description: "定时任务名称多语言翻译"}]; // 定时任务名称多语言翻译
}
