// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/oauth.proto

/* eslint-disable */
import type { PasswordCrypto } from "../../common/v1/types";
import type { Empty } from "../../google/protobuf/empty";
import type { LoginStatus } from "./login";

/** 个人中心三方账号绑定列表查询条件 */
export interface ListOauthBindingRequest {
}

/** 个人中心三方账号绑定列表响应 */
export interface ListOauthBindingResponse {
  /** 三方账号绑定列表 */
  bindings: OauthBinding[];
}

/** 三方登录方式查询条件 */
export interface ListOauthProviderRequest {
}

/** 三方登录方式查询结果 */
export interface ListOauthProviderResponse {
  /** 三方登录方式列表 */
  providers: OauthProvider[];
}

/** 三方登录授权地址创建条件 */
export interface CreateOauthAuthorizationRequest {
  /** 登录方式标识 */
  provider: string;
  /** 三方登录完成后的前端接收地址 */
  redirect_url: string;
}

/** 三方登录授权地址创建结果 */
export interface CreateOauthAuthorizationResponse {
  /** 三方授权地址 */
  authorization_url: string;
}

/** 个人中心三方账号绑定授权地址创建条件 */
export interface CreateOauthBindingAuthorizationRequest {
  /** 登录方式标识 */
  provider: string;
  /** 绑定完成后回跳地址 */
  redirect_url: string;
}

/** 个人中心三方账号绑定授权地址创建响应 */
export interface CreateOauthBindingAuthorizationResponse {
  /** 三方授权地址 */
  authorization_url: string;
}

/** 三方登录会话创建请求 */
export interface CreateOauthSessionRequest {
  /** 登录方式标识 */
  provider: string;
  /** 三方授权码 */
  code: string;
}

/** 绑定已有账号的三方登录会话创建条件 */
export interface BindOauthSessionRequest {
  /** 登录方式标识 */
  provider: string;
  /** 三方授权码 */
  code: string;
  /** 租户编码 */
  tenant_code: string;
  /** 用户名 */
  user_name: string;
  /** 用户密码 */
  password:
    | PasswordCrypto
    | undefined;
  /** 验证码 */
  captcha_code: string;
  /** 验证码Id */
  captcha_id: string;
}

/** 三方登录会话创建响应 */
export interface CreateOauthSessionResponse {
  /** 访问令牌，必选项。 */
  access_token: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refresh_token: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  token_type: string;
  /** 令牌有效时间，单位为秒。 */
  expires_in: number;
  /** 是否需要绑定已有账号。 */
  binding_required: boolean;
  /** 登录认证状态 */
  status: LoginStatus;
  /** 多因素认证挑战ID */
  mfa_challenge_id: string;
  /** 多因素认证绑定临时票据 */
  mfa_setup_ticket: string;
  /** 多因素认证挑战或绑定票据有效时间，单位秒 */
  mfa_expires_in: number;
  /** 多因素认证方式：totp、webauthn */
  mfa_method: string;
  /** WebAuthn认证选项JSON */
  mfa_webauthn_options_json: string;
  /** 当前登录策略允许的MFA设备免验证天数 */
  mfa_remember_days: number;
}

/** 三方登录回调请求 */
export interface HandleOauthCallbackRequest {
  /** 登录方式标识 */
  provider: string;
  /** 三方授权码 */
  code: string;
  /** 授权状态码 */
  state: string;
  /** 三方错误码 */
  error: string;
  /** 三方错误描述 */
  error_description: string;
}

/** 三方登录回调结果 */
export interface HandleOauthCallbackResponse {
}

/** 三方登录票据兑换请求 */
export interface ExchangeOauthTicketRequest {
  /** 三方登录票据 */
  ticket: string;
}

/** 三方登录票据兑换结果 */
export interface ExchangeOauthTicketResponse {
  /** 访问令牌，必选项。 */
  access_token: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refresh_token: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  token_type: string;
  /** 令牌有效时间，单位为秒。 */
  expires_in: number;
  /** 登录认证状态 */
  status: LoginStatus;
  /** 多因素认证挑战ID */
  mfa_challenge_id: string;
  /** 多因素认证绑定临时票据 */
  mfa_setup_ticket: string;
  /** 多因素认证挑战或绑定票据有效时间，单位秒 */
  mfa_expires_in: number;
  /** 多因素认证方式：totp、webauthn */
  mfa_method: string;
  /** WebAuthn认证选项JSON */
  mfa_webauthn_options_json: string;
  /** 当前登录策略允许的MFA设备免验证天数 */
  mfa_remember_days: number;
}

/** 个人中心三方账号绑定回调请求 */
export interface HandleOauthBindingCallbackRequest {
  /** 登录方式标识 */
  provider: string;
  /** 三方授权码 */
  code: string;
  /** 授权状态码 */
  state: string;
  /** 三方错误码 */
  error: string;
  /** 三方错误描述 */
  error_description: string;
}

/** 个人中心三方账号绑定回调响应 */
export interface HandleOauthBindingCallbackResponse {
}

/** 个人中心三方账号解绑条件 */
export interface UnbindOauthAccountRequest {
  /** 登录方式标识 */
  provider: string;
}

/** 三方登录方式信息 */
export interface OauthProvider {
  /** 登录方式标识 */
  provider: string;
}

/** 个人中心三方账号绑定信息 */
export interface OauthBinding {
  /** 登录方式标识 */
  provider: string;
  /** 是否已绑定 */
  bound: boolean;
}

/** Base三方登录公共服务 */
export interface OauthService {
  /** 查询个人中心三方账号绑定列表 */
  ListOauthBinding(request: ListOauthBindingRequest): Promise<ListOauthBindingResponse>;
  /** 查询三方登录方式 */
  ListOauthProvider(request: ListOauthProviderRequest): Promise<ListOauthProviderResponse>;
  /** 创建三方登录授权地址 */
  CreateOauthAuthorization(request: CreateOauthAuthorizationRequest): Promise<CreateOauthAuthorizationResponse>;
  /** 创建个人中心三方账号绑定授权地址 */
  CreateOauthBindingAuthorization(
    request: CreateOauthBindingAuthorizationRequest,
  ): Promise<CreateOauthBindingAuthorizationResponse>;
  /** 创建三方登录会话 */
  CreateOauthSession(request: CreateOauthSessionRequest): Promise<CreateOauthSessionResponse>;
  /** 绑定已有账号并创建三方登录会话 */
  BindOauthSession(request: BindOauthSessionRequest): Promise<CreateOauthSessionResponse>;
  /** 处理三方登录回调 */
  HandleOauthCallback(request: HandleOauthCallbackRequest): Promise<HandleOauthCallbackResponse>;
  /** 兑换三方登录票据 */
  ExchangeOauthTicket(request: ExchangeOauthTicketRequest): Promise<ExchangeOauthTicketResponse>;
  /** 处理个人中心三方账号绑定回调 */
  HandleOauthBindingCallback(request: HandleOauthBindingCallbackRequest): Promise<HandleOauthBindingCallbackResponse>;
  /** 解绑个人中心三方账号 */
  UnbindOauthAccount(request: UnbindOauthAccountRequest): Promise<Empty>;
}
