// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/notification.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/**
 * MessagePriority 定义站内信在收件箱和投递队列中的处理优先级。
 * 数值越高表示业务紧急程度越高，未指定值由业务层按分类默认值补齐。
 */
export enum MessagePriority {
  /** MESSAGE_PRIORITY_UNSPECIFIED - 未指定消息优先级。 */
  MESSAGE_PRIORITY_UNSPECIFIED = 0,
  /** MESSAGE_PRIORITY_NORMAL - 普通消息。 */
  MESSAGE_PRIORITY_NORMAL = 1,
  /** MESSAGE_PRIORITY_IMPORTANT - 重要消息。 */
  MESSAGE_PRIORITY_IMPORTANT = 2,
  /** MESSAGE_PRIORITY_URGENT - 紧急消息。 */
  MESSAGE_PRIORITY_URGENT = 3,
}

/**
 * MessageContentFormat 定义消息正文的编码格式和前端渲染方式。
 * 富文本和 Markdown 在入库前必须经过服务端安全清洗，不能直接信任客户端内容。
 */
export enum MessageContentFormat {
  /** MESSAGE_CONTENT_FORMAT_UNSPECIFIED - 未指定正文格式。 */
  MESSAGE_CONTENT_FORMAT_UNSPECIFIED = 0,
  /** MESSAGE_CONTENT_FORMAT_PLAIN_TEXT - 纯文本。 */
  MESSAGE_CONTENT_FORMAT_PLAIN_TEXT = 1,
  /** MESSAGE_CONTENT_FORMAT_SAFE_MARKDOWN - 安全 Markdown。 */
  MESSAGE_CONTENT_FORMAT_SAFE_MARKDOWN = 2,
  /** MESSAGE_CONTENT_FORMAT_RICH_TEXT - 富文本。 */
  MESSAGE_CONTENT_FORMAT_RICH_TEXT = 3,
}

/**
 * MessageActionType 定义用户点击站内信后执行的导航动作。
 * 动作目标由服务端校验为已注册视图键，避免将任意 URL 注入消息正文。
 */
export enum MessageActionType {
  /** MESSAGE_ACTION_TYPE_UNSPECIFIED - 无动作。 */
  MESSAGE_ACTION_TYPE_UNSPECIFIED = 0,
  /** MESSAGE_ACTION_TYPE_VIEW_KEY - 跳转到视图键。 */
  MESSAGE_ACTION_TYPE_VIEW_KEY = 1,
}

/**
 * MessageStatus 定义消息从草稿、发布、撤回到归档的生命周期状态。
 * 状态迁移由管理端业务用例控制，投递任务状态不直接改变消息主状态。
 */
export enum MessageStatus {
  /** MESSAGE_STATUS_UNSPECIFIED - 未指定消息状态。 */
  MESSAGE_STATUS_UNSPECIFIED = 0,
  /** MESSAGE_STATUS_DRAFT - 草稿。 */
  MESSAGE_STATUS_DRAFT = 1,
  /** MESSAGE_STATUS_SCHEDULED - 已安排定时发布。 */
  MESSAGE_STATUS_SCHEDULED = 2,
  /** MESSAGE_STATUS_PUBLISHING - 发布中。 */
  MESSAGE_STATUS_PUBLISHING = 3,
  /** MESSAGE_STATUS_PUBLISHED - 已发布。 */
  MESSAGE_STATUS_PUBLISHED = 4,
  /** MESSAGE_STATUS_REVOKED - 已撤回。 */
  MESSAGE_STATUS_REVOKED = 5,
  /** MESSAGE_STATUS_ARCHIVED - 已归档。 */
  MESSAGE_STATUS_ARCHIVED = 6,
}

/**
 * MessageSourceType 标识消息由管理端、系统任务还是业务模块产生。
 * 来源用于审计、展示发送者和排查异步投递问题。
 */
export enum MessageSourceType {
  /** MESSAGE_SOURCE_TYPE_UNSPECIFIED - 未指定消息来源。 */
  MESSAGE_SOURCE_TYPE_UNSPECIFIED = 0,
  /** MESSAGE_SOURCE_TYPE_ADMIN - 管理端发送。 */
  MESSAGE_SOURCE_TYPE_ADMIN = 1,
  /** MESSAGE_SOURCE_TYPE_SYSTEM - 系统发送。 */
  MESSAGE_SOURCE_TYPE_SYSTEM = 2,
  /** MESSAGE_SOURCE_TYPE_BUSINESS - 业务模块发送。 */
  MESSAGE_SOURCE_TYPE_BUSINESS = 3,
}

/**
 * MessageSenderType 标识站内信对应的发送主体类型。
 * 用户发送消息必须使用当前认证身份，系统发送消息由受信内部调用创建。
 */
export enum MessageSenderType {
  /** MESSAGE_SENDER_TYPE_UNSPECIFIED - 未指定发送者类型。 */
  MESSAGE_SENDER_TYPE_UNSPECIFIED = 0,
  /** MESSAGE_SENDER_TYPE_USER - 用户发送。 */
  MESSAGE_SENDER_TYPE_USER = 1,
  /** MESSAGE_SENDER_TYPE_SYSTEM - 系统发送。 */
  MESSAGE_SENDER_TYPE_SYSTEM = 2,
}

/**
 * MessageAudienceType 定义消息受众的解析范围。
 * 受众编号按类型解释，租户全员使用 0，部门受众可选择是否包含子部门。
 */
export enum MessageAudienceType {
  /** MESSAGE_AUDIENCE_TYPE_UNSPECIFIED - 未指定受众类型。 */
  MESSAGE_AUDIENCE_TYPE_UNSPECIFIED = 0,
  /** MESSAGE_AUDIENCE_TYPE_USER - 指定用户。 */
  MESSAGE_AUDIENCE_TYPE_USER = 1,
  /** MESSAGE_AUDIENCE_TYPE_ROLE - 指定角色。 */
  MESSAGE_AUDIENCE_TYPE_ROLE = 2,
  /** MESSAGE_AUDIENCE_TYPE_DEPT - 指定部门。 */
  MESSAGE_AUDIENCE_TYPE_DEPT = 3,
  /** MESSAGE_AUDIENCE_TYPE_POST - 指定岗位。 */
  MESSAGE_AUDIENCE_TYPE_POST = 4,
  /** MESSAGE_AUDIENCE_TYPE_TENANT - 租户全员。 */
  MESSAGE_AUDIENCE_TYPE_TENANT = 5,
}

/**
 * MessageDispatchStatus 定义单个受众投递任务的处理状态。
 * 状态用于租约恢复、失败重试和最终一致性统计，不代表用户是否已阅读消息。
 */
export enum MessageDispatchStatus {
  /** MESSAGE_DISPATCH_STATUS_UNSPECIFIED - 未指定投递状态。 */
  MESSAGE_DISPATCH_STATUS_UNSPECIFIED = 0,
  /** MESSAGE_DISPATCH_STATUS_WAITING - 等待发布。 */
  MESSAGE_DISPATCH_STATUS_WAITING = 1,
  /** MESSAGE_DISPATCH_STATUS_PENDING - 等待处理。 */
  MESSAGE_DISPATCH_STATUS_PENDING = 2,
  /** MESSAGE_DISPATCH_STATUS_RUNNING - 处理中。 */
  MESSAGE_DISPATCH_STATUS_RUNNING = 3,
  /** MESSAGE_DISPATCH_STATUS_SUCCEEDED - 投递成功。 */
  MESSAGE_DISPATCH_STATUS_SUCCEEDED = 4,
  /** MESSAGE_DISPATCH_STATUS_FAILED - 投递失败。 */
  MESSAGE_DISPATCH_STATUS_FAILED = 5,
  /** MESSAGE_DISPATCH_STATUS_CANCELLED - 已取消。 */
  MESSAGE_DISPATCH_STATUS_CANCELLED = 6,
}

/**
 * NotificationView 定义当前用户收件箱的筛选视图。
 * 视图只影响查询范围，不改变消息或投递记录的持久化状态。
 */
export enum NotificationView {
  /** NOTIFICATION_VIEW_UNSPECIFIED - 未指定收件箱视图，按全部收件箱消息处理。 */
  NOTIFICATION_VIEW_UNSPECIFIED = 0,
  /** NOTIFICATION_VIEW_INBOX - 全部收件箱消息。 */
  NOTIFICATION_VIEW_INBOX = 1,
  /** NOTIFICATION_VIEW_UNREAD - 未读消息。 */
  NOTIFICATION_VIEW_UNREAD = 2,
  /** NOTIFICATION_VIEW_ARCHIVED - 已归档消息。 */
  NOTIFICATION_VIEW_ARCHIVED = 3,
}

/** 当前用户收件箱分页查询条件。 */
export interface PageNotificationRequest {
  /** 收件箱视图 */
  view: NotificationView;
  /** 消息分类ID */
  category_id?:
    | number
    | undefined;
  /** 消息优先级 */
  priority?:
    | MessagePriority
    | undefined;
  /** 上一页最后投递ID */
  cursor_id: number;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 当前用户收件箱分页响应。 */
export interface PageNotificationResponse {
  /** 消息列表 */
  notifications: Notification[];
  /** 总数 */
  total: number;
  /** 下一页游标 */
  next_cursor_id: number;
  /** 是否还有下一页 */
  has_more: boolean;
}

/** 消息分类列表查询条件。 */
export interface ListNotificationCategoriesRequest {
}

/** 消息分类列表响应。 */
export interface ListNotificationCategoriesResponse {
  /** 消息分类列表 */
  categories: NotificationCategory[];
}

/** 当前可用的消息分类。 */
export interface NotificationCategory {
  /** 消息分类ID */
  id: number;
  /** 分类编码 */
  code: string;
  /** 分类名称 */
  name: string;
  /** 分类图标 */
  icon: string;
  /** 分类颜色 */
  color: string;
  /** 排序 */
  sort: number;
}

/** 消息详情查询条件。 */
export interface GetNotificationRequest {
  /** 投递ID */
  id: number;
}

/** 当前用户未读汇总查询条件。 */
export interface GetNotificationSummaryRequest {
}

/** 当前用户未读汇总。 */
export interface NotificationSummary {
  /** 未读总数 */
  unread_total: number;
  /** 最新投递ID */
  latest_delivery_id: number;
  /** 分类未读数 */
  category_unread: NotificationCategoryUnread[];
}

/** 当前用户单个分类的未读数量。 */
export interface NotificationCategoryUnread {
  /** 消息分类ID */
  category_id: number;
  /** 分类未读数 */
  unread_total: number;
}

/** 批量标记消息已读请求。 */
export interface MarkNotificationReadRequest {
  /** 投递ID列表 */
  ids: number[];
}

/** 批量标记消息未读请求。 */
export interface MarkNotificationUnreadRequest {
  /** 投递ID列表 */
  ids: number[];
}

/** 全部已读请求。 */
export interface MarkAllNotificationReadRequest {
  /** 已读水位线投递ID */
  before_delivery_id: number;
}

/** 归档消息请求。 */
export interface ArchiveNotificationRequest {
  /** 投递ID */
  id: number;
}

/** 恢复归档消息请求。 */
export interface RestoreNotificationRequest {
  /** 投递ID */
  id: number;
}

/** 删除消息请求。 */
export interface DeleteNotificationRequest {
  /** 投递ID */
  id: number;
}

/** 当前用户消息。 */
export interface Notification {
  /** 投递ID */
  id: number;
  /** 消息ID */
  message_id: number;
  /** 分类ID */
  category_id: number;
  /** 分类名称 */
  category_name: string;
  /** 分类图标 */
  category_icon: string;
  /** 分类颜色 */
  category_color: string;
  /** 消息优先级 */
  priority: MessagePriority;
  /** 消息标题 */
  title: string;
  /** 消息正文 */
  content: string;
  /** 正文格式 */
  content_format: MessageContentFormat;
  /** 动作类型 */
  action_type: MessageActionType;
  /** 动作目标 */
  action_target: string;
  /** 动作参数JSON */
  action_params: string;
  /** 发送者名称 */
  sender_name: string;
  /** 接收时间 */
  received_at: string;
  /** 已读时间 */
  read_at: string;
  /** 归档时间 */
  archived_at: string;
  /** 过期时间 */
  expires_at: string;
  /** 是否允许归档 */
  allow_archive: boolean;
  /** 是否允许删除 */
  allow_delete: boolean;
}

/** Base站内信通知服务，提供当前用户的收件箱能力。 */
export interface NotificationService {
  /** 分页查询当前用户收件箱。 */
  PageNotification(request: PageNotificationRequest): Promise<PageNotificationResponse>;
  /** 查询消息分类列表。 */
  ListNotificationCategories(request: ListNotificationCategoriesRequest): Promise<ListNotificationCategoriesResponse>;
  /** 查询当前用户未读汇总。 */
  GetNotificationSummary(request: GetNotificationSummaryRequest): Promise<NotificationSummary>;
  /** 查询当前用户消息详情。 */
  GetNotification(request: GetNotificationRequest): Promise<Notification>;
  /** 标记消息为已读。 */
  MarkNotificationRead(request: MarkNotificationReadRequest): Promise<Empty>;
  /** 标记消息为未读。 */
  MarkNotificationUnread(request: MarkNotificationUnreadRequest): Promise<Empty>;
  /** 标记水位线之前的全部消息为已读。 */
  MarkAllNotificationRead(request: MarkAllNotificationReadRequest): Promise<Empty>;
  /** 归档消息。 */
  ArchiveNotification(request: ArchiveNotificationRequest): Promise<Empty>;
  /** 恢复已归档消息。 */
  RestoreNotification(request: RestoreNotificationRequest): Promise<Empty>;
  /** 从个人收件箱删除消息。 */
  DeleteNotification(request: DeleteNotificationRequest): Promise<Empty>;
}
