// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: base/v1/file.proto

/* eslint-disable */
import type { BytesValue } from "../../google/protobuf/wrappers";

/** 文件访问方式。 */
export enum BaseFileAccessMode {
  /** BASE_FILE_ACCESS_MODE_UNSPECIFIED - 未指定文件访问方式，服务端按授权访问处理。 */
  BASE_FILE_ACCESS_MODE_UNSPECIFIED = 0,
  /** BASE_FILE_ACCESS_MODE_PUBLIC - 允许匿名公开访问。 */
  BASE_FILE_ACCESS_MODE_PUBLIC = 1,
  /** BASE_FILE_ACCESS_MODE_AUTHORIZED - 必须携带有效访问令牌。 */
  BASE_FILE_ACCESS_MODE_AUTHORIZED = 2,
}

/** 批量上传文件请求参数 */
export interface MultiUploadFileRequest {
  /** 文件名 */
  files: UploadFileInfo[];
}

/** 批量上传文件响应 */
export interface MultiUploadFileResponse {
  /** 文件上传结果 */
  files: FileInfo[];
}

/** 单文件上传请求参数 */
export interface UploadFileRequest {
  /** 上传文件信息 */
  file: UploadFileInfo | undefined;
}

/** 上传文件信息 */
export interface UploadFileInfo {
  /** 文件名 */
  name: string;
  /** 文件扩展名 */
  extname: string;
  /** 文件路径 */
  path: string;
  /** 二进制内容将通过 base64 编码传输 */
  content: Uint8Array;
  /** 文件访问方式，未指定时默认需要访问令牌 */
  access_mode: BaseFileAccessMode;
}

/** 下载文件请求参数 */
export interface DownloadFileRequest {
  /** 文件名 */
  name: string;
  /** 文件路径 */
  path: string;
}

/** File信息 */
export interface FileInfo {
  /** 文件路径 */
  url: string;
  /** 文件名 */
  name: string;
  /** 文件扩展名 */
  extname: string;
}

/** Base文件服务 */
export interface FileService {
  /** 多个文件上传 */
  MultiUploadFile(request: MultiUploadFileRequest): Promise<MultiUploadFileResponse>;
  /** 单个文件上传 */
  UploadFile(request: UploadFileRequest): Promise<FileInfo>;
  /** 下载文件 */
  DownloadFile(request: DownloadFileRequest): Promise<BytesValue>;
}
