// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/file.proto

/* eslint-disable */
import type { BytesValue } from "../../google/protobuf/wrappers";

/** 批量上传文件请求参数 */
export interface MultiUploadFileRequest {
  /** 文件名 */
  files: UploadFileInfo[];
}

/** 批量上传文件响应 */
export interface MultiUploadFileResponse {
  /** 文件上传结果 */
  files: FileInfo[];
}

/** 单文件上传请求参数 */
export interface UploadFileRequest {
  /** 上传文件信息 */
  file: UploadFileInfo | undefined;
}

/** 上传文件信息 */
export interface UploadFileInfo {
  /** 文件名 */
  name: string;
  /** 文件扩展名 */
  extname: string;
  /** 文件路径 */
  path: string;
  /** 二进制内容将通过 base64 编码传输 */
  content: Uint8Array;
}

/** 下载文件请求参数 */
export interface DownloadFileRequest {
  /** 文件名 */
  name: string;
  /** 文件路径 */
  path: string;
}

/** File信息 */
export interface FileInfo {
  /** 文件路径 */
  url: string;
  /** 文件名 */
  name: string;
  /** 文件扩展名 */
  extname: string;
}

/** Base文件服务 */
export interface FileService {
  /** 多个文件上传 */
  MultiUploadFile(request: MultiUploadFileRequest): Promise<MultiUploadFileResponse>;
  /** 单个文件上传 */
  UploadFile(request: UploadFileRequest): Promise<FileInfo>;
  /** 下载文件 */
  DownloadFile(request: DownloadFileRequest): Promise<BytesValue>;
}
