// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/language.proto

/* eslint-disable */

/** 查询语言选项请求参数。 */
export interface OptionLanguageRequest {
}

/** 语言选择项。 */
export interface LanguageItem {
  /** 标准语言代码 */
  language_code: string;
  /** 本地语言名称 */
  native_name: string;
}

/** 当前支持的语言选项查询结果。 */
export interface OptionLanguageResponse {
  /** 当前支持的语言列表 */
  languages: LanguageItem[];
}

/** Base语言公共服务。 */
export interface LanguageService {
  /** 查询当前支持的语言选项。 */
  OptionLanguage(request: OptionLanguageRequest): Promise<OptionLanguageResponse>;
}
