// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/mfa.proto

/* eslint-disable */
import type { PasswordCrypto } from "../../common/v1/types";
import type { Empty } from "../../google/protobuf/empty";
import type { LoginResponse } from "./login";

/** 多因素认证校验请求。 */
export interface VerifyMfaRequest {
  /** 多因素认证挑战ID */
  challenge_id: string;
  /** TOTP动态口令 */
  code: string;
  /** 一次性恢复码 */
  recovery_code: string;
  /** WebAuthn认证响应JSON */
  webauthn_response_json: string;
  /** 是否记住当前设备 */
  remember_device: boolean;
}

/** 登录强制绑定多因素认证请求。 */
export interface BeginMfaEnrollmentRequest {
  /** 强制绑定临时票据 */
  setup_ticket: string;
}

/** 登录强制绑定多因素认证响应。 */
export interface BeginMfaEnrollmentResponse {
  /** 绑定临时票据 */
  setup_ticket: string;
  /** Authenticator应用使用的otpauth地址 */
  otpauth_uri: string;
  /** 绑定临时票据有效时间，单位秒 */
  expires_in: number;
  /** 多因素认证方式：totp、webauthn */
  method: string;
  /** WebAuthn注册选项JSON */
  webauthn_options_json: string;
}

/** 登录强制绑定多因素认证确认请求。 */
export interface ConfirmMfaEnrollmentRequest {
  /** 绑定临时票据 */
  setup_ticket: string;
  /** TOTP动态口令 */
  code: string;
  /** WebAuthn注册响应JSON */
  webauthn_response_json: string;
}

/** 登录强制绑定多因素认证确认响应。 */
export interface ConfirmMfaEnrollmentResponse {
  /** 是否启用成功 */
  enabled: boolean;
  /** 一次性恢复码，仅本次返回 */
  recovery_codes: string[];
}

/** 查询当前用户多因素认证状态请求。 */
export interface GetMfaStatusRequest {
}

/** 多因素认证状态响应。 */
export interface MfaStatusResponse {
  /** 是否已启用多因素认证 */
  enabled: boolean;
  /** 全局多因素认证策略 */
  policy: string;
  /** 认证方式 */
  method: string;
}

/** 开始绑定多因素认证请求。 */
export interface BeginMfaSetupRequest {
  /** 当前登录密码 */
  password:
    | PasswordCrypto
    | undefined;
  /** 强制绑定场景下的临时票据 */
  setup_ticket: string;
}

/** 开始绑定多因素认证响应。 */
export interface BeginMfaSetupResponse {
  /** 绑定临时票据 */
  setup_ticket: string;
  /** Authenticator 应用使用的 otpauth 地址 */
  otpauth_uri: string;
  /** 绑定临时票据有效时间，单位秒 */
  expires_in: number;
  /** 多因素认证方式：totp、webauthn */
  method: string;
  /** WebAuthn 注册选项 JSON */
  webauthn_options_json: string;
}

/** 确认绑定多因素认证请求。 */
export interface ConfirmMfaSetupRequest {
  /** 绑定临时票据 */
  setup_ticket: string;
  /** TOTP 动态口令 */
  code: string;
  /** WebAuthn 注册响应 JSON */
  webauthn_response_json: string;
}

/** 确认绑定多因素认证响应。 */
export interface ConfirmMfaSetupResponse {
  /** 是否启用成功 */
  enabled: boolean;
  /** 一次性恢复码，仅本次返回 */
  recovery_codes: string[];
}

/** 开始禁用 WebAuthn 多因素认证请求。 */
export interface BeginMfaDisableRequest {
}

/** 开始禁用 WebAuthn 多因素认证响应。 */
export interface BeginMfaDisableResponse {
  /** WebAuthn 禁用挑战 ID */
  challenge_id: string;
  /** WebAuthn 禁用挑战有效时间，单位秒 */
  expires_in: number;
  /** WebAuthn 验证选项 JSON */
  webauthn_options_json: string;
}

/** 禁用多因素认证请求。 */
export interface DisableMfaRequest {
  /** 当前登录密码 */
  password:
    | PasswordCrypto
    | undefined;
  /** TOTP 动态口令 */
  code: string;
  /** WebAuthn 禁用挑战 ID */
  webauthn_challenge_id: string;
  /** WebAuthn 验证响应 JSON */
  webauthn_response_json: string;
  /** 一次性恢复码 */
  recovery_code: string;
}

/** 重新生成恢复码请求。 */
export interface RegenerateMfaRecoveryCodesRequest {
  /** TOTP 动态口令 */
  code: string;
}

/** 恢复码响应。 */
export interface RecoveryCodesResponse {
  /** 一次性恢复码，仅本次返回 */
  recovery_codes: string[];
}

/** Base 多因素认证公共服务。 */
export interface MfaService {
  /** 校验多因素认证 */
  VerifyMfa(request: VerifyMfaRequest): Promise<LoginResponse>;
  /** 开始登录强制绑定配置的 MFA 方式 */
  BeginMfaEnrollment(request: BeginMfaEnrollmentRequest): Promise<BeginMfaEnrollmentResponse>;
  /** 确认登录强制绑定配置的 MFA 方式 */
  ConfirmMfaEnrollment(request: ConfirmMfaEnrollmentRequest): Promise<ConfirmMfaEnrollmentResponse>;
  /** 查询当前用户多因素认证状态。 */
  GetMfaStatus(request: GetMfaStatusRequest): Promise<MfaStatusResponse>;
  /** 开始绑定当前用户的多因素认证方式。 */
  BeginMfaSetup(request: BeginMfaSetupRequest): Promise<BeginMfaSetupResponse>;
  /** 确认绑定当前用户的多因素认证方式。 */
  ConfirmMfaSetup(request: ConfirmMfaSetupRequest): Promise<ConfirmMfaSetupResponse>;
  /** 开始禁用 WebAuthn 多因素认证的 Passkey 验证。 */
  BeginMfaDisable(request: BeginMfaDisableRequest): Promise<BeginMfaDisableResponse>;
  /** 禁用当前用户的多因素认证。 */
  DisableMfa(request: DisableMfaRequest): Promise<Empty>;
  /** 重新生成当前用户的多因素认证恢复码。 */
  RegenerateMfaRecoveryCodes(request: RegenerateMfaRecoveryCodesRequest): Promise<RecoveryCodesResponse>;
}
