// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/oauth_client.proto

/* eslint-disable */

/** 客户端凭据令牌请求。 */
export interface IssueOauthClientTokenRequest {
  /** 客户端标识 */
  client_id: string;
  /** 客户端密钥 */
  client_secret: string;
  /** 授权类型 */
  grant_type: string;
}

/** 客户端凭据令牌响应。 */
export interface IssueOauthClientTokenResponse {
  /** 访问令牌 */
  access_token: string;
  /** 令牌类型 */
  token_type: string;
  /** 令牌有效时间，单位为秒 */
  expires_in: number;
}

/** Base开放授权客户端令牌服务。 */
export interface OauthClientService {
  /** 使用客户端凭据换取访问令牌。 */
  IssueOauthClientToken(request: IssueOauthClientTokenRequest): Promise<IssueOauthClientTokenResponse>;
}
