// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: base/v1/mcp.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/** MCP请求参数 */
export interface HandleMcpRequest {
  /** 服务筛选关键字，必填，支持 app、admin 或任意服务关键字 */
  terminal: string;
}

/** Base MCP服务 */
export interface McpService {
  /** 处理MCP Streamable HTTP请求 */
  HandleMcp(request: HandleMcpRequest): Promise<Empty>;
}
