// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/google/wire"
	"github.com/liujitcn/kratos-admin/backend"
	"github.com/liujitcn/kratos-admin/backend/adapter/core"
	"github.com/liujitcn/kratos-admin/backend/adapter/kit"
	kratoscore "github.com/liujitcn/kratos-core"
	biz2 "github.com/liujitcn/kratos-core/biz"
	"github.com/liujitcn/kratos-core/config"
	"github.com/liujitcn/kratos-core/data"
	"github.com/liujitcn/kratos-core/job"
	"github.com/liujitcn/kratos-core/mcp"
	"github.com/liujitcn/kratos-core/module"
	queue2 "github.com/liujitcn/kratos-core/queue"
	"github.com/liujitcn/kratos-core/resource"
	"github.com/liujitcn/kratos-core/resource/biz"
	"github.com/liujitcn/kratos-core/resource/i18n"
	"github.com/liujitcn/kratos-core/resource/migration"
	"github.com/liujitcn/kratos-core/resource/openapi"
	"github.com/liujitcn/kratos-core/server"
	"github.com/liujitcn/kratos-core/sse"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"
	"github.com/liujitcn/kratos-kit/translator"

	_ "github.com/liujitcn/kratos-kit/database/gorm/driver/mysql"

	_ "github.com/liujitcn/kratos-kit/logger/zap"

	_ "github.com/liujitcn/kratos-kit/registry/consul"
)

// Injectors from wire.go:

// NewApp 通过 Core、Admin 和宿主 ProviderSet 注入并创建应用。
func NewApp(ctx *bootstrap.Context) (*kratos.App, func(), error) {
	configv1Bootstrap, err := config.ParseBootstrap(ctx)
	if err != nil {
		return nil, nil, err
	}
	v, err := config.ParseDatabase(configv1Bootstrap)
	if err != nil {
		return nil, nil, err
	}
	adminResources := backend.NewModuleResources()
	resources := provideResources(adminResources)
	models := module.NewModels(resources)
	v2, cleanup, err := data.NewClients(v, models)
	if err != nil {
		return nil, nil, err
	}
	migrations := module.NewMigrations(resources)
	migrationMigration, err := migration.NewMigration(ctx, v2, migrations)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	openAPI := module.NewOpenAPIFromResources(resources)
	registry, err := openapi.NewRegistry(openAPI)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	transaction, err := core.NewTransaction(v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	apiStoreAdapter, err := core.NewAPIStoreAdapter(v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseAPICase := biz.NewBaseAPICase(apiStoreAdapter)
	permissionStoreAdapter, err := core.NewPermissionStoreAdapter(v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseTenantCase := biz.NewBaseTenantCase(transaction, permissionStoreAdapter)
	engine, err := biz2.NewAuthzEngine()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	casbinRuleCase, err := biz.NewCasbinRuleCase(permissionStoreAdapter, baseAPICase, engine)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	syncResult, err := resource.NewSyncResult(ctx, migrationMigration, registry, transaction, baseAPICase, baseTenantCase, casbinRuleCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appInfo, err := config.ParseAppInfo(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authentication_Jwt, err := config.ParseAuthnJWT(configv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authenticator, err := biz2.NewAuthenticator(authentication_Jwt)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Redis, err := config.ParseRedis(configv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userToken := biz2.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	moduleI18n := module.NewI18nFromResources(resources)
	i18nI18n, err := i18n.NewCatalog(moduleI18n)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHTTPMiddleware(ctx, authenticator, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	configv1Pprof, err := config.ParsePprof(configv1Bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(configv1Pprof)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	data_Queue, err := config.ParseQueue(configv1Bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	queueQueue, cleanup3, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configv1Oss, err := config.ParseOSS(configv1Bootstrap)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ossOSS, err := oss.NewOSS(configv1Oss)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configv1Translator, err := config.ParseTranslator(configv1Bootstrap)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	translatorTranslator, err := translator.NewTranslator(configv1Translator)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseCase, cleanup4 := biz2.NewBaseCase(ctx, pprofPprof, cacheCache, queueQueue, ossOSS, translatorTranslator, v2)
	jobStoreAdapter, err := core.NewJobStoreAdapter(v2)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseRegistry := sse.NewRegistry()
	streamIDResolver := sse.NewStreamResolver(sseRegistry, authenticator, userToken)
	v3 := backend.NewCodeGenManager()
	adminStreams, cleanup5, err := backend.NewStreams(v3, v2, baseCase, i18nI18n)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	streams := provideStreams(adminStreams)
	sseServer, cleanup6, err := sse.NewServer(ctx, streamIDResolver, streams, sseRegistry)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseSSE, cleanup7 := sse.NewSSE(authenticator, userToken, sseRegistry, sseServer)
	adminTasks, cleanup8, err := backend.NewTasks(v2, baseCase, sseSSE)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tasks := provideTasks(adminTasks)
	jobRegistry, err := job.NewRegistry(tasks)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	executionLocker := job.NewExecutionLocker(data_Redis)
	scheduler := job.NewSchedulerWithLocker(jobStoreAdapter, jobRegistry, executionLocker)
	jobJob := job.NewJob(scheduler)
	openapiOpenAPI := openapi.NewOpenAPI(registry)
	redactPolicyResolver, err := kit.NewRedactPolicyResolver(v2)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	adminModules, cleanup9, err := backend.NewModules(migrationMigration, configv1Bootstrap, v2, baseCase, engine, authenticator, userToken, jobJob, sseSSE, i18nI18n, openapiOpenAPI, redactPolicyResolver, v3)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	modules := provideModules(adminModules)
	mcpServer, cleanup10, err := mcp.NewServer(ctx, modules, redactPolicyResolver)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transportServer, err := server.NewHTTPServer(ctx, appInfo, httpMiddlewares, modules, authenticator, userToken, registry, mcpServer, sseServer, redactPolicyResolver)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcMiddlewares := server.NewGRPCMiddleware(ctx, authenticator, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	grpcServer, err := server.NewGRPCServer(ctx, grpcMiddlewares, modules, redactPolicyResolver)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logStoreAdapter, err := core.NewLogStoreAdapter(v2)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logPipeline, cleanup11 := biz2.NewLogPipeline(queueQueue, logStoreAdapter)
	adminConsumers, cleanup12, err := backend.NewQueueConsumers(v2, baseCase, sseSSE)
	if err != nil {
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	consumers := provideConsumers(adminConsumers)
	queueServer, err := queue2.NewServer(queueQueue, jobStoreAdapter, logPipeline, consumers)
	if err != nil {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobServer := job.NewServer(scheduler)
	app := kratoscore.NewApp(ctx, syncResult, transportServer, grpcServer, mcpServer, sseServer, queueServer, jobServer)
	return app, func() {
		cleanup12()
		cleanup11()
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// hostProviderSet 将 Admin 的具名贡献收口为 Core 最终集合。
var hostProviderSet = wire.NewSet(
	provideResources,
	provideModules,
	provideTasks,
	provideStreams,
	provideConsumers,
)
