// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/google/wire"
	"github.com/liujitcn/kratos-admin/gis/backend"
	"github.com/liujitcn/kratos-admin/gis/backend/adapter/core"
	"github.com/liujitcn/kratos-admin/gis/backend/adapter/kit"
	"github.com/liujitcn/kratos-core"
	biz2 "github.com/liujitcn/kratos-core/biz"
	"github.com/liujitcn/kratos-core/config"
	"github.com/liujitcn/kratos-core/data"
	"github.com/liujitcn/kratos-core/job"
	"github.com/liujitcn/kratos-core/mcp"
	"github.com/liujitcn/kratos-core/module"
	queue2 "github.com/liujitcn/kratos-core/queue"
	"github.com/liujitcn/kratos-core/resource"
	"github.com/liujitcn/kratos-core/resource/biz"
	"github.com/liujitcn/kratos-core/resource/i18n"
	"github.com/liujitcn/kratos-core/resource/migration"
	"github.com/liujitcn/kratos-core/resource/openapi"
	"github.com/liujitcn/kratos-core/server"
	"github.com/liujitcn/kratos-core/sse"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/queue"
)

import (
	_ "github.com/liujitcn/kratos-kit/database/gorm/driver/mysql"
	_ "github.com/liujitcn/kratos-kit/logger/zap"
	_ "github.com/liujitcn/kratos-kit/registry/consul"
)

// Injectors from wire.go:

// NewApp 通过 Core、GIS 和宿主 ProviderSet 注入并创建应用。
func NewApp(ctx *bootstrap.Context) (*kratos.App, func(), error) {
	configv1Bootstrap, err := config.ParseBootstrap(ctx)
	if err != nil {
		return nil, nil, err
	}
	v, err := config.ParseDatabase(configv1Bootstrap)
	if err != nil {
		return nil, nil, err
	}
	gisResources := gis.NewModuleResources()
	resources := provideResources(gisResources)
	models := module.NewModels(resources)
	v2, cleanup, err := data.NewClients(v, models)
	if err != nil {
		return nil, nil, err
	}
	migrations := module.NewMigrations(resources)
	migrationMigration, err := migration.NewMigration(ctx, v2, migrations)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	openAPI := module.NewOpenAPIFromResources(resources)
	registry, err := openapi.NewRegistry(openAPI)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	transaction, err := core.NewTransaction(v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	apiStoreAdapter, err := core.NewAPIStoreAdapter(v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseAPICase := biz.NewBaseAPICase(apiStoreAdapter)
	permissionStoreAdapter, err := core.NewPermissionStoreAdapter(v2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseTenantCase := biz.NewBaseTenantCase(transaction, permissionStoreAdapter)
	engine, err := biz2.NewAuthzEngine()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	casbinRuleCase, err := biz.NewCasbinRuleCase(permissionStoreAdapter, baseAPICase, engine)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	syncResult, err := resource.NewSyncResult(ctx, migrationMigration, registry, transaction, baseAPICase, baseTenantCase, casbinRuleCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appInfo, err := config.ParseAppInfo(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authentication_Jwt, err := config.ParseAuthnJWT(configv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authenticator, err := biz2.NewAuthenticator(authentication_Jwt)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Redis, err := config.ParseRedis(configv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userToken := biz2.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	moduleI18n := module.NewI18nFromResources(resources)
	i18nI18n, err := i18n.NewCatalog(moduleI18n)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHTTPMiddleware(ctx, authenticator, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	gisModules, cleanup3, err := gis.NewModules(configv1Bootstrap, v2, engine, authenticator)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	modules := provideModules(gisModules)
	redactPolicyResolver, err := kit.NewRedactPolicyResolver(v2)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpServer, cleanup4, err := mcp.NewServer(ctx, modules, redactPolicyResolver)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseRegistry := sse.NewRegistry()
	streamIDResolver := sse.NewStreamResolver(sseRegistry, authenticator, userToken)
	gisStreams, cleanup5, err := gis.NewStreams()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	streams := provideStreams(gisStreams)
	sseServer, cleanup6, err := sse.NewServer(ctx, streamIDResolver, streams, sseRegistry)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transportServer, err := server.NewHTTPServer(ctx, appInfo, httpMiddlewares, modules, authenticator, userToken, registry, mcpServer, sseServer, redactPolicyResolver)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcMiddlewares := server.NewGRPCMiddleware(ctx, authenticator, engine, userToken, authentication_Jwt, cacheCache, i18nI18n)
	grpcServer, err := server.NewGRPCServer(ctx, grpcMiddlewares, modules, redactPolicyResolver)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	data_Queue, err := config.ParseQueue(configv1Bootstrap)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	queueQueue, cleanup7, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobStoreAdapter, err := core.NewJobStoreAdapter(v2)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logStoreAdapter, err := core.NewLogStoreAdapter(v2)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logPipeline, cleanup8 := biz2.NewLogPipeline(queueQueue, logStoreAdapter)
	gisConsumers, cleanup9, err := gis.NewQueueConsumers()
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	consumers := provideConsumers(gisConsumers)
	queueServer, err := queue2.NewServer(queueQueue, jobStoreAdapter, logPipeline, consumers)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	gisTasks, cleanup10, err := gis.NewTasks()
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tasks := provideTasks(gisTasks)
	jobRegistry, err := job.NewRegistry(tasks)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	executionLocker := job.NewExecutionLocker(data_Redis)
	scheduler := job.NewSchedulerWithLocker(jobStoreAdapter, jobRegistry, executionLocker)
	jobServer := job.NewServer(scheduler)
	app := kratoscore.NewApp(ctx, syncResult, transportServer, grpcServer, mcpServer, sseServer, queueServer, jobServer)
	return app, func() {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// hostProviderSet 将 GIS 的具名贡献收口为 Core 最终集合。
var hostProviderSet = wire.NewSet(
	provideResources,
	provideModules,
	provideTasks,
	provideStreams,
	provideConsumers,
)
