// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: common/v1/analytics.proto

/* eslint-disable */

/** 分析时间类型。 */
export enum AnalyticsTimeType {
  /** ANALYTICS_TIME_TYPE_UNSPECIFIED - 未指定统计时间类型，服务端按默认周维度处理。 */
  ANALYTICS_TIME_TYPE_UNSPECIFIED = 0,
  /** ANALYTICS_TIME_TYPE_WEEK - 按周统计。 */
  ANALYTICS_TIME_TYPE_WEEK = 1,
  /** ANALYTICS_TIME_TYPE_MONTH - 按月统计。 */
  ANALYTICS_TIME_TYPE_MONTH = 2,
  /** ANALYTICS_TIME_TYPE_YEAR - 按年统计。 */
  ANALYTICS_TIME_TYPE_YEAR = 3,
}

/** 分析图表系列类型。 */
export enum AnalyticsSeriesType {
  /** ANALYTICS_SERIES_TYPE_UNSPECIFIED - 未指定图表系列类型。 */
  ANALYTICS_SERIES_TYPE_UNSPECIFIED = 0,
  /** ANALYTICS_SERIES_TYPE_BAR - 柱状图系列。 */
  ANALYTICS_SERIES_TYPE_BAR = 1,
  /** ANALYTICS_SERIES_TYPE_LINE - 折线图系列。 */
  ANALYTICS_SERIES_TYPE_LINE = 2,
}

/** 分析时间请求参数。 */
export interface AnalyticsTimeRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 趋势分析系列。 */
export interface AnalyticsTrendSeries {
  /** 系列名称 */
  name: string;
  /** 图表类型 */
  type: AnalyticsSeriesType;
  /** 数据数组 */
  data: number[];
  /** Y轴索引 */
  y_axis_index: number;
}

/** 趋势分析响应。 */
export interface AnalyticsTrendResponse {
  /** 坐标轴数据 */
  axis: string[];
  /** 系列列表 */
  series: AnalyticsTrendSeries[];
  /** Y轴名称列表 */
  y_axis_names: string[];
}

/** 排行分析项。 */
export interface AnalyticsRankItem {
  /** 名称 */
  name: string;
  /** 值 */
  value: number;
}

/** 排行分析响应。 */
export interface AnalyticsRankResponse {
  /** 排行列表 */
  items: AnalyticsRankItem[];
}

/** 占比分析项。 */
export interface AnalyticsPieItem {
  /** 名称 */
  name: string;
  /** 值 */
  value: number;
}

/** 占比分析响应。 */
export interface AnalyticsPieResponse {
  /** 饼图数据 */
  items: AnalyticsPieItem[];
}
