syntax = "proto3";

package system.app.v1;

import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "system/common/v1/common.proto";
import "buf/validate/validate.proto";

// App用户认证服务
service AuthService {
  // 获取已经登录的用户的数据
  rpc GetUserProfile(GetUserProfileRequest) returns (UserProfileForm) {
    option (google.api.http) = {
      get: "/api/v1/app/auth/profile"
    };
  }

  // 修改个人中心用户信息
  rpc UpdateUserProfile(UpdateUserProfileRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/api/v1/app/auth/profile"
      body: "user_profile"
    };
  }

  // 手机号授权
  rpc BindUserPhone(BindUserPhoneRequest) returns (BindUserPhoneResponse) {
    option (google.api.http) = {
      put: "/api/v1/app/auth/phone"
      body: "*"
    };
  }
}

// 获取用户资料请求参数
message GetUserProfileRequest {}

// 用户资料表单
message UserProfileForm {
  string user_name = 1 [(gnostic.openapi.v3.property) = {description: "用户账号"}]; // 用户账号

  string nick_name = 2 [(gnostic.openapi.v3.property) = {description: "用户昵称"}]; // 用户昵称

  int32 gender = 3 [(gnostic.openapi.v3.property) = {description: "性别"}]; // 性别

  string phone = 4 [(gnostic.openapi.v3.property) = {description: "手机号"}]; // 手机号

  string email = 6 [(gnostic.openapi.v3.property) = {description: "邮箱"}, (buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE, (buf.validate.field).string.email = true, (buf.validate.field).cel = {id: "system.app.auth.profile.email.max_length" message: "邮箱不能超过 128 个字符" expression: "this.size() <= 128"}]; // 邮箱

  .system.common.v1.BaseUserIDType id_type = 7 [(gnostic.openapi.v3.property) = {description: "证件类型：枚举【BaseUserIDType】"}, (buf.validate.field).enum = {defined_only: true}]; // 证件类型：枚举【BaseUserIDType】

  string id_code = 8 [(gnostic.openapi.v3.property) = {description: "证件号"}, (buf.validate.field).cel = {id: "system.app.auth.profile.id_code.format" message: "请输入正确的证件号" expression: "this.size() == 0 || this.matches('^[A-Za-z0-9][A-Za-z0-9-]{0,63}$')"}]; // 证件号

  string avatar = 5 [(gnostic.openapi.v3.property) = {description: "头像"}]; // 头像
}

// 更新用户资料请求参数
message UpdateUserProfileRequest {
  UserProfileForm user_profile = 1 [(gnostic.openapi.v3.property) = {description: "用户资料"}]; // 用户资料
}

// 手机号授权请求参数
message BindUserPhoneRequest {
  string code = 1 [(gnostic.openapi.v3.property) = {description: "授权信息"}]; // 授权信息
}

// 手机号授权响应
message BindUserPhoneResponse {
  string phone = 1 [(gnostic.openapi.v3.property) = {description: "手机号"}]; // 手机号
}
