syntax = "proto3";

package base.v1;

import "buf/validate/validate.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

// Base系统配置公共服务
service ConfigService {
  // 获取系统配置
  rpc GetConfig(GetConfigRequest) returns (GetConfigResponse) {
    option (google.api.http) = {
      get: "/api/v1/base/config"
    };
  }
}

// 系统配置位置。
enum BaseConfigSite {
  // 未指定系统配置位置。
  BASE_CONFIG_SITE_UNSPECIFIED = 0;
  // 系统内使用。
  BASE_CONFIG_SITE_SYSTEM = 1;
  // 管理端。
  BASE_CONFIG_SITE_ADMIN = 2;
  // 移动端。
  BASE_CONFIG_SITE_APP = 3;
}

// 获取系统配置条件
message GetConfigRequest {
  BaseConfigSite site = 2 [(gnostic.openapi.v3.property) = {description: "位置：枚举【BaseConfigSite】"}, (buf.validate.field).enum = {defined_only: true}, (buf.validate.field).cel = {id: "base.config.get.site.required" message: "位置不能为空" expression: "this != 0"}]; // 位置：枚举【BaseConfigSite】
}

// 系统配置项
message ConfigItem {
  int64 id = 1 [(gnostic.openapi.v3.property) = {description: "配置ID"}]; // 配置ID

  string key = 2 [(gnostic.openapi.v3.property) = {description: "配置key"}]; // 配置key

  string value = 3 [(gnostic.openapi.v3.property) = {description: "配置value"}]; // 配置value
}

// 系统配置查询结果
message GetConfigResponse {
  repeated ConfigItem configs = 1 [(gnostic.openapi.v3.property) = {description: "系统配置列表"}]; // 系统配置列表

  bool ai_enabled = 2 [(gnostic.openapi.v3.property) = {description: "AI assistant availability"}]; // AI 助手是否可用
}
