-- 脱敏规则示例及用户管理入库、出库策略。
-- 表结构由 GORM AutoMigrate 根据生成模型创建，本文件只初始化示例模板和运行时策略。

SET NAMES utf8mb4;
SET @old_foreign_key_checks = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

-- base_redact_storage_policy：按数据源和物理表字段保存入库脱敏策略，旁表保存加密原文和精确查询摘要。
INSERT IGNORE INTO `base_redact_storage_policy` (`id`, `tenant_id`, `source_name`, `table_name`, `column_name`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (2001, 1, 'default', 'base_user', 'phone', 2, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户手机号入库保护', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_storage_policy` (`id`, `tenant_id`, `source_name`, `table_name`, `column_name`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (2002, 1, 'default', 'base_user', 'email', 3, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户邮箱入库保护', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_storage_policy` (`id`, `tenant_id`, `source_name`, `table_name`, `column_name`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (2003, 1, 'default', 'base_user', 'id_code', 10, '{"fixed_length":{"char":"X"}}', 1, '用户证件号入库保护', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_storage_policy` (`id`, `tenant_id`, `source_name`, `table_name`, `column_name`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (2004, 1, 'default', 'base_oauth_provider', 'client_secret', 11, '{"encrypt":{"algorithm":"AES_GCM"}}', 1, 'OAuth第三方应用密钥直接加密', 1, 1, '2026-09-23 00:00:00', '2026-09-23 00:00:00', 0);

-- base_redact_output_policy：按服务名、operation 和响应字段精确匹配出库规则。
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3001, 1, '/system.admin.v1.BaseUserService/ListBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'phone', 1, 2, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户列表手机号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3002, 1, '/system.admin.v1.BaseUserService/ListBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'email', 1, 3, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户列表邮箱出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3003, 1, '/system.admin.v1.BaseUserService/ListBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'id_code', 1, 10, '{"fixed_length":{"char":"X"}}', 1, '用户列表证件号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3011, 1, '/system.admin.v1.BaseUserService/PageBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'phone', 1, 2, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户分页手机号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3012, 1, '/system.admin.v1.BaseUserService/PageBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'email', 1, 3, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户分页邮箱出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3013, 1, '/system.admin.v1.BaseUserService/PageBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'id_code', 1, 10, '{"fixed_length":{"char":"X"}}', 1, '用户分页证件号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3021, 1, '/system.admin.v1.BaseUserService/GetBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUserForm', 'phone', 1, 2, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户详情手机号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3022, 1, '/system.admin.v1.BaseUserService/GetBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUserForm', 'email', 1, 3, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户详情邮箱出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);
INSERT IGNORE INTO `base_redact_output_policy` (`id`, `tenant_id`, `operation`, `service_name`, `message_ref`, `field_path`, `mode`, `rule_id`, `rule_params`, `status`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) VALUES (3023, 1, '/system.admin.v1.BaseUserService/GetBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUserForm', 'id_code', 1, 10, '{"fixed_length":{"char":"X"}}', 1, '用户详情证件号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0);

SET FOREIGN_KEY_CHECKS = @old_foreign_key_checks;
