-- 脱敏规则模板及用户管理入库、出库策略。
-- 表结构由 GORM AutoMigrate 根据生成模型创建，本文件只初始化固定模板和运行时策略。
-- base_redact_storage_policy：按数据源和物理表字段保存入库脱敏策略，旁表保存加密原文和精确查询摘要。
INSERT INTO "base_redact_storage_policy" ("id", "source_name", "table_name", "column_name", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (2001, 'default', 'base_user', 'phone', 1001, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户手机号入库保护', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_storage_policy" ("id", "source_name", "table_name", "column_name", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (2002, 'default', 'base_user', 'email', 1002, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户邮箱入库保护', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_storage_policy" ("id", "source_name", "table_name", "column_name", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (2003, 'default', 'base_user', 'id_code', 1009, '{"fixed_length":{"char":"X"}}', 1, '用户证件号入库保护', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
-- base_redact_output_policy：按服务名、operation 和响应字段精确匹配出库规则。
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3001, '/system.admin.v1.BaseUserService/ListBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'phone', 1, 1001, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户列表手机号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3002, '/system.admin.v1.BaseUserService/ListBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'email', 1, 1002, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户列表邮箱出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3003, '/system.admin.v1.BaseUserService/ListBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'id_code', 1, 1009, '{"fixed_length":{"char":"X"}}', 1, '用户列表证件号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3011, '/system.admin.v1.BaseUserService/PageBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'phone', 1, 1001, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户分页手机号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3012, '/system.admin.v1.BaseUserService/PageBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'email', 1, 1002, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户分页邮箱出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3013, '/system.admin.v1.BaseUserService/PageBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUser', 'id_code', 1, 1009, '{"fixed_length":{"char":"X"}}', 1, '用户分页证件号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3021, '/system.admin.v1.BaseUserService/GetBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUserForm', 'phone', 1, 1001, '{"mask":{"keep_first":3,"keep_last":4,"mask_char":"*"}}', 1, '用户详情手机号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3022, '/system.admin.v1.BaseUserService/GetBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUserForm', 'email', 1, 1002, '{"email":{"keep_local_first":2,"mask_domain":false,"mask_char":"*"}}', 1, '用户详情邮箱出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
INSERT INTO "base_redact_output_policy" ("id", "operation", "service_name", "message_ref", "field_path", "mode", "rule_id", "rule_params", "status", "remark", "created_by", "updated_by", "created_at", "updated_at", "deleted_at") VALUES (3023, '/system.admin.v1.BaseUserService/GetBaseUser', 'system.admin.v1.BaseUserService', 'system.admin.v1.BaseUserForm', 'id_code', 1, 1009, '{"fixed_length":{"char":"X"}}', 1, '用户详情证件号出库掩码', 1, 1, '2026-09-05 00:00:00', '2026-09-05 00:00:00', 0) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('base_redact_output_policy', 'id'), COALESCE((SELECT MAX(id) FROM "base_redact_output_policy"), 1), true);
SELECT setval(pg_get_serial_sequence('base_redact_storage_policy', 'id'), COALESCE((SELECT MAX(id) FROM "base_redact_storage_policy"), 1), true);
