data:
    database:
        connection_max_lifetime: 300s
        debug: true
        driver: postgres
        enable_metrics: false
        enable_migrate: true
        enable_trace: false
        max_idle_connections: 25
        max_open_connections: 25
        source: postgres://postgre:postgre@127.0.0.1:5455/gis?sslmode=disable
    redis:
        addr:
            - 127.0.0.1:6379
        db: 4
    queue:
        memory:
            pool_size: 1000
