ai:
  model:
    type: CLOUD_MODEL
    model_name: gpt-5.6
    cloud:
      base_url: http://subapi.openclawrouter.site/v1
      api_key: ENC[y84v5UY0idWEvUxMqCf1MXULmDyOOmKB3AH6Z4PjQ0PBPO04gBpJPUM4lHCQ9E-6FDT552sWRpDS5-ww4Y9joVFabNXX1lk4uhxzYrcDDNlD5DRQDmdA1eXh5TLT_gA]
