ai:
  model:
    type: CLOUD_MODEL
    model_name: gpt-5.6
    cloud:
      base_url: http://subapi.openclawrouter.site/v1
      api_key: ENC[hnvWoWJuSdBnoLwI1F3r-3kYvN0p2oNcFhfr1TVEHc03SGcCR0DSzJ9-0PgQYXC8vyKtBBKPqRVXMCbKfuHu7v4Nk7awujuxBbAEmM2xNkeH]
