data:
    database:
        connection_max_lifetime: 300s
        debug: true
        driver: mysql
        enable_metrics: false
        enable_migrate: true
        enable_trace: false
        max_idle_connections: 25
        max_open_connections: 25
        source: root:root@tcp(host.docker.internal:3306)/kratos_admin?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
    redis:
        addr:
            - host.docker.internal:6379
        db: 3
    queue:
        memory:
            pool_size: 1000