data:
    database:
        connection_max_lifetime: 300s
        debug: true
        driver: postgres
        enable_metrics: false
        enable_migrate: true
        enable_trace: false
        max_idle_connections: 25
        max_open_connections: 25
        source: host=127.0.0.1 user=postgre password=postgre dbname=kratos_admin port=5455 sslmode=disable TimeZone=Asia/Shanghai
