data:
    database:
        connection_max_lifetime: 300s
        debug: true
        driver: postgres
        enable_metrics: false
        enable_migrate: true
        enable_trace: false
        max_idle_connections: 25
        max_open_connections: 25
        source: host=host.docker.internal user=postgre password=postgre dbname=kratos_admin port=5455 sslmode=disable TimeZone=Asia/Shanghai
    redis:
        addr:
            - host.docker.internal:6379
        db: 3
    queue:
        memory:
            pool_size: 1000