data:
    database:
        connection_max_lifetime: 300s
        debug: true
        driver: postgres
        enable_metrics: false
        enable_migrate: false
        enable_trace: false
        max_idle_connections: 25
        max_open_connections: 25
        source: host=127.0.0.1 port=5455 user=postgre password=postgre dbname=kratos_admin sslmode=disable
    redis:
        addr:
            - 127.0.0.1:6379
        db: 3
#        password: 
    queue:
        memory:
            pool_size: 1000

