mfa:
  webauthn:
    rp_id: localhost
    rp_origins:
      - http://localhost:7001
      - http://127.0.0.1:7001
      - http://localhost:5002
      - http://127.0.0.1:5002
      - http://localhost:5004
      - http://127.0.0.1:5004
      - http://localhost:8848
      - http://127.0.0.1:8848
