oauth:
  providers:
    gitee:
      client_id: a23f23168a3baef3f37b37d136400a7118278ba6ec3b8f18315727581ddeba4b
      client_secret: ENC[Xjo-0Zebyc9VmgVWNYBrftLMeCFdTHIM4-JpAwHs]
      redirect_uri: http://127.0.0.1:7001/api/v1/base/oauth/gitee/callback
    github:
      client_id: Ov23litVBeilJRE8TgOk
      client_secret: ENC[ZyU0FKkT-1jcxbnK3Z6l6PNkUKcKoD_DP7aSio9N]
      redirect_uri: http://127.0.0.1:7001/api/v1/base/oauth/github/callback
    google:
      client_id: 97409157491-jak87hoo8odjb5e0capltnklk5iqjqhq.apps.googleusercontent.com
      client_secret: ENC[ewgGtBt3QRTXkhZdRrXswdCUJw3J5QERRVKpkFxI]
      redirect_uri: http://127.0.0.1:7001/api/v1/base/oauth/google/callback
    wechatmini:
      client_id: wx3fe0d8a39051f39a
      client_secret: ENC[BehEa3-z-Aqzn82fAuKhd2mWP77cdU0OhkIQpS_O]
