oauth:
  providers:
    github:
      client_id: Ov23litVBeilJRE8TgOk
      client_secret: dev-placeholder-secret
      redirect_uri: http://127.0.0.1:7001/api/v1/base/oauth/github/callback
      scopes:
        - user:email
    gitee:
      client_id: a23f23168a3baef3f37b37d136400a7118278ba6ec3b8f18315727581ddeba4b
      client_secret: dev-placeholder-secret
      redirect_uri: http://127.0.0.1:7001/api/v1/base/oauth/gitee/callback
      scopes:
        - user_info
    google:
      client_id: 97409157491-jak87hoo8odjb5e0capltnklk5iqjqhq.apps.googleusercontent.com
      client_secret: dev-placeholder-secret
      redirect_uri: http://127.0.0.1:7001/api/v1/base/oauth/google/callback
      scopes:
        - openid
        - profile
        - email
    wechatmini:
      client_id: wx80073bcc341e31fb
      client_secret: dev-placeholder-secret
