oss:
  type: s3
  root_directory: ./data
  minio:
    endpoint: 127.0.0.1:9000
    access_key: snopadmin
    secret_key: "snop_dev_2026"
    token: ''
    bucket_name: kratos-admin
    use_ssl: false
  s3:
    endpoint: http://127.0.0.1:9000
    region: us-east-1
    access_key: snopadmin
    secret_key: "snop_dev_2026"
    token: ''
    bucket_name: kratos-admin
    use_ssl: false
    force_path_style: true
