// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/common/v1/common.proto

/* eslint-disable */

/** 系统公共用户相关枚举。 */
export enum BaseUserIDType {
  /** BASE_USER_ID_TYPE_UNSPECIFIED - 未指定证件类型。 */
  BASE_USER_ID_TYPE_UNSPECIFIED = 0,
  /** BASE_USER_ID_TYPE_ID_CARD - 居民身份证。 */
  BASE_USER_ID_TYPE_ID_CARD = 1,
  /** BASE_USER_ID_TYPE_PASSPORT - 护照。 */
  BASE_USER_ID_TYPE_PASSPORT = 2,
  /** BASE_USER_ID_TYPE_HK_MACAO_PERMIT - 港澳居民来往内地通行证。 */
  BASE_USER_ID_TYPE_HK_MACAO_PERMIT = 3,
  /** BASE_USER_ID_TYPE_TAIWAN_PERMIT - 台湾居民来往大陆通行证。 */
  BASE_USER_ID_TYPE_TAIWAN_PERMIT = 4,
  /** BASE_USER_ID_TYPE_FOREIGN_PERMANENT_RESIDENCE - 外国人永久居留身份证。 */
  BASE_USER_ID_TYPE_FOREIGN_PERMANENT_RESIDENCE = 5,
  /** BASE_USER_ID_TYPE_OTHER - 其他证件。 */
  BASE_USER_ID_TYPE_OTHER = 6,
}

/** 用户密码修改状态。 */
export enum BaseUserPasswordChangeStatus {
  /** BASE_USER_PASSWORD_CHANGE_STATUS_UNSPECIFIED - 未指定密码修改状态。 */
  BASE_USER_PASSWORD_CHANGE_STATUS_UNSPECIFIED = 0,
  /** BASE_USER_PASSWORD_CHANGE_STATUS_REQUIRED - 当前必须修改密码。 */
  BASE_USER_PASSWORD_CHANGE_STATUS_REQUIRED = 1,
  /** BASE_USER_PASSWORD_CHANGE_STATUS_NOT_REQUIRED - 当前无需修改密码。 */
  BASE_USER_PASSWORD_CHANGE_STATUS_NOT_REQUIRED = 2,
}
