// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: system/config/v1/system_config.proto

/* eslint-disable */

/**
 * BaseLogFallbackConfig 日志入库回退配置。
 * 审计日志队列异常或无法入库时，写入回退文件，后续由定时任务重新写入日志表。
 */
export interface BaseLogFallbackConfig {
  /** 日志入库回退目录路径 */
  file_path: string;
}
